from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd

from nh_importer import canonical_overseas_position_key

AUTO_START = "<!-- AUTO-GENERATED:START -->"
AUTO_END = "<!-- AUTO-GENERATED:END -->"


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path, dtype={"ticker": str}, encoding="utf-8-sig")
    except Exception:
        return pd.DataFrame()


def markdown_table(df: pd.DataFrame, columns: list[str] | None = None, limit: int | None = None) -> str:
    if df.empty:
        return "_표시할 데이터가 없습니다._"
    view = df.copy()
    if columns:
        view = view[[c for c in columns if c in view.columns]]
    if limit:
        view = view.head(limit)
    headers = list(view.columns)
    lines = ["| " + " | ".join(headers) + " |", "| " + " | ".join(["---"] * len(headers)) + " |"]
    for _, row in view.iterrows():
        vals = [str(row.get(c, "")).replace("\n", " ") for c in headers]
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines)


def summary_value(summary: pd.DataFrame, metric: str) -> str:
    if summary.empty or "metric" not in summary.columns or "value" not in summary.columns:
        return ""
    rows = summary[summary["metric"].astype(str) == metric]
    if rows.empty:
        return ""
    value = rows["value"].iloc[0]
    if pd.isna(value):
        return ""
    return str(value)


def balance_data_warning(summary: pd.DataFrame) -> str:
    available = summary_value(summary, "balance_data_available").strip().lower()
    if available in {"false", "0", "no"}:
        return "> [!warning] 잔고자료 미반영\n> 현재 raw 폴더에 종합잔고/ISA잔고/해외증권잔고 파일이 없어 포트폴리오 가치, 평가손익, 수익률을 산출하지 않았습니다. 거래내역은 `processed_transactions.csv`에만 반영됩니다."
    return ""


def replace_autogenerated_block(path: Path, content: str, dry_run: bool = False) -> tuple[bool, str]:
    if not path.exists():
        text = f"# {path.stem}\n\n{AUTO_START}\n{content.rstrip()}\n{AUTO_END}\n"
    else:
        text = path.read_text(encoding="utf-8-sig")
        if AUTO_START not in text or AUTO_END not in text:
            return False, f"{path} has no AUTO-GENERATED markers"
        pattern = re.compile(re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), re.S)
        replacement = f"{AUTO_START}\n{content.rstrip()}\n{AUTO_END}"
        text = pattern.sub(lambda _m: replacement, text)
    if not dry_run:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text.rstrip() + "\n", encoding="utf-8")
    return True, ""


def dashboard_content(name: str, processed_dir: Path) -> str:
    summary = read_csv(processed_dir / "portfolio_summary.csv")
    holdings = read_csv(processed_dir / "processed_holdings.csv")
    risk = read_csv(processed_dir / "risk_watchlist.csv")
    review = read_csv(processed_dir / "review_queue.csv")
    history = read_csv(processed_dir / "history_queue.csv")
    cash = read_csv(processed_dir / "processed_cashflows.csv")
    dividends = read_csv(processed_dir / "processed_dividends.csv")
    sources = read_csv(processed_dir / "source_file_index.csv")
    qa = read_csv(processed_dir / "qa_exceptions.csv")
    unclassified = read_csv(processed_dir / "unclassified_rows.csv")
    warning = balance_data_warning(summary)

    if name == "Portfolio.md":
        return "\n".join([warning, "_CSV/SQLite 기준 생성 요약_", markdown_table(summary), "\n## 보유종목", markdown_table(holdings, ["ticker", "security_name", "account_type", "market", "asset_type", "currency", "evaluation_amount", "unrealized_pnl", "pnl_pct", "weight_pct"], 50)]).strip()
    if name == "Exposure.md":
        if holdings.empty or "evaluation_amount" not in holdings:
            return "\n".join([warning, "_노출도 계산 데이터가 없습니다._"]).strip()
        parts = []
        for key in ["account_type", "market", "asset_type", "currency"]:
            if key in holdings:
                g = holdings.groupby(key, dropna=False)["evaluation_amount"].sum().reset_index()
                total = g["evaluation_amount"].sum()
                g["weight_pct"] = g["evaluation_amount"].apply(lambda v: round(v / total * 100, 2) if total else 0)
                parts.append(f"## {key}\n" + markdown_table(g))
        lev = holdings[holdings.get("is_leveraged", False) == True] if "is_leveraged" in holdings else pd.DataFrame()
        parts.append("## leveraged ETF exposure\n" + markdown_table(lev, ["ticker", "security_name", "evaluation_amount", "weight_pct"]))
        return "\n\n".join(parts)
    if name == "Cashflows.md":
        return "\n".join(["## 현금흐름", markdown_table(cash, ["trade_date", "transaction_type", "account_type", "settlement_amount", "currency"], 100), "\n## 배당/분배금", markdown_table(dividends, ["trade_date", "ticker", "security_name", "settlement_amount", "currency"], 100)])
    if name == "Import_Review.md":
        status_rows = summary[summary.get("metric", pd.Series(dtype=str)).isin(["raw_file_count", "transaction_history_file_count", "holdings_file_count", "balance_data_available", "total_portfolio_value_status", "total_portfolio_value_basis", "portfolio_summary_estimated", "data_quality_warning"])] if not summary.empty else summary
        return "\n".join([warning, "## Data status", markdown_table(status_rows), "\n## Imported source files", markdown_table(sources), "\n## Unclassified transaction rows", markdown_table(unclassified, limit=50), "\n## Next actions\n- unclassified row가 있으면 컬럼 매핑 또는 거래유형 키워드를 보완하세요.\n- 잔고자료 미반영 경고가 있으면 종합잔고/ISA잔고/해외증권잔고 파일을 raw 폴더에 추가하세요.\n- sensitive warning이 있으면 generated Markdown에 노출되지 않았는지 확인하세요."]).strip()
    if name == "Risk_Watchlist.md":
        return "\n".join([warning, markdown_table(risk, ["ticker", "security_name", "account_type", "risk_flags", "pnl_pct", "weight_pct", "suggested_action"], 100)]).strip()
    if name == "Review_Queue.md":
        return "\n".join([warning, markdown_table(review, ["ticker", "security_name", "reason", "severity", "suggested_action"], 100)]).strip()
    if name == "History_Queue.md":
        return "\n".join(["_현재 보유수량과 평가금액이 0인 과거 거래종목 후보입니다. 기본 Review Queue에서는 제외됩니다._", markdown_table(history, ["ticker", "security_name", "account_type", "market", "history_reason", "suggested_destination", "suggested_action"], 200)])
    if name == "QA_Exceptions.md":
        return markdown_table(qa, ["exception_id", "severity", "file", "issue", "suggested_fix"], 200)
    return "_지원하지 않는 대시보드입니다._"


def safe_component(value: Any) -> str:
    s = str(value or "").strip() or "UNKNOWN"
    return re.sub(r"[^0-9A-Za-z가-힣._-]+", "_", s).strip("_")


def parse_note_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end == -1:
        return {}
    meta: dict[str, str] = {}
    for line in text[3:end].splitlines():
        if ":" not in line or line.lstrip().startswith("#"):
            continue
        key, value = line.split(":", 1)
        meta[key.strip()] = value.strip().strip('"').strip("'")
    return meta


def company_note_identity_key(row: dict[str, Any] | pd.Series) -> str:
    asset_type = str(row.get("asset_type", "") or "").strip().lower()
    if asset_type == "cash":
        return ""
    canonical = canonical_overseas_position_key(row)
    if canonical and not canonical.startswith("CASH:"):
        return canonical
    ticker = str(row.get("ticker", "") or "").strip().upper()
    return f"TICKER:{ticker}" if ticker else ""


def existing_company_note_index(company_root: Path) -> dict[str, Path]:
    index: dict[str, Path] = {}
    if not company_root.exists():
        return index
    for path in sorted(company_root.glob("*/Company.md")):
        try:
            text = path.read_text(encoding="utf-8-sig")
        except Exception:
            continue
        meta = parse_note_frontmatter(text)
        ticker = str(meta.get("ticker", "") or path.parent.name).strip()
        row = {
            "ticker": ticker,
            "security_name": meta.get("name", ""),
            "market": meta.get("market", ""),
            "asset_type": meta.get("asset_type", ""),
        }
        for key in {
            f"FOLDER:{path.parent.name.upper()}",
            f"TICKER:{ticker.upper()}" if ticker else "",
            company_note_identity_key(row),
        }:
            if key:
                index.setdefault(key, path)
    return index


def new_company_note(row: pd.Series) -> str:
    ticker = str(row.get("ticker", "") or "UNKNOWN")
    name = str(row.get("security_name", "") or ticker)
    asset_type = str(row.get("asset_type", "stock") or "stock")
    is_lev = bool(row.get("is_leveraged", False))
    etf_extra = ""
    if asset_type == "etf" or is_lev:
        etf_extra = """underlying_asset:
leverage_factor:
rebalance_type:
long_term_holding_allowed: false
volatility_decay_risk: true
leveraged_etf_rule_link: "[[05_Principles/Leveraged_ETF_Rules]]"
"""
    return f"""---
type: company
ticker: "{ticker}"
name: "{name}"
market: "{row.get('market', '')}"
asset_type: "{asset_type}"
account: "{row.get('account_type', '')}"
currency: "{row.get('currency', '')}"
status: "position"
weight_pct: {row.get('weight_pct', '')}
pnl_pct: {row.get('pnl_pct', '')}
is_leveraged: {str(is_lev).lower()}
{etf_extra}review_status: "needs_user_review"
risk_level:
last_review:
next_review:
source_files:
  - "{row.get('source_file', '')}"
tags:
  - investment
  - company
---

# {name} / {ticker}

## 자동 업데이트 영역
{AUTO_START}
- 비중: {row.get('weight_pct', '')}
- 평가손익률: {row.get('pnl_pct', '')}
- 계좌: {row.get('account_type', '')}
- 최근 점검일:
- 리스크 플래그:
- 원천자료: {row.get('source_file', '')}
{AUTO_END}

## 사용자 판단 영역
### 1. 매수 이유
### 2. 계속 보유하려는 이유
### 3. 핵심 확인 지표
### 4. 펀더멘털 훼손 기준
### 5. -10% 하락 시 대응
### 6. 추가매수 조건
### 7. 매도/비중축소 조건

## AI 점검 기록
## 관련 Risk Event
## 관련 Decision
## 원천자료 링크
"""


def write_company_notes(vault_root: Path, processed_dir: Path, create_companies: bool = False, dry_run: bool = False) -> list[str]:
    warnings: list[str] = []
    holdings = read_csv(processed_dir / "processed_holdings.csv")
    if holdings.empty:
        return warnings
    holdings["ticker"] = holdings.get("ticker", "").astype(str)
    holdings = holdings[~holdings["ticker"].str.lower().isin(["", "nan", "none"])].drop_duplicates(subset=["account_type", "ticker"], keep="last")
    if "asset_type" in holdings.columns:
        holdings = holdings[holdings["asset_type"].fillna("").astype(str).str.lower() != "cash"]
    seen_warnings: set[str] = set()
    company_root = vault_root / "20_Companies"
    note_index = existing_company_note_index(company_root)
    for _, row in holdings.iterrows():
        ticker = safe_component(row.get("ticker"))
        expected_path = company_root / ticker / "Company.md"
        path = expected_path
        if not path.exists():
            path = note_index.get(company_note_identity_key(row)) or note_index.get(f"TICKER:{str(row.get('ticker', '')).strip().upper()}") or expected_path
        content = f"- 비중: {row.get('weight_pct', '')}\n- 평가손익률: {row.get('pnl_pct', '')}\n- 계좌: {row.get('account_type', '')}\n- 최근 점검일:\n- 리스크 플래그:\n- 원천자료: {row.get('source_file', '')}"
        if path.exists():
            ok, warning = replace_autogenerated_block(path, content, dry_run=dry_run)
            if not ok:
                warnings.append(warning)
        elif create_companies:
            if not dry_run:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(new_company_note(row), encoding="utf-8")
                for key in {
                    f"FOLDER:{path.parent.name.upper()}",
                    f"TICKER:{str(row.get('ticker', '')).strip().upper()}",
                    company_note_identity_key(row),
                }:
                    if key:
                        note_index.setdefault(key, path)
        else:
            warning = f"{path} missing; run with --create-companies to create"
            if warning not in seen_warnings:
                warnings.append(warning)
                seen_warnings.add(warning)
    return warnings


def write_dashboards(vault_root: Path, processed_dir: Path | None = None, dry_run: bool = False) -> list[str]:
    processed_dir = processed_dir or vault_root / "70_Imports" / "processed"
    warnings: list[str] = []
    for name in ["Portfolio.md", "Exposure.md", "Cashflows.md", "Import_Review.md", "Risk_Watchlist.md", "Review_Queue.md", "History_Queue.md", "QA_Exceptions.md"]:
        path = vault_root / "10_Dashboard" / name
        ok, warning = replace_autogenerated_block(path, dashboard_content(name, processed_dir), dry_run=dry_run)
        if not ok:
            warnings.append(warning)
    return warnings
