from __future__ import annotations

import re
from datetime import date
from pathlib import Path
from typing import Any

import pandas as pd

from nh_importer import detect_sensitive, is_cash_asset_name, is_leveraged_etf_name, is_principal_cashflow_row, safe_source_name
from obsidian_writer import (
    AUTO_END,
    AUTO_START,
    company_note_identity_key,
    existing_company_note_index,
    qa_exception_cards,
    replace_autogenerated_block,
    safe_component,
)
from portfolio_model import has_filled_section, parse_frontmatter


BLANK_VALUES = {"", "nan", "none", "na", "n/a", "<na>", "-", "--"}
BROKER_KRW_SOURCES = {"broker_krw", "broker_provided_krw", "broker_krw_amount"}
FX_KRW_SOURCES = {"fx_rate_to_krw", "derived_krw_from_fx"}
RESIDUAL_EXCEPTION_THRESHOLD_KRW = 1000.0


def read_csv(path: Path) -> pd.DataFrame:
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path, dtype={"ticker": str}, encoding="utf-8-sig")
    except Exception:
        return pd.DataFrame()


def add(rows: list[dict[str, Any]], exception_id: str, severity: str, file: str, issue: str, suggested_fix: str) -> None:
    rows.append({"exception_id": exception_id, "severity": severity, "file": file, "issue": issue, "suggested_fix": suggested_fix})


def is_blank(value: Any) -> bool:
    if value is None:
        return True
    try:
        if pd.isna(value):
            return True
    except Exception:
        pass
    return str(value).strip().lower() in BLANK_VALUES


def text_value(value: Any) -> str:
    return "" if is_blank(value) else str(value).strip()


def lower_value(value: Any) -> str:
    return text_value(value).lower()


def bool_value(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    return lower_value(value) in {"true", "1", "yes", "y"}


def optional_number(value: Any) -> float | None:
    if is_blank(value):
        return None
    try:
        return float(str(value).replace(",", "").strip())
    except Exception:
        return None


def row_status(row: pd.Series, *fields: str) -> str:
    for field in fields:
        if field in row.index:
            value = lower_value(row.get(field))
            if value:
                return value
    return ""


def processed_row_ref(file_name: str, idx: int) -> str:
    return f"70_Imports/processed/{file_name}:row{idx + 2}"


def days_old(value: Any) -> int | None:
    if value is None or str(value).strip() == "":
        return None
    try:
        parsed = pd.to_datetime(value)
        if pd.isna(parsed):
            return None
        dt = parsed.date()
    except Exception:
        return None
    return (date.today() - dt).days


def generated_blocks(text: str) -> list[str]:
    return re.findall(re.escape(AUTO_START) + r"(.*?)" + re.escape(AUTO_END), text, re.S)


def is_cash_company_note(path: Path, meta: dict[str, Any]) -> bool:
    asset_type = str(meta.get("asset_type", "") or "").strip().lower()
    ticker = str(meta.get("ticker", "") or path.parent.name).strip()
    name = str(meta.get("name", "") or path.parent.name).strip()
    return asset_type == "cash" or is_cash_asset_name(name, ticker)


def active_company_note_targets(vault_root: Path, processed_dir: Path) -> dict[str, set[str]]:
    """Return active Company note paths keyed by normalized holding identity."""
    holdings = read_csv(processed_dir / "processed_holdings.csv")
    if holdings.empty:
        return {}
    company_root = vault_root / "20_Companies"
    note_index = existing_company_note_index(company_root)
    targets: dict[str, set[str]] = {}
    for _, row in holdings.iterrows():
        asset_type = str(row.get("asset_type", "") or "").strip().lower()
        ticker = str(row.get("ticker", "") or "").strip()
        if asset_type == "cash" or not ticker:
            continue
        identity = company_note_identity_key(row)
        if not identity:
            continue
        expected_path = company_root / safe_component(ticker) / "Company.md"
        path = expected_path
        if not path.exists():
            path = (
                note_index.get(identity)
                or note_index.get(f"TICKER:{ticker.upper()}")
                or expected_path
            )
        targets.setdefault(identity, set()).add(str(path.relative_to(vault_root)))
    return targets


def reconciliation_summary_metrics(processed_dir: Path) -> dict[str, str]:
    summary = read_csv(processed_dir / "reconciliation_summary.csv")
    if summary.empty or "metric" not in summary.columns or "value" not in summary.columns:
        return {}
    return {
        str(row.get("metric", "") or "").strip(): text_value(row.get("value", ""))
        for _, row in summary.iterrows()
        if text_value(row.get("metric", ""))
    }


def add_status_exception(rows: list[dict[str, Any]], status: str, file_name: str, idx: int) -> None:
    if status == "fx_missing":
        add(
            rows,
            "REC-EX-01",
            "blocking",
            processed_row_ref(file_name, idx),
            "FX rate missing for a non-KRW amount needed before reconciliation can be official.",
            "Review FX source or broker-provided KRW amount provenance; keep the row out of official KRW totals until resolved.",
        )
    elif status == "currency_ambiguous":
        add(
            rows,
            "REC-EX-02",
            "blocking",
            processed_row_ref(file_name, idx),
            "Currency is ambiguous; raw amount cannot be safely treated as KRW.",
            "Review source mapping and set currency_native to a 3-letter currency code before reconciliation.",
        )
    elif status == "unit_ambiguous":
        add(
            rows,
            "REC-EX-03",
            "blocking",
            processed_row_ref(file_name, idx),
            "Unit is ambiguous; numeric value may be quantity, unit price, FX rate, fee, tax, or money.",
            "Classify amount_kind, amount_basis, unit, and review status before using the row in KRW totals.",
        )


def add_status_exceptions_from_frame(rows: list[dict[str, Any]], df: pd.DataFrame, file_name: str, status_fields: tuple[str, ...]) -> None:
    if df.empty:
        return
    for idx, row in df.reset_index(drop=True).iterrows():
        status = row_status(row, *status_fields)
        add_status_exception(rows, status, file_name, idx)


def row_currency(row: pd.Series) -> str:
    for field in ["currency_native", "currency"]:
        if field in row.index:
            currency = text_value(row.get(field)).upper()
            if currency:
                return currency
    return ""


def row_has_krw_without_provenance(row: pd.Series) -> bool:
    currency = row_currency(row)
    if not currency or currency == "KRW":
        return False
    if is_blank(row.get("amount_krw", "")):
        return False
    fx_rate = row.get("fx_rate_to_krw", row.get("fx_rate", ""))
    amount_source = lower_value(row.get("amount_krw_source", ""))
    amount_basis = lower_value(row.get("amount_basis", ""))
    if not is_blank(fx_rate):
        return False
    return amount_source not in BROKER_KRW_SOURCES | FX_KRW_SOURCES and amount_basis not in BROKER_KRW_SOURCES | FX_KRW_SOURCES


def add_non_krw_provenance_exceptions(rows: list[dict[str, Any]], df: pd.DataFrame, file_name: str) -> None:
    if df.empty:
        return
    for idx, row in df.reset_index(drop=True).iterrows():
        if row_has_krw_without_provenance(row):
            add(
                rows,
                "REC-EX-08",
                "blocking",
                processed_row_ref(file_name, idx),
                "Non-KRW amount has amount_krw populated without FX rate or broker KRW provenance.",
                "Add fx_rate_to_krw or broker KRW source metadata before treating the KRW amount as official.",
            )


def is_principal_candidate(row: pd.Series) -> bool:
    role = lower_value(row.get("cashflow_role", ""))
    tx_type = lower_value(row.get("transaction_type", ""))
    return (
        role == "external_principal"
        or tx_type in {"deposit", "withdrawal"}
        or bool_value(row.get("affects_principal", ""))
        or is_principal_cashflow_row(row)
    )


def has_quantity_or_price_unit(row: pd.Series) -> bool:
    amount_kind = lower_value(row.get("amount_kind", ""))
    quantity = optional_number(row.get("quantity", row.get("raw_quantity", "")))
    price = optional_number(row.get("price", row.get("raw_price", "")))
    quantity_unit = text_value(row.get("quantity_unit", ""))
    price_unit = text_value(row.get("price_unit", ""))
    return (
        amount_kind in {"quantity", "unit_price"}
        or (quantity is not None and abs(quantity) > 1e-9)
        or (price is not None and abs(price) > 1e-9)
        or bool(quantity_unit)
        or bool(price_unit)
    )


def add_quantity_price_exceptions(rows: list[dict[str, Any]], df: pd.DataFrame, file_name: str) -> None:
    if df.empty:
        return
    for idx, row in df.reset_index(drop=True).iterrows():
        if is_principal_candidate(row) and has_quantity_or_price_unit(row):
            add(
                rows,
                "REC-EX-09",
                "blocking",
                processed_row_ref(file_name, idx),
                "Quantity or unit price appears in a principal or total amount candidate.",
                "Separate quantity/unit price from money amount fields before principal or asset reconciliation.",
            )


def add_exchange_exceptions(rows: list[dict[str, Any]], df: pd.DataFrame, file_name: str) -> None:
    if df.empty:
        return
    for idx, row in df.reset_index(drop=True).iterrows():
        role = lower_value(row.get("cashflow_role", ""))
        tx_type = lower_value(row.get("transaction_type", ""))
        if role == "internal_fx_exchange" or tx_type == "exchange" or bool_value(row.get("is_internal_transfer", "")):
            add(
                rows,
                "REC-EX-04",
                "advisory",
                processed_row_ref(file_name, idx),
                "Exchange row detected and excluded from external principal.",
                "Verify FX pairing and keep exchange activity classified as an internal transfer.",
            )


def add_income_exclusion_exceptions(rows: list[dict[str, Any]], income: pd.DataFrame, transactions: pd.DataFrame) -> None:
    income_types = {"dividend", "interest", "distribution"}
    if not income.empty:
        for idx, row in income.reset_index(drop=True).iterrows():
            if lower_value(row.get("income_type", "")) in income_types:
                add(
                    rows,
                    "REC-EX-05",
                    "advisory",
                    processed_row_ref("processed_income.csv", idx),
                    "Dividend, interest, or distribution row detected and excluded from external principal.",
                    "Verify income classification and include it only in profit breakdown after KRW conversion is reviewed.",
                )
    if not transactions.empty:
        for idx, row in transactions.reset_index(drop=True).iterrows():
            role = lower_value(row.get("cashflow_role", ""))
            tx_type = lower_value(row.get("transaction_type", ""))
            if role.startswith("income_") or tx_type in income_types:
                add(
                    rows,
                    "REC-EX-05",
                    "advisory",
                    processed_row_ref("processed_transactions.csv", idx),
                    "Dividend, interest, or distribution row detected and excluded from external principal.",
                    "Verify income classification and include it only in profit breakdown after KRW conversion is reviewed.",
                )


def add_reconciliation_summary_exceptions(rows: list[dict[str, Any]], processed_dir: Path) -> None:
    metrics = reconciliation_summary_metrics(processed_dir)
    if not metrics:
        return
    total_assets_status = lower_value(metrics.get("total_assets_status", ""))
    principal_status = lower_value(metrics.get("net_external_principal_status", ""))
    total_return_status = lower_value(metrics.get("total_return_status", ""))
    if total_return_status and total_return_status != "available":
        add(
            rows,
            "REC-EX-06",
            "blocking",
            "70_Imports/processed/reconciliation_summary.csv",
            "Reconciliation total return is unavailable because total assets or net principal is unavailable.",
            "Resolve total_assets_status and net_external_principal_status before treating total return as official.",
        )
    elif (total_assets_status and total_assets_status != "available") or (principal_status and principal_status != "available"):
        add(
            rows,
            "REC-EX-06",
            "blocking",
            "70_Imports/processed/reconciliation_summary.csv",
            "Reconciliation total return is unavailable because total assets or net principal is unavailable.",
            "Resolve total_assets_status and net_external_principal_status before treating total return as official.",
        )

    residual_status = lower_value(metrics.get("residual_status", ""))
    residual = optional_number(metrics.get("residual_krw", ""))
    if residual_status == "available" and residual is not None and abs(residual) > RESIDUAL_EXCEPTION_THRESHOLD_KRW:
        add(
            rows,
            "REC-EX-07",
            "advisory",
            "70_Imports/processed/reconciliation_summary.csv",
            "Residual exceeds configured reconciliation threshold.",
            "Review realized PnL, FX PnL, income, expenses, and principal classifications for unexplained difference.",
        )

    realized_status = lower_value(metrics.get("realized_pnl_status", ""))
    if realized_status and realized_status != "available":
        add(
            rows,
            "REC-EX-10",
            "advisory",
            "70_Imports/processed/reconciliation_summary.csv",
            "Realized PnL ledger is incomplete or unavailable.",
            "Review processed_realized_pnl.csv and imported transaction history before treating profit decomposition as complete.",
        )


def add_reconciliation_quality_exceptions(rows: list[dict[str, Any]], processed_dir: Path) -> None:
    amount_audit = read_csv(processed_dir / "amount_unit_audit.csv")
    unit_mismatch = read_csv(processed_dir / "unit_mismatch_audit.csv")
    transactions = read_csv(processed_dir / "processed_transactions.csv")
    cashflows = read_csv(processed_dir / "processed_cashflows.csv")
    income = read_csv(processed_dir / "processed_income.csv")
    expenses = read_csv(processed_dir / "processed_expenses.csv")
    fx_events = read_csv(processed_dir / "processed_fx_events.csv")

    add_status_exceptions_from_frame(rows, amount_audit, "amount_unit_audit.csv", ("amount_review_status", "fx_rate_status"))
    add_status_exceptions_from_frame(rows, unit_mismatch, "unit_mismatch_audit.csv", ("amount_normalization_status",))

    for file_name, df in [
        ("amount_unit_audit.csv", amount_audit),
        ("unit_mismatch_audit.csv", unit_mismatch),
        ("processed_transactions.csv", transactions),
        ("processed_cashflows.csv", cashflows),
        ("processed_income.csv", income),
        ("processed_expenses.csv", expenses),
        ("processed_fx_events.csv", fx_events),
    ]:
        add_non_krw_provenance_exceptions(rows, df, file_name)
        add_quantity_price_exceptions(rows, df, file_name)

    add_exchange_exceptions(rows, transactions, "processed_transactions.csv")
    add_exchange_exceptions(rows, cashflows, "processed_cashflows.csv")
    add_exchange_exceptions(rows, fx_events, "processed_fx_events.csv")
    add_income_exclusion_exceptions(rows, income, transactions)
    add_reconciliation_summary_exceptions(rows, processed_dir)


def run_qa(vault_root: Path, processed_dir: Path | None = None, dry_run: bool = False) -> pd.DataFrame:
    processed_dir = processed_dir or vault_root / "70_Imports" / "processed"
    rows: list[dict[str, Any]] = []
    active_note_targets = active_company_note_targets(vault_root, processed_dir)

    company_files = list((vault_root / "20_Companies").glob("*/Company.md"))
    for path in company_files:
        text = path.read_text(encoding="utf-8-sig")
        meta = parse_frontmatter(text)
        rel = str(path.relative_to(vault_root))
        typ = meta.get("type") or meta.get("doc_type")
        is_cash_note = is_cash_company_note(path, meta)
        note_identity = company_note_identity_key({
            "ticker": meta.get("ticker", "") or path.parent.name,
            "security_name": meta.get("name", ""),
            "market": meta.get("market", ""),
            "asset_type": meta.get("asset_type", ""),
        })
        is_stale_duplicate_note = bool(
            note_identity
            and note_identity in active_note_targets
            and rel not in active_note_targets[note_identity]
        )
        if not typ and not is_cash_note:
            add(rows, "INV-EX-01", "blocking", rel, "필수 YAML type이 없습니다.", "frontmatter에 type: company를 추가하세요.")
        if typ in {"company", "holding_stock", "holding_etf"} and not is_cash_note and not is_stale_duplicate_note:
            if not meta.get("ticker") or not meta.get("market"):
                add(rows, "INV-EX-02", "blocking", rel, "ticker 또는 market이 비어 있습니다.", "ticker와 market을 채우세요.")
            if not has_filled_section(text, ["투자 논리", "Thesis", "매수 이유"]):
                add(rows, "INV-EX-03", "advisory", rel, "thesis가 비어 있거나 placeholder 수준입니다.", "투자 논리/매수 이유를 작성하세요.")
            if not has_filled_section(text, ["매도", "비중축소", "sell criteria", "청산 조건"]):
                add(rows, "INV-EX-08", "blocking", rel, "sell criteria가 비어 있습니다.", "매도/비중축소 조건을 작성하세요.")
            if not meta.get("source_files") and "원천자료" not in text:
                add(rows, "INV-EX-07", "advisory", rel, "source link가 없습니다.", "source_files 또는 원천자료 링크를 추가하세요.")
            old = days_old(meta.get("last_review") or meta.get("last_update"))
            if old is not None and old > 30:
                add(rows, "INV-EX-06", "advisory", rel, f"last_review가 {old}일 전입니다.", "리뷰 노트를 갱신하세요.")
            if is_leveraged_etf_name(meta.get("name", ""), meta.get("ticker", "")) and "leveraged_etf_rule_link" not in meta:
                add(rows, "INV-EX-05", "blocking", rel, "레버리지 ETF 규칙 링크가 없습니다.", "leveraged_etf_rule_link를 추가하세요.")
        for block in generated_blocks(text):
            if detect_sensitive(block):
                add(rows, "INV-EX-12", "blocking", rel, "AUTO-GENERATED 블록에 민감정보 후보가 있습니다.", "generated output redaction을 확인하세요.")

    for path in (vault_root / "10_Dashboard").glob("*.md"):
        text = path.read_text(encoding="utf-8-sig")
        if path.name in {"Portfolio.md", "Exposure.md", "Cashflows.md", "Import_Review.md", "Risk_Watchlist.md", "Review_Queue.md", "QA_Exceptions.md"}:
            if AUTO_START not in text or AUTO_END not in text:
                add(rows, "INV-EX-09", "blocking", str(path.relative_to(vault_root)), "자동화 대상 파일에 AUTO-GENERATED 마커가 없습니다.", "마커를 추가하거나 수동 파일로 유지하세요.")
        for block in generated_blocks(text):
            if detect_sensitive(block):
                add(rows, "INV-EX-12", "blocking", str(path.relative_to(vault_root)), "대시보드 generated block에 민감정보 후보가 있습니다.", "redaction을 적용하세요.")

    holdings = read_csv(processed_dir / "processed_holdings.csv")
    if not holdings.empty:
        for _, r in holdings.iterrows():
            ticker = str(r.get("ticker", ""))
            asset_type = str(r.get("asset_type", "") or "").strip().lower()
            if asset_type == "cash":
                continue
            pnl = pd.to_numeric(pd.Series([r.get("pnl_pct", 0)]), errors="coerce").fillna(0).iloc[0]
            if pnl <= -10:
                add(rows, "INV-EX-04", "blocking", f"processed_holdings.csv:{ticker}", "pnl_pct <= -10이며 최근 리뷰 확인이 필요합니다.", "Risk Event 또는 Review Report를 작성하세요.")
            if is_leveraged_etf_name(r.get("security_name", ""), ticker):
                note = vault_root / "20_Companies" / ticker / "Company.md"
                if not note.exists() or "leveraged_etf_rule_link" not in note.read_text(encoding="utf-8-sig"):
                    add(rows, "INV-EX-05", "blocking", f"processed_holdings.csv:{ticker}", "레버리지 ETF 규칙 링크가 없습니다.", "Leveraged_ETF_Rules 링크를 추가하세요.")

    unclassified = read_csv(processed_dir / "unclassified_rows.csv")
    if not unclassified.empty:
        add(rows, "INV-EX-11", "blocking", "70_Imports/processed/unclassified_rows.csv", f"unclassified row {len(unclassified)}건이 있습니다.", "거래유형 분류 규칙을 보완하세요.")

    source_index = read_csv(processed_dir / "source_file_index.csv")
    indexed = set(source_index.get("source_file", pd.Series(dtype=str)).astype(str)) if not source_index.empty else set()
    raw_dir = vault_root / "70_Imports" / "raw"
    for raw in raw_dir.glob("*"):
        if raw.suffix.lower() not in {".xls", ".xlsx"}:
            continue
        if safe_source_name(raw) not in indexed:
            add(rows, "INV-EX-10", "advisory", str(raw.relative_to(vault_root)), "raw brokerage file이 source_file_index.csv에 없습니다.", "import를 다시 실행하세요.")

    add_reconciliation_quality_exceptions(rows, processed_dir)

    result = pd.DataFrame(rows, columns=["exception_id", "severity", "file", "issue", "suggested_fix"])
    if not dry_run:
        processed_dir.mkdir(parents=True, exist_ok=True)
        result.to_csv(processed_dir / "qa_exceptions.csv", index=False, encoding="utf-8-sig")
        dash = vault_root / "10_Dashboard" / "QA_Exceptions.md"
        replace_autogenerated_block(dash, qa_exception_cards(result), dry_run=False)
    return result
