import argparse
from datetime import date, datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from types import SimpleNamespace
import uuid

import pandas as pd
import pytest

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON,
    COLUMN_ALIASES,
    MULTIINDEX_COLUMN_SEPARATOR,
    OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON,
    canonical_overseas_position_key,
    dedupe_holdings,
    extract_symbol_from_parentheses,
    import_raw_dir,
    infer_asset_type,
    infer_market,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_cash_currency,
    normalize_currency_and_fx_rate,
    normalize_dataframe,
    normalize_date,
    normalize_amount_fields,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from migrate_autogenerated_markers import resolve_company_note
import main as pipeline_main
from main import LIVE_WRITE_CONFIRMATION_TOKEN, build_parser, is_live_vault_path, live_write_guard_findings
from obsidian_writer import AUTO_END, AUTO_START, bootstrap_autogenerated_block, dashboard_content, qa_exception_cards, qa_exception_rollup_summary, replace_autogenerated_block, write_company_notes
from portfolio_model import apply_expense_fx_rates, apply_holdings_snapshot_asof_register, apply_holdings_snapshot_asof_register_to_source_index, apply_income_fx_rates, build_fx_rate_requirements, build_income_summary, build_monthly_cashflow_summary, build_performance_history, build_performance_summary, build_portfolio, build_portfolio_outputs, generate_reports, has_filled_section, load_fx_rates, resolve_fx_rate
from qa_checker import QA_EXCEPTION_ROLLUP_COLUMNS, REC_EX_01_ISSUE, REC_EX_01_SUGGESTED_FIX, build_qa_exception_rollup, run_qa
from quality_gate import (
    audit_output_schema_findings,
    audit_representation_findings,
    changed_entries,
    company_note_currency_findings,
    company_note_duplicate_findings,
    duplicate_overseas_holding_findings,
    expense_contract_findings,
    fx_internal_transfer_findings,
    fx_event_contract_findings,
    income_contract_findings,
    income_expense_separation_findings,
    income_reversal_review_findings,
    income_summary_contract_findings,
    invalid_currency_findings,
    live_vault_actual_write_guard_findings,
    non_krw_amount_without_fx_findings,
    dashboard_return_label_findings,
    official_krw_total_provenance_findings,
    principal_unit_misuse_findings,
    processed_cashflows_contract_findings,
    processed_output_schema_findings,
    performance_summary_findings,
    realized_pnl_cost_basis_findings,
    realized_pnl_review_findings,
    reconciliation_summary_findings,
    scan_generated_markdown_sensitive,
    snapshot_raw_files,
    unit_classification_findings,
)


AMOUNT_UNIT_AUDIT_COLUMNS = [
    "source_file",
    "source_file_type",
    "account_type",
    "market",
    "trade_date",
    "transaction_type",
    "ticker",
    "security_name",
    "raw_quantity",
    "raw_price",
    "raw_trade_amount",
    "raw_settlement_amount",
    "raw_fee",
    "raw_tax",
    "quantity_unit",
    "price_unit",
    "currency_native",
    "money_unit_native",
    "money_unit_krw",
    "fx_rate_to_krw",
    "fx_rate_source",
    "fx_rate_status",
    "amount_kind",
    "amount_basis",
    "amount_native",
    "amount_krw",
    "amount_krw_source",
    "cashflow_role",
    "affects_principal",
    "affects_profit",
    "is_internal_transfer",
    "is_trade_settlement",
    "is_valuation_snapshot",
    "amount_confidence",
    "amount_review_status",
    "amount_review_reason",
]

UNIT_MISMATCH_AUDIT_COLUMNS = [
    "source_file",
    "source_file_type",
    "account_type",
    "market",
    "trade_date",
    "transaction_type",
    "ticker",
    "security_name",
    "quantity",
    "price",
    "raw_trade_amount",
    "raw_settlement_amount",
    "currency",
    "currency_native",
    "fx_rate_to_krw",
    "trade_amount_native",
    "trade_amount_krw",
    "settlement_amount_native",
    "settlement_amount_krw",
    "amount_normalization_status",
    "amount_normalization_reason",
    "cashflow_role",
    "affects_principal",
    "affects_profit",
    "is_internal_transfer",
]

FX_EVENT_COLUMNS = [
    "fx_event_id",
    "source_file",
    "source_file_type",
    "account_type",
    "trade_date",
    "trade_time",
    "leg",
    "from_currency",
    "to_currency",
    "currency_native",
    "amount_native",
    "amount_krw",
    "fx_rate_to_krw",
    "fx_rate_source",
    "fx_pair_status",
    "cashflow_role",
    "affects_principal",
    "affects_profit",
    "is_internal_transfer",
    "amount_review_status",
    "amount_review_reason",
    "raw_memo",
]

INCOME_OUTPUT_COLUMNS = [
    "source_file", "source_file_type", "account_type", "market", "trade_date", "trade_time",
    "ticker", "security_name", "income_type", "currency_native", "amount_native", "amount_krw",
    "amount_krw_source", "tax_native", "tax_krw", "fx_rate_to_krw", "fx_rate_source",
    "amount_kind", "amount_basis", "amount_confidence", "amount_review_status",
    "amount_review_reason", "affects_principal", "affects_profit", "raw_memo",
]

INCOME_SUMMARY_OUTPUT_COLUMNS = [
    "income_type", "currency_native", "amount_native_sum", "amount_krw_sum", "tax_native_sum",
    "tax_krw_sum", "net_income_native", "net_income_krw", "row_count", "fx_missing_row_count",
    "amount_review_needed_row_count", "fx_status_summary", "fx_source_summary", "income_status",
]

FX_RATE_REQUIREMENT_COLUMNS = [
    "event_date", "currency", "use_case", "row_count", "amount_native_sum",
    "missing_reason", "source_file_type", "status",
]

MONTHLY_CASHFLOW_SUMMARY_COLUMNS = [
    "month",
    "external_deposit_krw",
    "external_withdrawal_krw",
    "net_principal_flow_krw",
    "cumulative_principal_krw",
]

PERFORMANCE_HISTORY_COLUMNS = [
    "snapshot_month",
    "snapshot_date",
    "cumulative_principal_krw",
    "current_total_assets_krw",
    "cumulative_return_krw",
    "cumulative_return_pct",
    "performance_status",
]

PERFORMANCE_SUMMARY_METRICS = [
    "net_external_principal_krw",
    "external_deposit_krw",
    "external_withdrawal_krw",
    "current_total_assets_krw",
    "current_cash_krw",
    "current_holding_assets_krw",
    "cumulative_return_krw",
    "cumulative_return_pct",
    "realized_trade_pnl_gross_krw",
    "realized_trade_pnl_net_krw",
    "realized_gain_krw",
    "realized_loss_krw",
    "realized_loss_abs_krw",
    "unrealized_pnl_krw",
    "dividend_income_krw",
    "interest_income_krw",
    "distribution_income_krw",
    "income_total_krw",
    "fee_expense_krw",
    "tax_expense_krw",
    "explained_profit_krw",
    "reconciliation_residual_krw",
    "performance_status",
    "realized_pnl_status",
    "income_status",
    "fx_status",
    "income_fx_status",
    "income_fx_missing_row_count",
    "income_fx_source_summary",
    "fx_rate_requirement_row_count",
    "amount_review_needed_row_count",
]

EXPENSE_OUTPUT_COLUMNS = [
    "source_file", "source_file_type", "account_type", "market", "trade_date", "ticker",
    "security_name", "expense_type", "currency_native", "amount_native", "amount_krw",
    "fx_rate_to_krw", "fx_rate_source", "amount_kind", "amount_basis", "amount_confidence",
    "amount_review_status", "amount_review_reason", "affects_principal", "affects_profit",
    "raw_memo",
]

REALIZED_PNL_OUTPUT_COLUMNS = [
    "account_type", "market", "ticker", "security_name", "currency_native", "sell_date",
    "sell_import_id", "quantity_sold", "proceeds_native", "proceeds_krw", "cost_basis_native",
    "cost_basis_krw", "fee_native", "fee_krw", "tax_native", "tax_krw",
    "realized_trade_pnl_gross_native", "realized_trade_pnl_gross_krw",
    "realized_trade_pnl_net_native", "realized_trade_pnl_net_krw", "realized_result",
    "position_status", "cost_basis_method", "amount_review_status", "fx_status",
    "amount_review_reason", "source_file",
]

def assert_columns_present(df: pd.DataFrame, columns: list[str]) -> None:
    missing = [col for col in columns if col not in df.columns]
    assert not missing, f"missing expected unit/currency normalization columns: {missing}"

def is_blank_or_na(value) -> bool:
    if value is None:
        return True
    try:
        if pd.isna(value):
            return True
    except Exception:
        pass
    return str(value).strip() == ""

def read_processed_csv(processed: Path, name: str) -> pd.DataFrame:
    path = processed / name
    assert path.exists(), f"missing processed output: {name}"
    return pd.read_csv(path, dtype={"ticker": str})

def valid_reconciliation_summary_rows(**overrides: object) -> list[dict[str, str]]:
    values: dict[str, object] = {
        "reconciliation_summary_role": "audit_status_residual",
        "total_return_alias_of": "performance_summary.cumulative_return_krw",
        "total_return_pct_alias_of": "performance_summary.cumulative_return_pct",
        "explained_profit_formula": "realized_trade_pnl_gross_krw+unrealized_pnl_krw+dividend_income_krw+interest_income_krw+distribution_income_krw-fee_expense_krw-tax_expense_krw",
        "fee_tax_treatment": "gross_realized_pnl_minus_fee_tax_separate",
        "fx_pnl_treatment": "not_modeled_residual_context",
        "total_assets_krw": "120000",
        "total_assets_status": "available",
        "current_cash_krw": "5000",
        "current_holding_assets_krw": "115000",
        "external_deposit_krw": "100000",
        "external_withdrawal_krw": "0",
        "net_external_principal_krw": "100000",
        "net_external_principal_status": "available",
        "total_return_krw": "20000",
        "total_return_pct": "20",
        "total_return_status": "available",
        "unrealized_pnl_krw": "15000",
        "realized_pnl_krw": "0",
        "realized_trade_pnl_gross_krw": "0",
        "realized_trade_pnl_net_krw": "0",
        "realized_gain_krw": "0",
        "realized_loss_krw": "0",
        "realized_cost_basis_method": "fifo",
        "realized_pnl_basis": "gross_trade_pnl_krw_fee_tax_separate",
        "realized_pnl_status": "available",
        "realized_pnl_row_count": "0",
        "realized_pnl_unavailable_row_count": "0",
        "realized_closed_position_count": "0",
        "dividend_income_krw": "3000",
        "interest_income_krw": "500",
        "distribution_income_krw": "2000",
        "fee_expense_krw": "300",
        "tax_expense_krw": "200",
        "fx_pnl_status": "unavailable",
        "explained_profit_krw": "20000",
        "explained_profit_status": "available",
        "residual_krw": "0",
        "residual_status": "available",
        "fx_missing_row_count": "0",
        "currency_ambiguous_row_count": "0",
        "unit_ambiguous_row_count": "0",
        "amount_review_needed_row_count": "0",
        "fx_event_id_count": "1",
        "fx_event_leg_count": "2",
        "fx_paired_event_count": "1",
        "fx_partial_event_count": "0",
        "fx_unpaired_event_count": "0",
        "fx_needs_review_event_count": "0",
        "fx_unpaired_or_needs_review_row_count": "0",
        "fx_internal_transfer_row_count": "2",
    }
    values.update(overrides)
    return [{"metric": metric, "value": str(value)} for metric, value in values.items()]

def valid_performance_summary_rows(**overrides: object) -> list[dict[str, str]]:
    values: dict[str, object] = {
        "net_external_principal_krw": "100000",
        "external_deposit_krw": "100000",
        "external_withdrawal_krw": "0",
        "current_total_assets_krw": "120000",
        "current_cash_krw": "5000",
        "current_holding_assets_krw": "115000",
        "cumulative_return_krw": "20000",
        "cumulative_return_pct": "20",
        "realized_trade_pnl_gross_krw": "0",
        "realized_trade_pnl_net_krw": "0",
        "realized_gain_krw": "0",
        "realized_loss_krw": "0",
        "realized_loss_abs_krw": "0",
        "unrealized_pnl_krw": "15000",
        "dividend_income_krw": "3000",
        "interest_income_krw": "500",
        "distribution_income_krw": "2000",
        "income_total_krw": "5500",
        "fee_expense_krw": "300",
        "tax_expense_krw": "200",
        "explained_profit_krw": "20000",
        "reconciliation_residual_krw": "0",
        "performance_status": "available",
        "realized_pnl_status": "available",
        "income_status": "available",
        "fx_status": "available",
        "income_fx_status": "available",
        "income_fx_missing_row_count": "0",
        "income_fx_source_summary": "raw_native: 1",
        "fx_rate_requirement_row_count": "0",
        "amount_review_needed_row_count": "0",
    }
    values.update(overrides)
    return [{"metric": metric, "value": str(value)} for metric, value in values.items()]

def fx_gate_row(**overrides) -> dict[str, str]:
    row = {
        "fx_event_id": "FX-1",
        "fx_pair_status": "paired",
        "cashflow_role": "internal_fx_exchange",
        "is_internal_transfer": "True",
        "currency_native": "KRW",
        "amount_native": "100",
        "amount_review_status": "ok",
        "affects_principal": "False",
        "affects_profit": "False",
    }
    row.update(overrides)
    return row

def reconciliation_metrics(processed: Path) -> dict[str, str]:
    df = pd.read_csv(processed / "reconciliation_summary.csv", dtype=str)
    return dict(zip(df["metric"], df["value"].fillna("")))

def write_stage8_output_inputs(
    processed: Path,
    income_rows: list[dict[str, object]] | None = None,
    income_summary_rows: list[dict[str, object]] | None = None,
    expense_rows: list[dict[str, object]] | None = None,
    fx_rows: list[dict[str, object]] | None = None,
    realized_rows: list[dict[str, object]] | None = None,
) -> None:
    processed.mkdir(parents=True, exist_ok=True)
    income = pd.DataFrame(income_rows or [], columns=INCOME_OUTPUT_COLUMNS)
    income.to_csv(processed / "processed_income.csv", index=False)
    if income_summary_rows is None:
        build_income_summary(income).to_csv(processed / "income_summary.csv", index=False)
    else:
        pd.DataFrame(income_summary_rows, columns=INCOME_SUMMARY_OUTPUT_COLUMNS).to_csv(processed / "income_summary.csv", index=False)
    pd.DataFrame(columns=["metric", "value"]).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame(columns=MONTHLY_CASHFLOW_SUMMARY_COLUMNS).to_csv(processed / "monthly_cashflow_summary.csv", index=False)
    pd.DataFrame(columns=PERFORMANCE_HISTORY_COLUMNS).to_csv(processed / "performance_history.csv", index=False)
    pd.DataFrame(expense_rows or [], columns=EXPENSE_OUTPUT_COLUMNS).to_csv(processed / "processed_expenses.csv", index=False)
    pd.DataFrame(fx_rows or [], columns=FX_EVENT_COLUMNS).to_csv(processed / "processed_fx_events.csv", index=False)
    pd.DataFrame(columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)
    pd.DataFrame(realized_rows or [], columns=REALIZED_PNL_OUTPUT_COLUMNS).to_csv(processed / "processed_realized_pnl.csv", index=False)
    pd.DataFrame(columns=QA_EXCEPTION_ROLLUP_COLUMNS).to_csv(processed / "qa_exception_rollup.csv", index=False)

def synthetic_rec_ex_01_rollup_rows() -> pd.DataFrame:
    base = {
        "exception_id": "REC-EX-01",
        "severity": "blocking",
        "source_file_type": "transaction_history",
        "account_type": "comprehensive",
        "transaction_type": "buy",
        "cashflow_role": "trade_settlement",
        "amount_kind": "settlement_amount",
        "amount_basis": "raw_native",
        "currency_native": "USD",
        "issue": "FX provenance required",
        "suggested_fix": REC_EX_01_SUGGESTED_FIX,
    }
    return pd.DataFrame([
        {**base, "file": "70_Imports/processed/amount_unit_audit.csv:row2"},
        {**base, "file": "70_Imports/processed/amount_unit_audit.csv:row3"},
        {**base, "file": "70_Imports/processed/unit_mismatch_audit.csv:row2"},
        {**base, "file": "70_Imports/processed/unit_mismatch_audit.csv:row3"},
    ])
