import argparse
from datetime import date, datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import shutil
import sys
import tempfile
from types import SimpleNamespace
import uuid

import pandas as pd
import pytest

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON,
    COLUMN_ALIASES,
    MULTIINDEX_COLUMN_SEPARATOR,
    OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON,
    canonical_overseas_position_key,
    dedupe_holdings,
    extract_symbol_from_parentheses,
    import_raw_dir,
    infer_asset_type,
    infer_market,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_cash_currency,
    normalize_currency_and_fx_rate,
    normalize_dataframe,
    normalize_date,
    normalize_amount_fields,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from migrate_autogenerated_markers import resolve_company_note
import main as pipeline_main
from main import LIVE_WRITE_CONFIRMATION_TOKEN, build_parser, is_live_vault_path, live_write_guard_findings
from obsidian_writer import AUTO_END, AUTO_START, bootstrap_autogenerated_block, dashboard_content, qa_exception_cards, qa_exception_rollup_summary, replace_autogenerated_block, write_company_notes
from portfolio_model import apply_expense_fx_rates, apply_holdings_snapshot_asof_register, apply_holdings_snapshot_asof_register_to_source_index, apply_income_fx_rates, build_fx_rate_requirements, build_income_summary, build_monthly_cashflow_summary, build_performance_history, build_performance_summary, build_portfolio, build_portfolio_outputs, generate_reports, has_filled_section, load_fx_rates, resolve_fx_rate
from qa_checker import QA_EXCEPTION_ROLLUP_COLUMNS, REC_EX_01_ISSUE, REC_EX_01_SUGGESTED_FIX, build_qa_exception_rollup, run_qa
from quality_gate import (
    audit_output_schema_findings,
    audit_representation_findings,
    changed_entries,
    company_note_currency_findings,
    company_note_duplicate_findings,
    duplicate_overseas_holding_findings,
    expense_contract_findings,
    fx_internal_transfer_findings,
    fx_event_contract_findings,
    income_contract_findings,
    income_expense_separation_findings,
    income_reversal_review_findings,
    income_summary_contract_findings,
    invalid_currency_findings,
    live_vault_actual_write_guard_findings,
    non_krw_amount_without_fx_findings,
    dashboard_return_label_findings,
    official_krw_total_provenance_findings,
    principal_unit_misuse_findings,
    processed_cashflows_contract_findings,
    processed_output_schema_findings,
    performance_summary_findings,
    realized_pnl_cost_basis_findings,
    realized_pnl_review_findings,
    reconciliation_summary_findings,
    run_command,
    scan_generated_markdown_sensitive,
    snapshot_raw_files,
    unit_classification_findings,
)

from support import (
    AMOUNT_UNIT_AUDIT_COLUMNS,
    EXPENSE_OUTPUT_COLUMNS,
    FX_EVENT_COLUMNS,
    FX_RATE_REQUIREMENT_COLUMNS,
    INCOME_OUTPUT_COLUMNS,
    INCOME_SUMMARY_OUTPUT_COLUMNS,
    MONTHLY_CASHFLOW_SUMMARY_COLUMNS,
    PERFORMANCE_HISTORY_COLUMNS,
    PERFORMANCE_SUMMARY_METRICS,
    REALIZED_PNL_OUTPUT_COLUMNS,
    UNIT_MISMATCH_AUDIT_COLUMNS,
    assert_columns_present,
    fx_gate_row,
    is_blank_or_na,
    read_processed_csv,
    reconciliation_metrics,
    synthetic_rec_ex_01_rollup_rows,
    valid_performance_summary_rows,
    valid_reconciliation_summary_rows,
    write_stage8_output_inputs,
)


def test_quality_gate_live_vault_actual_write_guard_contract(tmp_path: Path):
    assert live_vault_actual_write_guard_findings(tmp_path) == []

def test_quality_gate_fake_live_contract_covers_qa_rollup_evidence_counts(tmp_path: Path):
    assert live_vault_actual_write_guard_findings(tmp_path) == []

def test_quality_gate_duplicate_overseas_uses_canonical_key():
    findings = duplicate_overseas_holding_findings([
        {"ticker": "US88160R1014", "security_name": "테슬라", "market": "US", "source_file_type": "holdings"},
        {"ticker": "테슬라 (TSLA)", "security_name": "테슬라 (TSLA)", "market": "US", "source_file_type": "overseas_balance"},
    ])
    assert findings == ["US:TSLA appears in both holdings and overseas_balance"]

def test_quality_gate_currency_helper_flags_fx_rate():
    assert invalid_currency_findings([{"ticker": "AAPL", "currency": "USD"}]) == []
    assert invalid_currency_findings([{"ticker": "AAPL", "currency": "", "currency_native": ""}]) == []
    findings = invalid_currency_findings([{"ticker": "AAPL", "currency": "1473.10"}])
    assert findings
    assert "FX rate" in findings[0]
    native_findings = invalid_currency_findings([{"ticker": "AAPL", "currency": "USD", "currency_native": "1473.10"}])
    assert native_findings
    assert "currency_native looks like FX rate" in native_findings[0]

def test_quality_gate_flags_numeric_currency_in_company_frontmatter(tmp_path: Path):
    note = tmp_path / "20_Companies" / "AAPL" / "Company.md"
    note.parent.mkdir(parents=True)
    note.write_text(
        "---\ntype: company\nticker: AAPL\nmarket: US\ncurrency: \"1473.10\"\n---\n# AAPL\n",
        encoding="utf-8",
    )

    findings = company_note_currency_findings(tmp_path)

    assert findings
    assert "currency looks like FX rate" in findings[0]

def test_quality_gate_flags_non_krw_amount_krw_without_fx_or_broker_source():
    findings = non_krw_amount_without_fx_findings([
        {"ticker": "AAPL", "currency_native": "USD", "amount_native": "412", "amount_krw": "412", "fx_rate_to_krw": "", "amount_krw_source": ""},
    ])
    assert findings
    assert "non-KRW native amount has amount_krw without FX or broker KRW source" in findings[0]
    assert non_krw_amount_without_fx_findings([
        {"ticker": "AAPL", "currency_native": "USD", "amount_native": "412", "amount_krw": "600000", "fx_rate_to_krw": "", "amount_basis": "broker_krw_amount"},
    ]) == []
    equality_findings = non_krw_amount_without_fx_findings([
        {"ticker": "AAPL", "currency_native": "USD", "amount_native": "412", "amount_krw": "412", "fx_rate_to_krw": "", "amount_krw_source": "derived_krw_from_fx"},
    ])
    assert any("USD amount_krw equals amount_native while FX rate is blank" in finding for finding in equality_findings)

def test_quality_gate_requires_stage8_output_schemas(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)

    findings = processed_output_schema_findings(processed)
    assert any("processed_income.csv is missing" in finding for finding in findings)

    write_stage8_output_inputs(processed)
    assert processed_output_schema_findings(processed) == []

    pd.DataFrame(columns=[col for col in INCOME_SUMMARY_OUTPUT_COLUMNS if col != "net_income_krw"]).to_csv(processed / "income_summary.csv", index=False)
    findings = processed_output_schema_findings(processed)
    assert any("income_summary.csv missing required columns" in finding and "net_income_krw" in finding for finding in findings)

    write_stage8_output_inputs(processed)
    pd.DataFrame(columns=["metric"]).to_csv(processed / "performance_summary.csv", index=False)
    findings = processed_output_schema_findings(processed)
    assert any("performance_summary.csv missing required columns" in finding and "value" in finding for finding in findings)

    write_stage8_output_inputs(processed)
    pd.DataFrame(columns=["income_type", "amount_native"]).to_csv(processed / "processed_income.csv", index=False)
    findings = processed_output_schema_findings(processed)
    assert any("processed_income.csv missing required columns" in finding for finding in findings)

    pd.DataFrame(columns=[col for col in REALIZED_PNL_OUTPUT_COLUMNS if col != "cost_basis_method"]).to_csv(processed / "processed_realized_pnl.csv", index=False)
    findings = processed_output_schema_findings(processed)
    assert any("processed_realized_pnl.csv missing required columns" in finding and "cost_basis_method" in finding for finding in findings)

def test_quality_gate_validates_qa_exception_rollup_schema(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_stage8_output_inputs(processed)

    assert processed_output_schema_findings(processed) == []

    pd.DataFrame(columns=[col for col in QA_EXCEPTION_ROLLUP_COLUMNS if col != "has_blocking"]).to_csv(processed / "qa_exception_rollup.csv", index=False)
    findings = processed_output_schema_findings(processed)

    assert any(
        "qa_exception_rollup.csv missing required columns" in finding and "has_blocking" in finding
        for finding in findings
    )

def test_quality_gate_validates_income_summary_contract():
    income_rows = [
        {"income_type": "dividend", "currency_native": "USD", "amount_native": "10", "amount_krw": "14000", "tax_native": "1", "tax_krw": "1400", "amount_review_status": "ok"},
        {"income_type": "dividend", "currency_native": "USD", "amount_native": "5", "amount_krw": "", "tax_native": "0.5", "tax_krw": "", "amount_review_status": "fx_missing"},
    ]
    valid_summary = build_income_summary(pd.DataFrame(income_rows)).astype(str).to_dict("records")

    assert income_summary_contract_findings(valid_summary, income_rows) == []

    inflated_krw = [{**valid_summary[0], "amount_krw_sum": "19000"}]
    findings = income_summary_contract_findings(inflated_krw, income_rows)
    assert any("amount_krw_sum expected 14000.0" in finding for finding in findings)

    available_status = [{**valid_summary[0], "income_status": "available"}]
    findings = income_summary_contract_findings(available_status, income_rows)
    assert any("income_status expected fx_missing" in finding for finding in findings)

def test_quality_gate_flags_income_reversal_rows_for_review_without_private_amounts():
    rows = [
        {
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native": "-12.34",
            "amount_krw": "-17000",
            "tax_native": "",
            "tax_krw": "",
            "amount_review_status": "ok",
            "account_type": "PRIVATE-ACCOUNT-123",
            "raw_memo": "regular dividend",
        },
        {
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native": "5",
            "amount_krw": "",
            "tax_native": "",
            "tax_krw": "",
            "amount_review_status": "fx_missing",
            "account_type": "PRIVATE-ACCOUNT-456",
            "raw_memo": "dividend reversal refund",
        },
    ]

    findings = income_reversal_review_findings(rows)
    text = "\n".join(findings)

    assert any("reversal/refund-like rows need review" in finding for finding in findings)
    assert "row_count=2" in text
    assert "income_types=dividend" in text
    assert "statuses=fx_missing,ok" in text
    assert "negative_amount" in text
    assert "reversal_keyword" in text
    assert "12.34" not in text
    assert "17000" not in text
    assert "PRIVATE-ACCOUNT" not in text
    assert "dividend reversal refund" not in text

def test_quality_gate_validates_realized_pnl_fifo_cost_basis_rows():
    valid_row = {
        "ticker": "FIFO",
        "sell_import_id": "sell-1",
        "proceeds_krw": "2500",
        "cost_basis_krw": "1000",
        "fee_krw": "100",
        "tax_krw": "50",
        "cost_basis_method": "fifo",
        "realized_trade_pnl_gross_krw": "1500",
        "realized_trade_pnl_net_krw": "1350",
        "amount_review_status": "ok",
        "fx_status": "not_required",
    }
    assert realized_pnl_cost_basis_findings([valid_row]) == []

    invalid_method_findings = realized_pnl_cost_basis_findings([{**valid_row, "cost_basis_method": "average"}])
    assert any("cost_basis_method must be fifo" in finding for finding in invalid_method_findings)

    blank_method_findings = realized_pnl_cost_basis_findings([{**valid_row, "cost_basis_method": ""}])
    assert any("cost_basis_method must be fifo" in finding for finding in blank_method_findings)

    ok_without_pnl_findings = realized_pnl_cost_basis_findings([{**valid_row, "realized_trade_pnl_gross_krw": ""}])
    assert any("status ok but blank official KRW fields" in finding for finding in ok_without_pnl_findings)

    gross_formula_findings = realized_pnl_cost_basis_findings([{**valid_row, "realized_trade_pnl_gross_krw": "1499"}])
    assert any("gross KRW formula mismatch" in finding for finding in gross_formula_findings)

    net_formula_findings = realized_pnl_cost_basis_findings([{**valid_row, "realized_trade_pnl_net_krw": "1490"}])
    assert any("net KRW formula mismatch" in finding for finding in net_formula_findings)

    lot_missing_row = {
        **valid_row,
        "cost_basis_method": "fifo",
        "cost_basis_krw": "",
        "realized_trade_pnl_gross_krw": "",
        "realized_trade_pnl_net_krw": "",
        "amount_review_status": "lot_missing",
    }
    assert realized_pnl_cost_basis_findings([lot_missing_row]) == []

    populated_lot_missing_findings = realized_pnl_cost_basis_findings([{**lot_missing_row, "realized_trade_pnl_gross_krw": "1500"}])
    assert any("lot_missing status but official KRW realized PnL is populated" in finding for finding in populated_lot_missing_findings)

    fx_missing_row = {
        **valid_row,
        "proceeds_krw": "",
        "cost_basis_krw": "",
        "realized_trade_pnl_gross_krw": "",
        "realized_trade_pnl_net_krw": "",
        "amount_review_status": "fx_missing",
        "fx_status": "fx_missing",
    }
    assert realized_pnl_cost_basis_findings([fx_missing_row]) == []

    fx_missing_populated = realized_pnl_cost_basis_findings([{**fx_missing_row, "realized_trade_pnl_gross_krw": "1500"}])
    assert any("fx_missing but official KRW realized PnL is populated" in finding for finding in fx_missing_populated)

def test_quality_gate_flags_realized_review_statuses_and_lot_missing_without_private_amounts():
    rows = [
        {
            "ticker": "SYN",
            "quantity_sold": "999",
            "amount_review_status": "fx_missing",
            "fx_status": "fx_missing",
            "amount_review_reason": "broker reference synthetic-account-token amount synthetic-cash-token",
        },
        {
            "ticker": "MISS",
            "quantity_sold": "2",
            "amount_review_status": "lot_missing",
            "fx_status": "not_required",
            "amount_review_reason": "sell quantity exceeds matched buy lots",
        },
    ]

    findings = realized_pnl_review_findings(rows)
    text = "\n".join(findings)

    assert any("requires review" in finding for finding in findings)
    assert any("sell quantity exceeds matched FIFO buy lots" in finding for finding in findings)
    assert "synthetic-cash-token" not in text
    assert "synthetic-account-token" not in text

def test_quality_gate_flags_official_krw_totals_without_fx_or_broker_provenance():
    findings = official_krw_total_provenance_findings(
        holdings=[
            {"ticker": "AAPL", "currency_native": "USD", "evaluation_amount_krw": "140000", "fx_rate_to_krw": "", "amount_basis": ""},
        ],
        realized=[
            {"ticker": "TSLA", "currency_native": "USD", "proceeds_krw": "140000", "fx_status": "fx_missing"},
        ],
    )

    assert any("processed_holdings row 2 non-KRW evaluation_amount_krw lacks FX or broker KRW provenance" in finding for finding in findings)
    assert any("processed_realized_pnl.csv row 2 non-KRW official KRW fields lack available FX/broker status" in finding for finding in findings)
    assert official_krw_total_provenance_findings(
        holdings=[
            {"ticker": "AAPL", "currency_native": "USD", "evaluation_amount_krw": "140000", "fx_rate_to_krw": "1400"},
        ],
        realized=[
            {"ticker": "TSLA", "currency_native": "USD", "proceeds_krw": "140000", "fx_status": "available"},
        ],
    ) == []

def test_quality_gate_flags_ambiguous_portfolio_dashboard_return_labels(tmp_path: Path):
    dashboard = tmp_path / "10_Dashboard"
    dashboard.mkdir(parents=True)
    (dashboard / "Portfolio.md").write_text(
        "# Portfolio\n\n"
        f"{AUTO_START}\n"
        '<span class="stock-kpi-label">Return</span>\n'
        "Portfolio Cost Basis\n"
        "Total Return %\n"
        f"{AUTO_END}\n",
        encoding="utf-8",
    )

    findings = dashboard_return_label_findings(tmp_path)

    assert findings
    assert "Return" in findings[0]
    assert "Portfolio Cost Basis" in findings[0]
    assert "Total Return %" in findings[0]

def test_quality_gate_requires_audit_output_schemas(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)

    findings = audit_output_schema_findings(processed)
    assert any("amount_unit_audit.csv is missing" in finding for finding in findings)
    assert any("unit_mismatch_audit.csv is missing" in finding for finding in findings)

    pd.DataFrame(columns=AMOUNT_UNIT_AUDIT_COLUMNS).to_csv(processed / "amount_unit_audit.csv", index=False)
    pd.DataFrame(columns=UNIT_MISMATCH_AUDIT_COLUMNS).to_csv(processed / "unit_mismatch_audit.csv", index=False)
    assert audit_output_schema_findings(processed) == []

    pd.DataFrame(columns=["source_file"]).to_csv(processed / "amount_unit_audit.csv", index=False)
    findings = audit_output_schema_findings(processed)
    assert any("amount_unit_audit.csv missing required columns" in finding for finding in findings)

def test_quality_gate_requires_unit_classification_for_official_amounts():
    valid_principal = {
        "transaction_type": "deposit",
        "cashflow_role": "external_principal",
        "affects_principal": "True",
        "amount_kind": "cash_amount",
        "amount_basis": "settlement_amount_krw",
        "currency_native": "KRW",
        "amount_review_status": "ok",
        "amount_krw": "1000",
    }
    assert unit_classification_findings([valid_principal]) == []

    findings = unit_classification_findings([{**valid_principal, "amount_kind": ""}])
    assert any("lacks explicit unit/currency classification" in finding and "amount_kind" in finding for finding in findings)

    findings = unit_classification_findings([{**valid_principal, "amount_kind": "fx_rate", "amount_krw": "1473.10"}])
    assert any("FX rate is present in money amount fields" in finding for finding in findings)

def test_quality_gate_requires_performance_summary_metrics_and_formulas():
    assert performance_summary_findings(valid_performance_summary_rows()) == []

    findings = performance_summary_findings([
        row for row in valid_performance_summary_rows() if row["metric"] != "cumulative_return_krw"
    ])
    assert any("missing required metrics" in finding and "cumulative_return_krw" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(net_external_principal_krw="90000"))
    assert any("net_external_principal_krw formula mismatch" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(cumulative_return_krw="21000"))
    assert any("cumulative_return_krw formula mismatch" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(income_total_krw="5400"))
    assert any("income_total_krw formula mismatch" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(explained_profit_krw="19000"))
    assert any("explained_profit_krw formula mismatch" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(
        realized_trade_pnl_gross_krw="2000",
        realized_trade_pnl_net_krw="1820",
        unrealized_pnl_krw="0",
        dividend_income_krw="0",
        interest_income_krw="0",
        distribution_income_krw="0",
        income_total_krw="0",
        fee_expense_krw="120",
        tax_expense_krw="60",
        explained_profit_krw="1640",
        reconciliation_residual_krw="18360",
    ))
    assert any("double-count fee/tax" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(
        current_total_assets_krw="",
        cumulative_return_krw="20000",
        cumulative_return_pct="20",
        performance_status="fx_missing",
    ))
    assert any("cumulative return is populated despite unavailable assets or principal" in finding for finding in findings)

    findings = performance_summary_findings(valid_performance_summary_rows(
        performance_status="available",
        income_status="fx_missing",
    ))
    assert any("performance_status is available despite unresolved inputs" in finding for finding in findings)

    findings = performance_summary_findings(
        valid_performance_summary_rows(
            current_total_assets_krw="120000",
            current_cash_krw="5000",
            current_holding_assets_krw="115000",
            unrealized_pnl_krw="15000",
            performance_status="fx_missing",
            fx_status="fx_missing",
        ),
        valid_reconciliation_summary_rows(
            total_assets_krw="",
            current_cash_krw="",
            current_holding_assets_krw="",
            total_assets_status="fx_missing",
            unrealized_pnl_krw="15000",
        ),
    )
    assert any("current_total_assets_krw must be blank" in finding for finding in findings)
    assert any("current_holding_assets_krw must be blank" in finding for finding in findings)
    assert any("unrealized_pnl_krw must be blank" in finding for finding in findings)

def test_quality_gate_requires_reconciliation_summary_metrics():
    assert reconciliation_summary_findings(valid_reconciliation_summary_rows()) == []

    findings = reconciliation_summary_findings([
        row for row in valid_reconciliation_summary_rows() if row["metric"] != "distribution_income_krw"
    ])
    assert any("missing required metrics" in finding and "distribution_income_krw" in finding for finding in findings)

    findings = reconciliation_summary_findings([
        row for row in valid_reconciliation_summary_rows() if row["metric"] != "realized_cost_basis_method"
    ])
    assert any("missing required metrics" in finding and "realized_cost_basis_method" in finding for finding in findings)

    for invalid_method in ["", "average", "avg", "moving_average", "unknown"]:
        findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(realized_cost_basis_method=invalid_method))
        assert any("realized_cost_basis_method must be fifo" in finding for finding in findings)

    findings = reconciliation_summary_findings([
        row for row in valid_reconciliation_summary_rows() if row["metric"] != "realized_pnl_basis"
    ])
    assert any("missing required metrics" in finding and "realized_pnl_basis" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(realized_pnl_basis="net_trade_pnl_krw"))
    assert any("realized_pnl_basis must be gross_trade_pnl_krw_fee_tax_separate" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(reconciliation_summary_role="performance_summary"))
    assert any("reconciliation_summary_role must be audit_status_residual" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(total_return_alias_of="standalone_total_return"))
    assert any("total_return_alias_of must be performance_summary.cumulative_return_krw" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(fee_tax_treatment="net_realized_pnl_includes_fee_tax"))
    assert any("fee_tax_treatment must be gross_realized_pnl_minus_fee_tax_separate" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(realized_pnl_krw="10", realized_trade_pnl_gross_krw="0"))
    assert any("realized_pnl_krw must equal realized_trade_pnl_gross_krw" in finding for finding in findings)

    assert reconciliation_summary_findings(valid_reconciliation_summary_rows(realized_pnl_status="available")) == []

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(realized_pnl_status="fx_missing", explained_profit_status="available"))
    assert any("explained_profit_status is available but realized_pnl_status is not available" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(fx_pnl_status="available"))
    assert any("fx_pnl_status must remain unavailable" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(total_return_krw="21000"))
    assert any("total_return_krw formula mismatch" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(
        realized_trade_pnl_gross_krw="2000",
        realized_trade_pnl_net_krw="1820",
        unrealized_pnl_krw="0",
        dividend_income_krw="0",
        interest_income_krw="0",
        distribution_income_krw="0",
        fee_expense_krw="120",
        tax_expense_krw="60",
        explained_profit_krw="1640",
    ))
    assert any("explained_profit_krw formula mismatch" in finding for finding in findings)

def test_quality_gate_reconciliation_status_consistency():
    assert reconciliation_summary_findings(valid_reconciliation_summary_rows()) == []

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(total_assets_status="fx_missing"))
    assert any("total_return_status is available but total_assets_status is not available" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(net_external_principal_status="fx_missing"))
    assert any("total_return_status is available but net_external_principal_status is not available" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(total_return_status="fx_missing", residual_status="available"))
    assert any("residual_status must not be available when total_return_status is not available" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(
        realized_pnl_status="lot_missing",
        explained_profit_status="lot_missing",
        explained_profit_krw="15000",
        residual_status="unavailable",
    ))
    assert any("explained_profit_krw must be blank when explained_profit_status is not available" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(fx_missing_row_count="1"))
    assert any("total_return_status is available despite unresolved official-total rows" in finding for finding in findings)
    assert any("explained_profit_status is available despite unresolved profit rows" in finding for finding in findings)

    findings = reconciliation_summary_findings(valid_reconciliation_summary_rows(total_assets_krw=""))
    assert any("total_assets_status is available but total_assets_krw is blank" in finding for finding in findings)

def test_quality_gate_income_expense_fx_contracts():
    valid_income = [{
        "income_type": "dividend",
        "currency_native": "USD",
        "amount_native": "12.34",
        "amount_krw": "",
        "amount_review_status": "fx_missing",
        "affects_principal": "False",
        "affects_profit": "True",
    }]
    valid_expense = [{
        "expense_type": "fee",
        "currency_native": "KRW",
        "amount_native": "100",
        "amount_krw": "100",
        "amount_review_status": "ok",
        "affects_principal": "False",
        "affects_profit": "True",
    }]
    valid_fx = [
        fx_gate_row(currency_native="KRW"),
        fx_gate_row(currency_native="USD"),
    ]

    assert income_contract_findings(valid_income) == []
    assert expense_contract_findings(valid_expense) == []
    assert fx_event_contract_findings(valid_fx) == []

    assert any("affects principal" in finding for finding in income_contract_findings([{**valid_income[0], "affects_principal": "True"}]))
    assert any("affects principal" in finding for finding in expense_contract_findings([{**valid_expense[0], "affects_principal": "True"}]))
    assert any("not marked as an internal FX transfer" in finding for finding in fx_event_contract_findings([{**valid_fx[0], "cashflow_role": "", "is_internal_transfer": "False"}]))

def test_quality_gate_valid_paired_krw_usd_fx_event_passes():
    rows = [
        fx_gate_row(currency_native="KRW"),
        fx_gate_row(currency_native="USD"),
    ]

    assert fx_event_contract_findings(rows) == []

def test_quality_gate_paired_fx_event_with_one_leg_fails():
    findings = fx_event_contract_findings([fx_gate_row(currency_native="USD")])

    assert any("has 1 rows; expected exactly 2 rows" in finding for finding in findings)

def test_quality_gate_paired_fx_event_with_two_krw_legs_fails():
    findings = fx_event_contract_findings([
        fx_gate_row(currency_native="KRW"),
        fx_gate_row(currency_native="KRW"),
    ])

    assert any("must have one KRW leg and one non-KRW leg" in finding for finding in findings)

def test_quality_gate_paired_fx_event_with_three_rows_fails():
    findings = fx_event_contract_findings([
        fx_gate_row(currency_native="KRW"),
        fx_gate_row(currency_native="USD"),
        fx_gate_row(currency_native="USD"),
    ])

    assert any("has 3 rows; expected exactly 2 rows" in finding for finding in findings)

def test_quality_gate_valid_partial_fx_event_passes():
    rows = [
        fx_gate_row(
            fx_event_id="FX-2",
            fx_pair_status="partial",
            currency_native="KRW",
            amount_review_reason="only one FX leg detected",
        )
    ]

    assert fx_event_contract_findings(rows) == []

def test_quality_gate_flags_quantity_or_price_in_principal_totals():
    findings = principal_unit_misuse_findings([
        {"transaction_type": "deposit", "cashflow_role": "external_principal", "affects_principal": "True", "amount_kind": "quantity", "quantity": "8", "price": "0"},
        {"transaction_type": "withdrawal", "cashflow_role": "external_principal", "affects_principal": "True", "amount_kind": "unit_price", "quantity": "0", "price": "51.5"},
    ])
    assert len(findings) == 2
    assert all("principal row uses quantity/unit_price" in finding for finding in findings)

def valid_gate_cashflow_row(**overrides):
    row = {
        "transaction_type": "deposit",
        "trade_date": "2026-01-01",
        "ticker": "",
        "security_name": "",
        "quantity": "0",
        "price": "0",
        "cashflow_role": "external_principal",
        "affects_principal": "True",
        "amount_review_status": "ok",
        "settlement_amount_krw": "1000",
        "amount_krw": "1000",
    }
    row.update(overrides)
    return row

def test_quality_gate_cashflows_are_role_aware_external_principal_only():
    assert processed_cashflows_contract_findings([valid_gate_cashflow_row()]) == []

    findings = processed_cashflows_contract_findings([valid_gate_cashflow_row(transaction_type="dividend")])
    assert any("contains non-principal transaction_type=dividend" in finding for finding in findings)

    findings = processed_cashflows_contract_findings([valid_gate_cashflow_row(cashflow_role="income_dividend")])
    assert any("cashflow_role is not external_principal" in finding for finding in findings)

    findings = processed_cashflows_contract_findings([valid_gate_cashflow_row(settlement_amount_krw="", amount_krw="")])
    assert any("has no KRW-normalized official amount field" in finding for finding in findings)

def test_quality_gate_fx_exchange_and_income_expense_stay_out_of_cashflows():
    exchange_tx = {"transaction_type": "exchange", "cashflow_role": "internal_fx_exchange"}
    findings = fx_internal_transfer_findings([], [exchange_tx], [], None)
    assert any("processed_fx_events.csv has no FX event rows" in finding for finding in findings)

    findings = fx_internal_transfer_findings([exchange_tx], [], [{"fx_event_id": "FX-1"}], None)
    assert any("processed_cashflows" in finding for finding in findings)

    separation = income_expense_separation_findings(
        [{"transaction_type": "interest", "cashflow_role": "income_interest"}],
        [{"income_type": "dividend", "affects_principal": "True"}],
        [{"expense_type": "fee", "affects_principal": "True"}],
    )
    assert any("contains income" in finding for finding in separation)
    assert any("processed_income row 2 affects principal" in finding for finding in separation)
    assert any("processed_expenses row 2 affects principal" in finding for finding in separation)

def test_quality_gate_audit_outputs_represent_risky_row_types():
    source_rows = [
        {
            "currency_native": "USD",
            "cashflow_role": "income_dividend",
            "transaction_type": "dividend",
            "amount_review_status": "fx_missing",
        }
    ]

    findings = audit_representation_findings(source_rows, [], [])
    assert any("non-KRW rows are not represented" in finding for finding in findings)
    assert any("income rows are not represented" in finding for finding in findings)
    assert any("ambiguous or unresolved rows are not represented" in finding for finding in findings)

    audit_row = {
        "currency_native": "USD",
        "cashflow_role": "income_dividend",
        "transaction_type": "dividend",
        "amount_review_status": "fx_missing",
    }
    assert audit_representation_findings(source_rows, [audit_row], []) == []

def test_quality_gate_flags_semantic_company_note_duplicates(tmp_path: Path):
    vault = tmp_path
    for folder, ticker, name in [
        ("US88160R1014", "US88160R1014", "테슬라"),
        ("테슬라_TSLA", "테슬라 (TSLA)", "테슬라 (TSLA)"),
    ]:
        path = vault / "20_Companies" / folder
        path.mkdir(parents=True)
        (path / "Company.md").write_text(
            f"---\ntype: company\nticker: {ticker}\nname: {name}\nmarket: US\nasset_type: stock\n---\n# {name}\n",
            encoding="utf-8",
        )

    findings = company_note_duplicate_findings(vault)
    assert findings
    assert "US:TSLA" in findings[0]

def test_quality_gate_ignores_stale_company_note_duplicate_when_current_target_exists(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {
            "ticker": "Aehr Test Systems (AEHR)",
            "security_name": "Aehr Test Systems (AEHR)",
            "account_type": "overseas",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "source_file_type": "overseas_balance",
        }
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    for folder, ticker in [
        ("US00760J1088", "US00760J1088"),
        ("Aehr_Test_Systems_AEHR", "Aehr Test Systems (AEHR)"),
    ]:
        path = vault / "20_Companies" / folder
        path.mkdir(parents=True)
        (path / "Company.md").write_text(
            f"---\ntype: company\nticker: \"{ticker}\"\nname: \"Aehr Test Systems\"\nmarket: US\nasset_type: stock\n---\n# A\n",
            encoding="utf-8",
        )

    assert company_note_duplicate_findings(vault) == []

def test_generated_markdown_sensitive_scan_detects_candidate(tmp_path: Path):
    dash = tmp_path / "10_Dashboard"
    dash.mkdir(parents=True)
    (dash / "Portfolio.md").write_text(
        "# Portfolio\n\n<!-- AUTO-GENERATED:START -->\nphone: 010-1234-5678\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )
    assert scan_generated_markdown_sensitive(tmp_path) == ["10_Dashboard\\Portfolio.md"] or scan_generated_markdown_sensitive(tmp_path) == ["10_Dashboard/Portfolio.md"]

def test_quickadd_report_schema_v2_uses_current_cli_markers():
    node = shutil.which("node") or shutil.which("node.exe")
    if node is None:
        pytest.skip("Node.js is required to execute the QuickAdd contract test")

    script_path = Path(__file__).resolve().parents[3] / "00_Config" / "QuickAdd" / "Stock_Command_Center.js"
    harness = r"""
const Module = require('module');
const originalLoad = Module._load;
Module._load = function(request, parent, isMain) {
  if (request === 'obsidian') {
    return { Notice: class Notice {}, normalizePath: value => value };
  }
  return originalLoad.call(this, request, parent, isMain);
};

const command = require(process.argv[1]);
const helpers = command.__test;
if (!helpers) throw new Error('QuickAdd test helpers are not exported');

function makeApp() {
  const writes = new Map();
  return {
    writes,
    app: {
      vault: {
        getAbstractFileByPath: () => null,
        createFolder: async () => {},
        create: async (filePath, content) => {
          writes.set(filePath, content);
          return { path: filePath };
        },
      },
    },
  };
}

(async () => {
  const stdout = [
    '[import] raw_files=4, parsed_rows=23, duplicate_removed=5, unclassified=2',
    '[qa] exceptions=7',
    '[done] no automated buy/sell orders were executed.',
  ].join('\n');
  const parsed = helpers.parseCounts(stdout);
  const partial = helpers.parseCounts('[qa] exceptions=3\n[done] complete');
  const successCapture = makeApp();
  const success = await helpers.createImportReport(successCapture.app, {
    mode: 'dry_run',
    start: new Date('2026-08-18T00:00:00Z'),
    end: new Date('2026-08-18T00:00:02Z'),
    result: { code: 0, stdout, stderr: '' },
  });
  const successContent = successCapture.writes.get(success.filePath);
  const noDone = await helpers.createImportReport(makeApp().app, {
    mode: 'dry_run',
    start: new Date('2026-08-18T00:00:00Z'),
    end: new Date('2026-08-18T00:00:01Z'),
    result: { code: 0, stdout: '[qa] exceptions=0', stderr: '' },
  });
  const badExit = await helpers.createImportReport(makeApp().app, {
    mode: 'dry_run',
    start: new Date('2026-08-18T00:00:00Z'),
    end: new Date('2026-08-18T00:00:01Z'),
    result: { code: 9, stdout: '[done] complete', stderr: '' },
  });
  process.stdout.write(JSON.stringify({
    parsed,
    partial,
    success: success.ok,
    reportChecks: {
      schemaVersion: successContent.includes('schema_version: 2'),
      successStatus: successContent.includes('status: "success"'),
      rawFiles: successContent.includes('raw_file_count: 4'),
      parsedRows: successContent.includes('parsed_row_count: 23'),
      duplicateRows: successContent.includes('duplicate_rows_removed_count: 5'),
      unclassifiedRows: successContent.includes('unclassified_row_count: 2'),
      qaExceptions: successContent.includes('qa_exception_count: 7'),
      legacyOmitted: ![
        'new_ledger_rows',
        'trade_notes_created',
        'cash_notes_created',
        'review_notes_created',
      ].some(field => successContent.includes(field)),
    },
    noDone: noDone.ok,
    badExit: badExit.ok,
  }));
})().catch(error => {
  console.error(error);
  process.exitCode = 1;
});
"""
    code, output = run_command([node, "-e", harness, str(script_path)], script_path.parent)

    assert code == 0, output
    observed = json.loads(output)
    assert observed["parsed"] == {
        "rawFileCount": 4,
        "parsedRowCount": 23,
        "duplicateRowsRemovedCount": 5,
        "unclassifiedRowCount": 2,
        "qaExceptionCount": 7,
        "doneMarkerPresent": True,
    }
    assert observed["partial"] == {
        "rawFileCount": None,
        "parsedRowCount": None,
        "duplicateRowsRemovedCount": None,
        "unclassifiedRowCount": None,
        "qaExceptionCount": 3,
        "doneMarkerPresent": True,
    }
    assert observed["success"] is True
    assert observed["noDone"] is False
    assert observed["badExit"] is False

    assert all(observed["reportChecks"].values())

def test_run_command_preserves_environment_and_prevents_python_cache_artifacts(tmp_path: Path, monkeypatch):
    synthetic_repo = tmp_path / "synthetic_repo"
    synthetic_repo.mkdir()
    (synthetic_repo / "synthetic_cache_module.py").write_text("VALUE = 7\n", encoding="utf-8")
    (synthetic_repo / "test_synthetic_cache.py").write_text(
        "import synthetic_cache_module\n\n"
        "def test_value():\n"
        "    assert synthetic_cache_module.VALUE == 7\n",
        encoding="utf-8",
    )
    monkeypatch.setenv("STOCK_QUALITY_GATE_ENV_SENTINEL", "preserved")

    code, output = run_command(
        [
            sys.executable,
            "-c",
            "import os, synthetic_cache_module; "
            "print(os.environ.get('STOCK_QUALITY_GATE_ENV_SENTINEL')); "
            "print(synthetic_cache_module.VALUE)",
        ],
        synthetic_repo,
    )

    assert code == 0
    assert output.splitlines() == ["preserved", "7"]

    code, output = run_command(
        [
            sys.executable,
            "-m",
            "pytest",
            "-p",
            "no:cacheprovider",
            "--basetemp",
            str(tmp_path / "pytest_subprocess"),
            "test_synthetic_cache.py",
        ],
        synthetic_repo,
    )

    assert code == 0, output
    cache_artifacts = [
        path
        for path in synthetic_repo.rglob("*")
        if path.name in {"__pycache__", ".pytest_cache"} or path.suffix == ".pyc"
    ]
    assert cache_artifacts == []
