import argparse
from datetime import date, datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from types import SimpleNamespace
import uuid

import pandas as pd
import pytest

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON,
    COLUMN_ALIASES,
    MULTIINDEX_COLUMN_SEPARATOR,
    OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON,
    canonical_overseas_position_key,
    dedupe_holdings,
    extract_symbol_from_parentheses,
    import_raw_dir,
    infer_asset_type,
    infer_market,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_cash_currency,
    normalize_currency_and_fx_rate,
    normalize_dataframe,
    normalize_date,
    normalize_amount_fields,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from migrate_autogenerated_markers import resolve_company_note
import main as pipeline_main
from main import LIVE_WRITE_CONFIRMATION_TOKEN, build_parser, is_live_vault_path, live_write_guard_findings
from obsidian_writer import AUTO_END, AUTO_START, bootstrap_autogenerated_block, dashboard_content, qa_exception_cards, qa_exception_rollup_summary, replace_autogenerated_block, write_company_notes
from portfolio_model import apply_expense_fx_rates, apply_holdings_snapshot_asof_register, apply_holdings_snapshot_asof_register_to_source_index, apply_income_fx_rates, build_fx_rate_requirements, build_income_summary, build_monthly_cashflow_summary, build_performance_history, build_performance_summary, build_portfolio, build_portfolio_outputs, generate_reports, has_filled_section, load_fx_rates, resolve_fx_rate
from qa_checker import QA_EXCEPTION_ROLLUP_COLUMNS, REC_EX_01_ISSUE, REC_EX_01_SUGGESTED_FIX, build_qa_exception_rollup, run_qa
from quality_gate import (
    audit_output_schema_findings,
    audit_representation_findings,
    changed_entries,
    company_note_currency_findings,
    company_note_duplicate_findings,
    duplicate_overseas_holding_findings,
    expense_contract_findings,
    fx_internal_transfer_findings,
    fx_event_contract_findings,
    income_contract_findings,
    income_expense_separation_findings,
    income_reversal_review_findings,
    income_summary_contract_findings,
    invalid_currency_findings,
    live_vault_actual_write_guard_findings,
    non_krw_amount_without_fx_findings,
    dashboard_return_label_findings,
    official_krw_total_provenance_findings,
    principal_unit_misuse_findings,
    processed_cashflows_contract_findings,
    processed_output_schema_findings,
    performance_summary_findings,
    realized_pnl_cost_basis_findings,
    realized_pnl_review_findings,
    reconciliation_summary_findings,
    scan_generated_markdown_sensitive,
    snapshot_raw_files,
    unit_classification_findings,
)

from support import (
    AMOUNT_UNIT_AUDIT_COLUMNS,
    EXPENSE_OUTPUT_COLUMNS,
    FX_EVENT_COLUMNS,
    FX_RATE_REQUIREMENT_COLUMNS,
    INCOME_OUTPUT_COLUMNS,
    INCOME_SUMMARY_OUTPUT_COLUMNS,
    MONTHLY_CASHFLOW_SUMMARY_COLUMNS,
    PERFORMANCE_HISTORY_COLUMNS,
    PERFORMANCE_SUMMARY_METRICS,
    REALIZED_PNL_OUTPUT_COLUMNS,
    UNIT_MISMATCH_AUDIT_COLUMNS,
    assert_columns_present,
    fx_gate_row,
    is_blank_or_na,
    read_processed_csv,
    reconciliation_metrics,
    synthetic_rec_ex_01_rollup_rows,
    valid_performance_summary_rows,
    valid_reconciliation_summary_rows,
    write_stage8_output_inputs,
)


def test_parse_korean_numeric_strings():
    assert parse_korean_number("1,234,567") == 1234567
    assert parse_korean_number("(1,200)") == -1200
    assert parse_korean_number("▲1,200원") == -1200

def test_parse_korean_percentage_strings():
    assert parse_korean_percent("-10.25%") == -10.25
    assert parse_korean_percent("12.3 %") == 12.3

def test_normalize_date_columns():
    assert normalize_date("2026.04.29") == "2026-04-29"
    assert normalize_date("20260429") == "2026-04-29"

def test_classify_transaction_types():
    assert classify_transaction_type("주식 매수") == "buy"
    assert classify_transaction_type("현금배당") == "dividend"
    assert classify_transaction_type("입금 외화배당금입금") == "dividend"
    assert classify_transaction_type("입금 ETF분배금입금") == "distribution"
    assert classify_transaction_type("입금 예탁금이용료") == "interest"
    assert classify_transaction_type("입금 배당소득세") == "tax"
    assert classify_transaction_type("알수없음") == "unknown"

def test_detect_leveraged_etf_names():
    assert is_leveraged_etf_name("Direxion Daily Semiconductor Bull 3X")
    assert is_leveraged_etf_name("KODEX 2차전지산업레버리지")
    for name in [
        "KODEX 미국나스닥100 2배",
        "TIGER 미국테크TOP10 3배",
        "KODEX 인버스 -2배",
        "디렉시온 Daily Semiconductor Bull",
        "티렉스 2X Long NVIDIA",
        "그래닛셰어즈 3x Long Tesla",
        "디파이언스 Daily Target 2X",
    ]:
        assert is_leveraged_etf_name(name)
    assert not is_leveraged_etf_name("Apple Inc")

def test_extract_symbol_from_parentheses():
    cases = {
        "테슬라 (TSLA)": "TSLA",
        "엔비디아 (NVDA)": "NVDA",
        "TRADR 앱러빈 2배 ETF (APPX)": "APPX",
        "그래닛셰어즈 엔비디아 데일리 2배 ETF (NVDL)": "NVDL",
        "알파벳 Class A (GOOGL)": "GOOGL",
        "text without parentheses": "",
    }
    for text, expected in cases.items():
        assert extract_symbol_from_parentheses(text) == expected

def test_canonical_overseas_position_key_symbol():
    row = {
        "ticker": "테슬라 (TSLA)",
        "security_name": "테슬라 (TSLA)",
        "market": "US",
        "source_file_type": "overseas_balance",
    }
    assert canonical_overseas_position_key(row) == "US:TSLA"

def test_canonical_overseas_position_key_isin_alias_fallback():
    row = {
        "ticker": "US88160R1014",
        "security_name": "테슬라",
        "market": "US",
        "source_file_type": "holdings",
    }
    assert canonical_overseas_position_key(row) == "US:TSLA"

def test_currency_fx_rate_split_from_overseas_balance(tmp_path: Path):
    currency, fx_rate = normalize_currency_and_fx_rate("1473.10", "", "overseas_balance")
    assert currency == "USD"
    assert fx_rate == 1473.10

    df = pd.DataFrame([
        {"종목명": "Apple", "종목코드": "AAPL", "보유수량": "1", "외화평가금액": "100", "통화": "1473.10"},
    ])
    normalized, _, _ = normalize_dataframe(df, tmp_path / "해외증권잔고조회.xlsx", "Sheet1")
    assert normalized["source_file_type"].iloc[0] == "overseas_balance"
    assert normalized["currency"].iloc[0] == "USD"
    assert normalized["fx_rate"].iloc[0] == 1473.10

def test_overseas_balance_broker_krw_evaluation_is_not_reconverted():
    fields = normalize_amount_fields({
        "source_file_type": "overseas_balance",
        "market": "US",
        "asset_type": "stock",
        "transaction_type": "unknown",
        "currency": "USD",
        "fx_rate": 1450.8,
        "quantity": 73,
        "price": 107.87,
        "evaluation_amount": 11424339,
        "unrealized_pnl": 2374340,
    })

    assert fields["amount_basis"] == "broker_provided_krw"
    assert fields["amount_krw_source"] == "broker_provided_krw"
    assert fields["evaluation_amount_krw"] == 11424339
    assert fields["unrealized_pnl_krw"] == 2374340
    assert fields["evaluation_amount_krw"] != round(11424339 * 1450.8, 6)
    assert fields["evaluation_amount_native"] == pytest.approx(7874.51, abs=0.01)

    cash_fields = normalize_amount_fields({
        "source_file_type": "holdings",
        "market": "US",
        "asset_type": "cash",
        "transaction_type": "unknown",
        "currency": "USD",
        "quantity": 38.5,
        "price": 1450.0,
        "evaluation_amount": 55825.0,
    })

    assert cash_fields["amount_review_status"] == "ok"
    assert cash_fields["fx_rate_to_krw"] == 1450.0
    assert cash_fields["amount_basis"] == "broker_provided_krw"
    assert cash_fields["evaluation_amount_krw"] == 55825.0

def test_transaction_history_paired_quantity_price_column_maps_quantity(tmp_path: Path):
    columns = pd.MultiIndex.from_tuples([
        ("거래일자", ""),
        ("거래유형", ""),
        ("종목명", ""),
        ("수량", "단가"),
        ("거래금액", "정산금액"),
    ])
    df = pd.DataFrame([
        ["2026-01-02", "매수", "Synthetic Position (SYN)", "7", "140000"],
        ["2026-01-03", "매도", "Synthetic Position (SYN)", "3", "75000"],
    ], columns=columns)

    normalized, _, _ = normalize_dataframe(df, tmp_path / "transaction_history.xlsx", "Sheet1")
    trades = normalized[normalized["transaction_type"].isin(["buy", "sell"])].reset_index(drop=True)

    assert list(trades["quantity"]) == [7.0, 3.0]
    assert list(trades["price"]) == [0.0, 0.0]

def test_us_transaction_history_missing_currency_defaults_to_usd(tmp_path: Path):
    df = pd.DataFrame([
        {
            COLUMN_ALIASES["trade_date"][0]: "2026-04-29",
            COLUMN_ALIASES["transaction_raw"][0]: "buy",
            COLUMN_ALIASES["ticker"][0]: "AAPL",
            COLUMN_ALIASES["security_name"][0]: "Apple",
            COLUMN_ALIASES["settlement_amount"][0]: "12.34",
        },
    ])
    normalized, _, _ = normalize_dataframe(df, tmp_path / "transaction_history.xlsx", "table_0")

    assert normalized["source_file_type"].iloc[0] == "transaction_history"
    assert normalized["market"].iloc[0] == "US"
    assert normalized["currency"].iloc[0] == "USD"
    assert infer_market("", "Apple (AAPL)") == "US"
    assert infer_market("KYG254571055", "") == "US"

def test_us_holding_missing_currency_stays_krw_by_default(tmp_path: Path):
    df = pd.DataFrame([
        {
            COLUMN_ALIASES["ticker"][0]: "AAPL",
            COLUMN_ALIASES["security_name"][0]: "Apple",
            COLUMN_ALIASES["balance_quantity"][0]: "1",
            COLUMN_ALIASES["evaluation_amount"][0]: "100",
        },
    ])
    normalized, _, _ = normalize_dataframe(df, tmp_path / "holdings.xlsx", "Sheet1")

    assert normalized["source_file_type"].iloc[0] == "holdings"
    assert normalized["market"].iloc[0] == "US"
    assert normalized["currency"].iloc[0] == "KRW"

def test_domestic_sol_ai_semiconductor_top2_is_etf_with_kr_market(tmp_path: Path):
    df = pd.DataFrame([
        {
            COLUMN_ALIASES["ticker"][0]: "0167A0",
            COLUMN_ALIASES["security_name"][0]: "SOL AI반도체TOP2플러스",
            COLUMN_ALIASES["balance_quantity"][0]: "1",
            COLUMN_ALIASES["evaluation_amount"][0]: "10000",
        },
    ])

    normalized, _, _ = normalize_dataframe(df, tmp_path / "holdings.xlsx", "Sheet1")

    assert infer_market("0167A0", "SOL AI반도체TOP2플러스") == "KR"
    assert infer_asset_type("SOL AI반도체TOP2플러스", "0167A0") == "etf"
    assert normalized["market"].iloc[0] == "KR"
    assert normalized["asset_type"].iloc[0] == "etf"
    assert normalized["currency"].iloc[0] == "KRW"

def boolish(value) -> bool:
    if isinstance(value, bool):
        return value
    return str(value).strip().lower() in {"true", "1", "yes", "y"}

def synthetic_transaction_row(
    *,
    trade_date: str = "2026-01-10",
    transaction_raw: str = "buy",
    ticker: str = "AAPL",
    security_name: str = "Apple",
    quantity: str | int | float = 8,
    price: str | int | float = 51.5,
    trade_amount: str | int | float = 412,
    settlement_amount: str | int | float | None = None,
    fee: str | int | float | None = None,
    tax: str | int | float | None = None,
    currency: str | None = None,
    fx_rate: str | int | float | None = None,
) -> dict[str, object]:
    row: dict[str, object] = {
        COLUMN_ALIASES["trade_date"][0]: trade_date,
        COLUMN_ALIASES["transaction_raw"][0]: transaction_raw,
        COLUMN_ALIASES["ticker"][0]: ticker,
        COLUMN_ALIASES["security_name"][0]: security_name,
        COLUMN_ALIASES["quantity"][0]: quantity,
        COLUMN_ALIASES["price"][0]: price,
        COLUMN_ALIASES["trade_amount"][0]: trade_amount,
    }
    if settlement_amount is not None:
        row[COLUMN_ALIASES["settlement_amount"][0]] = settlement_amount
    if fee is not None:
        row[COLUMN_ALIASES["fee"][0]] = fee
    if tax is not None:
        row[COLUMN_ALIASES["tax"][0]] = tax
    if currency is not None:
        row[COLUMN_ALIASES["currency"][0]] = currency
    if fx_rate is not None:
        row[COLUMN_ALIASES["exchange_rate"][0]] = fx_rate
    return row

def nh_detail_transaction_row(
    *,
    detail: str,
    transaction_raw: str = "\uc785\uae08",
    ticker: str = "",
    security_name: str = "",
    amount: str | int | float = 1000,
    currency: str | None = "KRW",
    tax: str | int | float | None = None,
) -> dict[str, object]:
    row = synthetic_transaction_row(
        transaction_raw=transaction_raw,
        ticker=ticker,
        security_name=security_name,
        quantity=0,
        price=0,
        trade_amount=amount,
        settlement_amount=amount,
        currency=currency,
        tax=tax,
    )
    row[COLUMN_ALIASES["memo"][0]] = ""
    row["\uc0c1\uc138\ub0b4\uc6a9"] = detail
    return row

def normalize_synthetic_transaction(tmp_path: Path, row: dict[str, object], file_name: str = "transaction_history.xlsx") -> pd.DataFrame:
    normalized, _, _ = normalize_dataframe(pd.DataFrame([row]), tmp_path / file_name, "Sheet1")
    assert len(normalized) == 1
    return normalized

def import_synthetic_transactions(tmp_path: Path, rows: list[dict[str, object]], file_name: str = "transaction_history.xlsx") -> Path:
    raw = tmp_path / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame(rows).to_excel(raw / file_name, index=False)
    import_raw_dir(tmp_path)
    return tmp_path / "70_Imports" / "processed"

def paired_header(first: str, second: str) -> str:
    return f"{first}{MULTIINDEX_COLUMN_SEPARATOR}{second}"

def paired_namoo_transaction_rows(transaction_header: str | None = None) -> list[dict[str, object]]:
    transaction_header = transaction_header or COLUMN_ALIASES["transaction_raw"][0]
    return [
        {
            COLUMN_ALIASES["trade_date"][0]: "2026-01-10",
            transaction_header: "buy",
            COLUMN_ALIASES["ticker"][0]: "AAPL",
            COLUMN_ALIASES["security_name"][0]: "Apple",
            paired_header(COLUMN_ALIASES["quantity"][0], COLUMN_ALIASES["price"][0]): "8",
            paired_header(COLUMN_ALIASES["trade_amount"][0], COLUMN_ALIASES["settlement_amount"][0]): "412",
            paired_header(COLUMN_ALIASES["fee"][0], COLUMN_ALIASES["tax"][0]): "1.25",
            paired_header(COLUMN_ALIASES["balance_quantity"][0], COLUMN_ALIASES["evaluation_amount"][0]): "100",
            paired_header(COLUMN_ALIASES["transaction_raw"][0], COLUMN_ALIASES["memo"][0]): "row one memo",
        },
        {
            COLUMN_ALIASES["trade_date"][0]: "",
            transaction_header: "",
            COLUMN_ALIASES["ticker"][0]: "",
            COLUMN_ALIASES["security_name"][0]: "",
            paired_header(COLUMN_ALIASES["quantity"][0], COLUMN_ALIASES["price"][0]): "51.5",
            paired_header(COLUMN_ALIASES["trade_amount"][0], COLUMN_ALIASES["settlement_amount"][0]): "410",
            paired_header(COLUMN_ALIASES["fee"][0], COLUMN_ALIASES["tax"][0]): "2.5",
            paired_header(COLUMN_ALIASES["balance_quantity"][0], COLUMN_ALIASES["evaluation_amount"][0]): "999999",
            paired_header(COLUMN_ALIASES["transaction_raw"][0], COLUMN_ALIASES["memo"][0]): "row two memo",
        },
    ]

def test_quantity_is_not_money_amount(tmp_path: Path):
    normalized = normalize_synthetic_transaction(tmp_path, synthetic_transaction_row())
    assert_columns_present(normalized, ["quantity_unit", "amount_kind", "amount_krw"])
    row = normalized.iloc[0]

    assert row["quantity"] == 8
    assert str(row["quantity_unit"]).lower() in {"", "share", "shares", "contract", "contracts"}
    assert str(row["amount_kind"]).lower() not in {"quantity", "share_quantity", "shares", "contracts"}
    assert is_blank_or_na(row["amount_krw"]) or float(row["amount_krw"]) != 8

def test_price_is_unit_price_not_total_money(tmp_path: Path):
    normalized = normalize_synthetic_transaction(tmp_path, synthetic_transaction_row())
    assert_columns_present(normalized, ["amount_kind", "price_unit"])
    row = normalized.iloc[0]
    kind_values = {str(row.get("price_kind", "")).lower(), str(row.get("amount_kind", "")).lower()}

    assert row["price"] == 51.5
    assert "unit_price" in kind_values
    assert "share" in str(row["price_unit"]).lower()

    processed = import_synthetic_transactions(tmp_path, [synthetic_transaction_row()])
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")
    assert cashflows.empty

def test_us_transaction_amount_is_native_usd_not_krw_without_fx(tmp_path: Path):
    normalized = normalize_synthetic_transaction(tmp_path, synthetic_transaction_row())
    assert_columns_present(normalized, ["currency_native", "trade_amount_native", "trade_amount_krw"])
    row = normalized.iloc[0]
    status = row.get("amount_review_status", row.get("amount_normalization_status", ""))

    assert row["market"] == "US"
    assert row["currency_native"] == "USD"
    assert row["trade_amount_native"] == 412
    assert is_blank_or_na(row["trade_amount_krw"])
    assert status == "fx_missing"

def test_isa_domestic_transaction_amount_defaults_to_krw(tmp_path: Path):
    row = synthetic_transaction_row(
        ticker="005930",
        security_name="Samsung Electronics",
        quantity=10,
        price=70000,
        trade_amount=700000,
    )
    normalized = normalize_synthetic_transaction(tmp_path, row, file_name="isa_transaction_history.xlsx")
    assert_columns_present(normalized, ["currency_native", "trade_amount_native", "trade_amount_krw"])
    out = normalized.iloc[0]
    status = out.get("amount_review_status", out.get("amount_normalization_status", ""))

    assert out["market"] == "KR"
    assert out["currency_native"] == "KRW"
    assert out["trade_amount_native"] == 700000
    assert out["trade_amount_krw"] == 700000
    assert status == "ok"

def test_foreign_dividend_is_income_not_external_principal(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="외화배당금입금 dividend",
            ticker="AAPL",
            security_name="Apple",
            quantity=0,
            price=0,
            trade_amount=12.34,
            currency="USD",
        )
    ])
    transactions = read_processed_csv(processed, "processed_transactions.csv")
    assert_columns_present(transactions, ["cashflow_role", "affects_principal", "affects_profit"])
    row = transactions.iloc[0]

    assert row["transaction_type"] == "dividend"
    assert row["cashflow_role"] == "income_dividend"
    assert not boolish(row["affects_principal"])
    assert boolish(row["affects_profit"])
    assert read_processed_csv(processed, "processed_cashflows.csv").empty

def test_krw_interest_is_income_not_external_principal(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="예탁금이용료 interest",
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=1200,
            currency="KRW",
        )
    ])
    transactions = read_processed_csv(processed, "processed_transactions.csv")
    assert_columns_present(transactions, ["cashflow_role", "affects_principal", "affects_profit"])
    row = transactions.iloc[0]

    assert row["transaction_type"] == "interest"
    assert row["cashflow_role"] == "income_interest"
    assert not boolish(row["affects_principal"])
    assert boolish(row["affects_profit"])
    assert read_processed_csv(processed, "processed_cashflows.csv").empty

def test_foreign_dividend_lands_in_processed_income_only(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="foreign dividend",
            ticker="AAPL",
            security_name="Apple",
            quantity=0,
            price=0,
            trade_amount=12.34,
            currency="USD",
        )
    ])

    income = read_processed_csv(processed, "processed_income.csv")
    expenses = read_processed_csv(processed, "processed_expenses.csv")
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")

    assert_columns_present(income, INCOME_OUTPUT_COLUMNS)
    assert_columns_present(expenses, EXPENSE_OUTPUT_COLUMNS)
    assert len(income) == 1
    row = income.iloc[0]
    assert row["income_type"] == "dividend"
    assert row["currency_native"] == "USD"
    assert row["amount_native"] == 12.34
    assert is_blank_or_na(row["amount_krw"])
    assert is_blank_or_na(row["amount_krw_source"])
    assert row["tax_native"] == 0
    assert row["tax_krw"] == 0
    assert row["amount_review_status"] == "fx_missing"
    assert not boolish(row["affects_principal"])
    assert boolish(row["affects_profit"])
    assert expenses.empty
    assert cashflows.empty

def test_krw_interest_lands_in_processed_income_only(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="interest",
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=1200,
            currency="KRW",
        )
    ])

    income = read_processed_csv(processed, "processed_income.csv")
    expenses = read_processed_csv(processed, "processed_expenses.csv")
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")

    assert_columns_present(income, INCOME_OUTPUT_COLUMNS)
    assert len(income) == 1
    row = income.iloc[0]
    assert row["income_type"] == "interest"
    assert row["currency_native"] == "KRW"
    assert row["amount_native"] == 1200
    assert row["amount_krw"] == 1200
    assert row["amount_krw_source"] == "raw_native"
    assert row["amount_review_status"] == "ok"
    assert not boolish(row["affects_principal"])
    assert boolish(row["affects_profit"])
    assert expenses.empty
    assert cashflows.empty

def test_distribution_lands_in_processed_income_when_detected(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="cash distribution",
            ticker="QQQI",
            security_name="ETF",
            quantity=0,
            price=0,
            trade_amount=3.5,
            currency="USD",
        )
    ])

    income = read_processed_csv(processed, "processed_income.csv")

    assert len(income) == 1
    assert income.iloc[0]["income_type"] == "distribution"
    assert income.iloc[0]["amount_review_status"] == "fx_missing"

def test_nh_detail_foreign_dividend_deposit_lands_in_income_not_principal(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        nh_detail_transaction_row(
            detail="외화배당금입금",
            ticker="AAPL",
            security_name="Apple",
            amount=12.34,
            currency="USD",
        )
    ])

    transactions = read_processed_csv(processed, "processed_transactions.csv")
    income = read_processed_csv(processed, "processed_income.csv")
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")

    tx = transactions.iloc[0]
    assert tx["transaction_type"] == "dividend"
    assert tx["cashflow_role"] == "income_dividend"
    assert not boolish(tx["affects_principal"])
    assert boolish(tx["affects_profit"])
    assert len(income) == 1
    assert income.iloc[0]["income_type"] == "dividend"
    assert income.iloc[0]["currency_native"] == "USD"
    assert income.iloc[0]["amount_review_status"] == "fx_missing"
    assert cashflows.empty

def test_nh_detail_dividend_deposit_does_not_increase_net_external_principal(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        nh_detail_transaction_row(detail="배당금입금", amount=3000, currency="KRW")
    ])

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    income = read_processed_csv(processed, "processed_income.csv")
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")

    assert len(income) == 1
    assert income.iloc[0]["income_type"] == "dividend"
    assert cashflows.empty
    assert float(metrics["net_external_principal_krw"]) == 0

def test_nh_detail_etf_distribution_deposit_lands_in_distribution_income(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        nh_detail_transaction_row(
            detail="ETF분배금입금",
            ticker="QQQI",
            security_name="Synthetic ETF",
            amount=700,
            currency="KRW",
        )
    ])

    transactions = read_processed_csv(processed, "processed_transactions.csv")
    income = read_processed_csv(processed, "processed_income.csv")

    assert transactions.iloc[0]["transaction_type"] == "distribution"
    assert transactions.iloc[0]["cashflow_role"] == "income_distribution"
    assert len(income) == 1
    assert income.iloc[0]["income_type"] == "distribution"
    assert income.iloc[0]["amount_review_status"] == "ok"

def test_nh_detail_interest_fee_lands_in_interest_income(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        nh_detail_transaction_row(detail="예탁금이용료", amount=1200, currency="KRW")
    ])

    transactions = read_processed_csv(processed, "processed_transactions.csv")
    income = read_processed_csv(processed, "processed_income.csv")

    assert transactions.iloc[0]["transaction_type"] == "interest"
    assert transactions.iloc[0]["cashflow_role"] == "income_interest"
    assert len(income) == 1
    assert income.iloc[0]["income_type"] == "interest"

def test_nh_detail_dividend_tax_is_not_dividend_income(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        nh_detail_transaction_row(detail="배당소득세", amount=300, currency="KRW")
    ])

    transactions = read_processed_csv(processed, "processed_transactions.csv")
    income = read_processed_csv(processed, "processed_income.csv")
    expenses = read_processed_csv(processed, "processed_expenses.csv")

    assert transactions.iloc[0]["transaction_type"] == "tax"
    assert transactions.iloc[0]["cashflow_role"] == "expense_tax"
    assert income.empty
    assert len(expenses) == 1
    assert expenses.iloc[0]["expense_type"] == "tax"

def test_nh_detail_dividend_correction_is_review_income_not_official_krw(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        nh_detail_transaction_row(detail="배당금입금 취소", amount=3000, currency="KRW")
    ])

    income = read_processed_csv(processed, "processed_income.csv")
    income_summary = build_income_summary(income)

    assert len(income) == 1
    assert income.iloc[0]["income_type"] == "dividend"
    assert income.iloc[0]["amount_review_status"] == "needs_review"
    assert "reversal/correction" in income.iloc[0]["amount_review_reason"]
    assert income_summary.iloc[0]["income_status"] == "needs_review"
    assert is_blank_or_na(income_summary.iloc[0]["amount_krw_sum"])

def test_fx_exchange_is_internal_transfer_not_principal_cashflow(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="환전 exchange",
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=100000,
            currency="KRW",
        )
    ])
    transactions = read_processed_csv(processed, "processed_transactions.csv")
    assert_columns_present(transactions, ["cashflow_role", "affects_principal", "is_internal_transfer", "fx_event_id", "fx_pair_status"])
    row = transactions.iloc[0]

    assert row["transaction_type"] == "exchange"
    assert row["cashflow_role"] == "internal_fx_exchange"
    assert not boolish(row["affects_principal"])
    assert boolish(row["is_internal_transfer"])
    assert str(row["fx_event_id"]).startswith("FX-")
    assert row["fx_pair_status"] == "partial"
    assert read_processed_csv(processed, "processed_cashflows.csv").empty

def test_fx_exchange_krw_usd_pair_outputs_two_internal_event_legs(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="외화매수 USD exchange",
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=638254,
            settlement_amount=430,
        )
    ])

    transactions = read_processed_csv(processed, "processed_transactions.csv")
    fx_events = read_processed_csv(processed, "processed_fx_events.csv")
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")
    amount_audit = read_processed_csv(processed, "amount_unit_audit.csv")
    mismatch_audit = read_processed_csv(processed, "unit_mismatch_audit.csv")

    assert_columns_present(fx_events, FX_EVENT_COLUMNS)
    assert len(fx_events) == 2
    assert fx_events["fx_event_id"].nunique() == 1
    assert str(fx_events["fx_event_id"].iloc[0]).startswith("FX-")
    assert set(fx_events["leg"]) == {"KRW_OUT", "USD_IN"}
    assert set(fx_events["fx_pair_status"]) == {"paired"}
    assert set(fx_events["cashflow_role"]) == {"internal_fx_exchange"}
    assert not fx_events["affects_principal"].map(boolish).any()
    assert not fx_events["affects_profit"].map(boolish).any()
    assert fx_events["is_internal_transfer"].map(boolish).all()

    usd_leg = fx_events[fx_events["currency_native"] == "USD"].iloc[0]
    assert usd_leg["amount_native"] == 430
    assert usd_leg["amount_krw"] == 638254
    assert abs(float(usd_leg["fx_rate_to_krw"]) - 1484.311628) < 0.001
    assert usd_leg["fx_rate_source"] == "implied_from_exchange_row"

    krw_leg = fx_events[fx_events["currency_native"] == "KRW"].iloc[0]
    assert krw_leg["amount_native"] == 638254
    assert krw_leg["amount_krw"] == 638254

    tx_row = transactions.iloc[0]
    assert tx_row["transaction_type"] == "exchange"
    assert tx_row["cashflow_role"] == "internal_fx_exchange"
    assert boolish(tx_row["is_internal_transfer"])
    assert cashflows.empty

    fx_audit = amount_audit[amount_audit["cashflow_role"].eq("internal_fx_exchange")]
    assert not fx_audit.empty
    assert set(fx_audit["amount_review_status"]) == {"ok"}

    fx_mismatch = mismatch_audit[mismatch_audit["cashflow_role"].eq("internal_fx_exchange")]
    assert not fx_mismatch.empty
    assert set(fx_mismatch["amount_normalization_status"]) == {"ok"}

def test_fx_exchange_single_detectable_leg_outputs_partial_event(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="환전 exchange",
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=100000,
            currency="KRW",
        )
    ])

    fx_events = read_processed_csv(processed, "processed_fx_events.csv")

    assert_columns_present(fx_events, FX_EVENT_COLUMNS)
    assert len(fx_events) == 1
    row = fx_events.iloc[0]
    assert str(row["fx_event_id"]).startswith("FX-")
    assert row["leg"] == "PARTIAL"
    assert row["currency_native"] == "KRW"
    assert row["amount_native"] == 100000
    assert row["amount_krw"] == 100000
    assert row["fx_pair_status"] == "partial"
    assert row["cashflow_role"] == "internal_fx_exchange"
    assert boolish(row["is_internal_transfer"])
    assert not boolish(row["affects_principal"])
    assert read_processed_csv(processed, "processed_cashflows.csv").empty

def test_processed_cashflows_contains_external_principal_only(tmp_path: Path):
    rows = [
        synthetic_transaction_row(transaction_raw="deposit", ticker="", security_name="", quantity=0, price=0, trade_amount=1000),
        synthetic_transaction_row(transaction_raw="withdrawal", ticker="", security_name="", quantity=0, price=0, trade_amount=250),
        synthetic_transaction_row(transaction_raw="외화배당금입금 dividend", quantity=0, price=0, trade_amount=10, currency="USD"),
        synthetic_transaction_row(transaction_raw="예탁금이용료 interest", ticker="", security_name="", quantity=0, price=0, trade_amount=5, currency="KRW"),
        synthetic_transaction_row(transaction_raw="환전 exchange", ticker="", security_name="", quantity=0, price=0, trade_amount=100),
        synthetic_transaction_row(transaction_raw="buy", ticker="AAPL", security_name="Apple", quantity=8, price=51.5, trade_amount=412),
        synthetic_transaction_row(transaction_raw="sell", ticker="AAPL", security_name="Apple", quantity=1, price=55, trade_amount=55),
    ]
    processed = import_synthetic_transactions(tmp_path, rows)
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")

    assert set(cashflows["transaction_type"]) == {"deposit", "withdrawal"}
    assert len(cashflows) == 2
    assert set(cashflows["cashflow_role"]) == {"external_principal"}
    assert cashflows["affects_principal"].map(boolish).all()
    assert not cashflows["affects_profit"].map(boolish).any()
    assert cashflows["amount_review_status"].eq("ok").all()
    assert not cashflows["settlement_amount_krw"].map(is_blank_or_na).any()
    assert not set(cashflows["transaction_type"]).intersection({"dividend", "interest", "exchange", "buy", "sell"})

def test_external_principal_requires_krw_normalized_amount(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="deposit",
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=100,
            currency="USD",
        )
    ])
    transactions = read_processed_csv(processed, "processed_transactions.csv")
    row = transactions.iloc[0]

    assert row["transaction_type"] == "deposit"
    assert row["cashflow_role"] == "external_principal"
    assert row["amount_review_status"] == "fx_missing"
    assert is_blank_or_na(row["settlement_amount_krw"])
    assert not boolish(row["affects_principal"])
    assert read_processed_csv(processed, "processed_cashflows.csv").empty

@pytest.mark.parametrize(
    ("transaction_raw", "expected_role"),
    [("fee", "expense_fee"), ("tax", "expense_tax")],
)
def test_standalone_fee_tax_are_profit_expense_not_external_principal(tmp_path: Path, transaction_raw: str, expected_role: str):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw=transaction_raw,
            ticker="",
            security_name="",
            quantity=0,
            price=0,
            trade_amount=1000,
            currency="KRW",
        )
    ])
    transactions = read_processed_csv(processed, "processed_transactions.csv")
    row = transactions.iloc[0]

    assert row["transaction_type"] == transaction_raw
    assert row["cashflow_role"] == expected_role
    assert not boolish(row["affects_principal"])
    assert boolish(row["affects_profit"])
    assert read_processed_csv(processed, "processed_cashflows.csv").empty

def test_attached_trade_fee_tax_lands_in_processed_expenses(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            transaction_raw="buy",
            ticker="005930",
            security_name="Samsung Electronics",
            quantity=10,
            price=70000,
            trade_amount=700000,
            fee=150,
            tax=50,
            currency="KRW",
        )
    ])

    expenses = read_processed_csv(processed, "processed_expenses.csv")
    cashflows = read_processed_csv(processed, "processed_cashflows.csv")

    assert_columns_present(expenses, EXPENSE_OUTPUT_COLUMNS)
    assert set(expenses["expense_type"]) == {"fee", "tax"}
    assert set(expenses["amount_kind"]) == {"fee", "tax"}
    assert not expenses["affects_principal"].map(boolish).any()
    assert expenses["affects_profit"].map(boolish).all()
    fee_row = expenses[expenses["expense_type"].eq("fee")].iloc[0]
    tax_row = expenses[expenses["expense_type"].eq("tax")].iloc[0]
    assert fee_row["amount_native"] == 150
    assert fee_row["amount_krw"] == 150
    assert fee_row["amount_review_status"] == "ok"
    assert tax_row["amount_native"] == 50
    assert tax_row["amount_krw"] == 50
    assert cashflows.empty

def test_income_and_expense_rows_do_not_appear_in_processed_cashflows(tmp_path: Path):
    rows = [
        synthetic_transaction_row(transaction_raw="deposit", ticker="", security_name="", quantity=0, price=0, trade_amount=1000, currency="KRW"),
        synthetic_transaction_row(transaction_raw="dividend", quantity=0, price=0, trade_amount=10, currency="KRW"),
        synthetic_transaction_row(transaction_raw="interest", ticker="", security_name="", quantity=0, price=0, trade_amount=5, currency="KRW"),
        synthetic_transaction_row(transaction_raw="fee", ticker="", security_name="", quantity=0, price=0, trade_amount=3, currency="KRW"),
        synthetic_transaction_row(transaction_raw="tax", ticker="", security_name="", quantity=0, price=0, trade_amount=2, currency="KRW"),
        synthetic_transaction_row(transaction_raw="buy", ticker="005930", security_name="Samsung Electronics", quantity=1, price=70000, trade_amount=70000, fee=1, tax=1, currency="KRW"),
    ]
    processed = import_synthetic_transactions(tmp_path, rows)

    cashflows = read_processed_csv(processed, "processed_cashflows.csv")
    income = read_processed_csv(processed, "processed_income.csv")
    expenses = read_processed_csv(processed, "processed_expenses.csv")

    assert set(income["income_type"]) == {"dividend", "interest"}
    assert set(expenses["expense_type"]) == {"fee", "tax"}
    assert set(cashflows["transaction_type"]) == {"deposit"}
    assert not set(cashflows["transaction_type"]).intersection({"dividend", "interest", "fee", "tax"})

def test_amount_unit_audit_includes_income_and_expense_rows(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(transaction_raw="dividend", quantity=0, price=0, trade_amount=10, currency="KRW"),
        synthetic_transaction_row(transaction_raw="interest", ticker="", security_name="", quantity=0, price=0, trade_amount=5, currency="KRW"),
        synthetic_transaction_row(
            transaction_raw="buy",
            ticker="005930",
            security_name="Samsung Electronics",
            quantity=1,
            price=70000,
            trade_amount=70000,
            fee=1,
            tax=2,
            currency="KRW",
        ),
    ])

    audit = read_processed_csv(processed, "amount_unit_audit.csv")

    assert_columns_present(audit, AMOUNT_UNIT_AUDIT_COLUMNS)
    assert {"income_dividend", "income_interest", "expense_fee", "expense_tax"}.issubset(set(audit["cashflow_role"]))
    assert {"dividend", "interest", "fee", "tax"}.issubset(set(audit["amount_kind"]))

def test_usd_buy_without_fx_appears_in_unit_mismatch_audit(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [synthetic_transaction_row()])

    amount_audit = read_processed_csv(processed, "amount_unit_audit.csv")
    mismatch = read_processed_csv(processed, "unit_mismatch_audit.csv")

    assert_columns_present(amount_audit, AMOUNT_UNIT_AUDIT_COLUMNS)
    assert_columns_present(mismatch, UNIT_MISMATCH_AUDIT_COLUMNS)
    buy_audit = amount_audit[amount_audit["transaction_type"].eq("buy")].iloc[0]
    buy_mismatch = mismatch[mismatch["transaction_type"].eq("buy")].iloc[0]
    assert buy_audit["currency_native"] == "USD"
    assert buy_audit["amount_review_status"] == "fx_missing"
    assert buy_audit["money_unit_native"] == "USD"
    assert buy_audit["money_unit_krw"] == "KRW"
    assert buy_mismatch["amount_normalization_status"] == "fx_missing"
    assert is_blank_or_na(buy_mismatch["trade_amount_krw"])

def test_isa_krw_buy_has_ok_status_in_amount_unit_audit(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(
            ticker="005930",
            security_name="Samsung Electronics",
            quantity=10,
            price=70000,
            trade_amount=700000,
        )
    ], file_name="isa_transaction_history.xlsx")

    amount_audit = read_processed_csv(processed, "amount_unit_audit.csv")
    row = amount_audit[amount_audit["transaction_type"].eq("buy")].iloc[0]

    assert row["currency_native"] == "KRW"
    assert row["amount_review_status"] == "ok"
    assert row["amount_native"] == 700000
    assert row["amount_krw"] == 700000
    assert row["amount_krw_source"] == "raw_native"

def test_fx_exchange_and_dividend_are_visible_in_audit_outputs(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(transaction_raw="exchange", ticker="", security_name="", quantity=0, price=0, trade_amount=100000, currency="KRW"),
        synthetic_transaction_row(transaction_raw="dividend", ticker="AAPL", security_name="Apple", quantity=0, price=0, trade_amount=12.34, currency="USD"),
    ])

    amount_audit = read_processed_csv(processed, "amount_unit_audit.csv")
    mismatch = read_processed_csv(processed, "unit_mismatch_audit.csv")

    exchange = amount_audit[amount_audit["transaction_type"].eq("exchange")].iloc[0]
    dividend = amount_audit[amount_audit["transaction_type"].eq("dividend")].iloc[0]
    assert exchange["cashflow_role"] == "internal_fx_exchange"
    assert boolish(exchange["is_internal_transfer"])
    assert not boolish(exchange["affects_principal"])
    assert dividend["cashflow_role"] == "income_dividend"
    assert boolish(dividend["affects_profit"])
    assert {"internal_fx_exchange", "income_dividend"}.issubset(set(mismatch["cashflow_role"]))

def test_audit_outputs_have_expected_headers_with_no_rows(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    import_raw_dir(tmp_path)

    amount_audit = pd.read_csv(processed / "amount_unit_audit.csv")
    mismatch = pd.read_csv(processed / "unit_mismatch_audit.csv")

    assert list(amount_audit.columns) == AMOUNT_UNIT_AUDIT_COLUMNS
    assert list(mismatch.columns) == UNIT_MISMATCH_AUDIT_COLUMNS
    assert amount_audit.empty
    assert mismatch.empty

def test_quantity_and_price_are_visible_as_units_not_principal(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [
        synthetic_transaction_row(transaction_raw="buy", ticker="AAPL", security_name="Apple", quantity=8, price=51.5, trade_amount=0, currency="USD")
    ])

    amount_audit = read_processed_csv(processed, "amount_unit_audit.csv")
    row = amount_audit.iloc[0]

    assert row["raw_quantity"] == 8
    assert row["raw_price"] == 51.5
    assert row["quantity_unit"] == "shares"
    assert str(row["price_unit"]).endswith("/share")
    assert row["amount_kind"] == "unit_price"
    assert row["amount_basis"] == "not_money"
    assert not boolish(row["affects_principal"])

def test_amount_unit_audit_exists_after_import(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [synthetic_transaction_row()])
    audit_path = processed / "amount_unit_audit.csv"

    assert audit_path.exists()
    audit = pd.read_csv(audit_path)
    assert_columns_present(audit, AMOUNT_UNIT_AUDIT_COLUMNS)

def test_unit_mismatch_audit_exists_after_import(tmp_path: Path):
    processed = import_synthetic_transactions(tmp_path, [synthetic_transaction_row()])
    audit_path = processed / "unit_mismatch_audit.csv"

    assert audit_path.exists()
    audit = pd.read_csv(audit_path)
    assert_columns_present(audit, UNIT_MISMATCH_AUDIT_COLUMNS)

def amount_only_cashflow_row(**overrides):
    row = {
        COLUMN_ALIASES["trade_amount"][0]: "100",
        COLUMN_ALIASES["settlement_amount"][0]: "100",
        COLUMN_ALIASES["currency"][0]: "USD",
        COLUMN_ALIASES["exchange_rate"][0]: "1473.10",
        COLUMN_ALIASES["quantity"][0]: "0",
        COLUMN_ALIASES["price"][0]: "0",
        COLUMN_ALIASES["fee"][0]: "0",
        COLUMN_ALIASES["tax"][0]: "0",
    }
    row.update(overrides)
    return row

def import_single_overseas_cashflow_row(vault: Path, row: dict[str, str]) -> Path:
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([row]).to_excel(raw / "overseas_cashflow.xlsx", index=False)
    import_raw_dir(vault)
    return vault / "70_Imports" / "processed"

def test_overseas_cashflow_amount_only_no_identity_row_is_skipped(tmp_path: Path):
    processed = import_single_overseas_cashflow_row(tmp_path, amount_only_cashflow_row())

    transactions = pd.read_csv(processed / "processed_transactions.csv")
    unclassified = pd.read_csv(processed / "unclassified_rows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert transactions.empty
    assert unclassified.empty
    assert len(skipped) == 1
    assert skipped["skip_reason"].iloc[0] == OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON
    assert skipped["currency"].iloc[0] == "USD"

def test_amount_only_row_with_date_is_not_skipped(tmp_path: Path):
    processed = import_single_overseas_cashflow_row(
        tmp_path,
        amount_only_cashflow_row(**{COLUMN_ALIASES["trade_date"][0]: "2026-04-29"}),
    )

    unclassified = pd.read_csv(processed / "unclassified_rows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert len(unclassified) == 1
    assert skipped.empty

def test_amount_only_row_with_memo_is_not_skipped(tmp_path: Path):
    processed = import_single_overseas_cashflow_row(
        tmp_path,
        amount_only_cashflow_row(**{COLUMN_ALIASES["memo"][0]: "manual review"}),
    )

    unclassified = pd.read_csv(processed / "unclassified_rows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert len(unclassified) == 1
    assert skipped.empty

def test_amount_only_row_with_deposit_keyword_is_not_skipped(tmp_path: Path):
    processed = import_single_overseas_cashflow_row(
        tmp_path,
        amount_only_cashflow_row(**{COLUMN_ALIASES["transaction_raw"][0]: "deposit"}),
    )

    transactions = pd.read_csv(processed / "processed_transactions.csv")
    unclassified = pd.read_csv(processed / "unclassified_rows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert len(transactions) == 1
    assert transactions["transaction_type"].iloc[0] == "deposit"
    assert unclassified.empty
    assert skipped.empty

def test_cashflow_deposit_amount_column_creates_deposit_after_aug_2025(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"거래일자": "2025-09-02", "적요": "monthly cash add", "입금액": "1000000", "출금액": "0"},
        {"거래일자": "2025-09-03", "적요": "cash withdrawal", "입금액": "0", "출금액": "250000"},
    ]).to_excel(raw / "cash_after_aug_2025.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")
    source_index = pd.read_csv(processed / "source_file_index.csv")
    unclassified = pd.read_csv(processed / "unclassified_rows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert source_index["source_file_type"].iloc[0] == "cashflow"
    assert cashflows["trade_date"].tolist() == ["2025-09-02", "2025-09-03"]
    assert cashflows["transaction_type"].tolist() == ["deposit", "withdrawal"]
    assert cashflows["settlement_amount"].tolist() == [1000000, 250000]
    assert unclassified.empty
    assert skipped.empty

def test_position_like_deposit_rows_stay_out_of_principal_cashflows(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"거래일자": "2025-09-02", "적요": "monthly cash add", "입금액": "1000000", "출금액": "0"},
        {"거래일자": "2025-09-03", "종목코드": "AAPL", "종목명": "Apple", "수량": "1", "입금액": "100", "출금액": "0"},
    ]).to_excel(raw / "cash_after_aug_2025.xlsx", index=False)
    pd.DataFrame([
        {"거래일자": "2025-09-04", "거래유형": "입금", "거래금액": "500000"},
        {"거래일자": "2025-09-05", "거래유형": "입금", "종목코드": "TSLA", "종목명": "Tesla", "수량": "1", "거래금액": "200"},
    ]).to_excel(raw / "종합거래내역.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    transactions = pd.read_csv(processed / "processed_transactions.csv")
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")

    assert len(transactions[transactions["transaction_type"] == "deposit"]) == 4
    assert cashflows["settlement_amount"].tolist() == [1000000, 500000]
    assert cashflows["transaction_type"].tolist() == ["deposit", "deposit"]
    assert cashflows["ticker"].fillna("").tolist() == ["", ""]
    assert cashflows["quantity"].fillna(0).tolist() == [0, 0]

def test_adjacent_duplicate_principal_cashflow_rows_are_skipped(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "잔고": "1000000", "받는통장표시내용 거래내역메모": "nan"},
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "잔고": "0", "받는통장표시내용 거래내역메모": ""},
    ]).to_excel(raw / "종합거래내역.xlsx", index=False)

    summary = import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    transactions = pd.read_csv(processed / "processed_transactions.csv")
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert summary.duplicate_rows_removed == 1
    assert len(transactions) == 1
    assert len(cashflows) == 1
    assert cashflows["settlement_amount"].tolist() == [200000]
    assert skipped["skip_reason"].iloc[0] == BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON
    assert skipped["row_count"].iloc[0] == 1

def test_non_adjacent_same_amount_principal_cashflows_are_preserved(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000"},
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "1000"},
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000"},
    ]).to_excel(raw / "종합거래내역.xlsx", index=False)

    import_raw_dir(vault)
    cashflows = pd.read_csv(vault / "70_Imports" / "processed" / "processed_cashflows.csv")

    assert len(cashflows) == 3
    assert cashflows["settlement_amount"].tolist() == [200000, 1000, 200000]

def test_cashflow_view_dedupes_residual_pair_after_adjacent_helper_skip(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "받는통장표시내용 거래내역메모": "same transfer"},
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "받는통장표시내용 거래내역메모": ""},
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "받는통장표시내용 거래내역메모": "same transfer"},
    ]).to_excel(raw / "종합거래내역.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    transactions = pd.read_csv(processed / "processed_transactions.csv")
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")

    assert len(transactions) == 2
    assert len(cashflows) == 1
    assert cashflows["settlement_amount"].tolist() == [200000]

def test_adjacent_same_amount_principal_cashflows_with_distinct_memos_are_preserved(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "받는통장표시내용 거래내역메모": "first transfer"},
        {"거래일자": "2026-01-10", "거래유형": "입금", "거래금액": "200000", "받는통장표시내용 거래내역메모": "second transfer"},
    ]).to_excel(raw / "종합거래내역.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")
    skipped = pd.read_csv(processed / "skipped_rows.csv")

    assert len(cashflows) == 2
    assert skipped.empty

def test_cashflow_named_position_snapshot_becomes_holdings_view(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {
            "No": 1,
            "조회일": "2026-06-28",
            "잔고유형": "stock",
            "상품명": "Samsung",
            "상품코드": "005930",
            "구분": "domestic",
            "수량": "2",
            "현재가": "70000",
            "매입금액": "120000",
            "평가금액": "140000",
            "평가손익": "20000",
            "수익률": "16.67",
        },
    ]).to_excel(raw / "입출금_잔고.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    idx = pd.read_csv(processed / "source_file_index.csv")
    transactions = pd.read_csv(processed / "processed_transactions.csv")
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")
    holdings = pd.read_csv(processed / "processed_holdings.csv")

    assert set(idx["source_file_type"]) == {"holdings"}
    assert idx["snapshot_date"].iloc[0] == "2026-06-28"
    assert transactions.empty
    assert cashflows.empty
    assert len(holdings) == 1
    assert holdings["source_file_type"].iloc[0] == "holdings"
    assert holdings["snapshot_date"].iloc[0] == "2026-06-28"
    assert str(holdings["ticker"].iloc[0]).zfill(6) == "005930"
    assert holdings["balance_quantity"].iloc[0] == 2
    assert holdings["evaluation_amount"].iloc[0] == 140000

def test_holding_collapse_prefers_latest_explicit_snapshot_date(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {
            "No": 1,
            "조회일": "2026-06-27",
            "잔고유형": "stock",
            "상품명": "Samsung",
            "상품코드": "005930",
            "구분": "domestic",
            "수량": "1",
            "현재가": "60000",
            "평가금액": "60000",
        },
        {
            "No": 2,
            "조회일": "2026-06-29",
            "잔고유형": "stock",
            "상품명": "Samsung",
            "상품코드": "005930",
            "구분": "domestic",
            "수량": "2",
            "현재가": "70000",
            "평가금액": "140000",
        },
    ]).to_excel(raw / "입출금_잔고.xlsx", index=False)

    import_raw_dir(vault)
    holdings = pd.read_csv(vault / "70_Imports" / "processed" / "processed_holdings.csv")

    assert len(holdings) == 1
    assert holdings["snapshot_date"].iloc[0] == "2026-06-29"
    assert holdings["balance_quantity"].iloc[0] == 2
    assert holdings["evaluation_amount"].iloc[0] == 140000

def test_overseas_cashflow_named_position_snapshot_becomes_overseas_balance(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {
            "기준일": "2026-06-29",
            "구분 구분": "stock",
            "종목명 (코드) 종목명 (코드)": "Apple (AAPL)",
            "시장명 시장명": "NASDAQ",
            "보유수량 보유수량": "3",
            "매입가 현재가": "150",
            "장부금액(외화) 장부금액(원화)": "400",
            "평가금액(외화) 평가금액(원화)": "450",
            "평가손익(외화) 평가손익(원화)": "50",
            "수익률(외화) 수익률(원화)": "12.5",
            "통화 환율": "USD",
        },
    ]).to_excel(raw / "overseas_cashflow.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    idx = pd.read_csv(processed / "source_file_index.csv")
    transactions = pd.read_csv(processed / "processed_transactions.csv")
    cashflows = pd.read_csv(processed / "processed_cashflows.csv")
    holdings = pd.read_csv(processed / "processed_holdings.csv")

    assert set(idx["source_file_type"]) == {"overseas_balance"}
    assert idx["snapshot_date"].iloc[0] == "2026-06-29"
    assert transactions.empty
    assert cashflows.empty
    assert len(holdings) == 1
    assert holdings["source_file_type"].iloc[0] == "overseas_balance"
    assert holdings["snapshot_date"].iloc[0] == "2026-06-29"
    assert holdings["account_type"].iloc[0] == "overseas"
    assert holdings["balance_quantity"].iloc[0] == 3
    assert holdings["evaluation_amount"].iloc[0] == 450
    assert holdings["currency"].iloc[0] == "USD"

def test_overseas_balance_preferred_over_comprehensive_holding_duplicate(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_comprehensive.xlsx", "source_file_type": "holdings", "account_type": "comprehensive"},
        {"source_file": "source_overseas.xlsx", "source_file_type": "overseas_balance", "account_type": "overseas"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"ticker": "AAPL", "security_name": "Apple", "account_type": "comprehensive", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 1, "evaluation_amount": 100, "unrealized_pnl": 0, "pnl_pct": 0, "source_file_type": "holdings"},
        {"ticker": "AAPL", "security_name": "Apple", "account_type": "overseas", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 1, "evaluation_amount": 100, "unrealized_pnl": 0, "pnl_pct": 0, "source_file_type": "overseas_balance"},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["ticker"]).to_csv(processed / "processed_transactions.csv", index=False)

    summary, holdings, _, _, _ = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))
    assert len(holdings) == 1
    assert holdings["source_file_type"].iloc[0] == "overseas_balance"
    assert float(summary_map["total_portfolio_value"]) == 100

def test_overseas_balance_name_symbol_dedupes_comprehensive_isin_row(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_comprehensive.xlsx", "source_file_type": "holdings", "account_type": "comprehensive"},
        {"source_file": "source_overseas.xlsx", "source_file_type": "overseas_balance", "account_type": "overseas"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {
            "ticker": "US88160R1014",
            "security_name": "테슬라",
            "account_type": "comprehensive",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "balance_quantity": 1,
            "evaluation_amount": 100,
            "unrealized_pnl": 0,
            "pnl_pct": 0,
            "source_file_type": "holdings",
        },
        {
            "ticker": "테슬라 (TSLA)",
            "security_name": "테슬라 (TSLA)",
            "account_type": "overseas",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "balance_quantity": 1,
            "evaluation_amount": 100,
            "unrealized_pnl": 0,
            "pnl_pct": 0,
            "source_file_type": "overseas_balance",
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["ticker"]).to_csv(processed / "processed_transactions.csv", index=False)

    summary, holdings, _, _, _ = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))
    assert len(holdings) == 1
    assert holdings["source_file_type"].iloc[0] == "overseas_balance"
    assert float(summary_map["total_portfolio_value"]) == 100

def test_dedupe_holdings_retains_overseas_balance_for_same_overseas_position():
    rows = pd.DataFrame([
        {
            "source_file": "source_comprehensive.xlsx",
            "source_file_type": "holdings",
            "account_type": "comprehensive",
            "ticker": "AEHR",
            "security_name": "Aehr Test Systems",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "balance_quantity": 3.0,
            "evaluation_amount": 300.01,
            "trade_amount": 250.0,
        },
        {
            "source_file": "source_overseas.xlsx",
            "source_file_type": "overseas_balance",
            "account_type": "overseas",
            "ticker": "AEHR",
            "security_name": "Aehr Test Systems",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "balance_quantity": 3.0,
            "evaluation_amount": 300.00,
            "trade_amount": 250.0,
        },
    ])

    deduped = dedupe_holdings(rows)

    assert len(deduped) == 1
    assert deduped["source_file_type"].iloc[0] == "overseas_balance"
    assert deduped["dedupe_action"].iloc[0] == "retained_preferred"
    assert deduped["dedupe_reason"].iloc[0] == "overseas_balance_retained_over_holdings_duplicate"
    assert int(deduped["dedupe_excluded_count"].iloc[0]) == 1
    assert float(deduped["dedupe_excluded_evaluation_amount"].iloc[0]) == pytest.approx(300.01)

def test_dedupe_holdings_handles_comprehensive_isin_krw_zero_quantity_duplicate():
    rows = pd.DataFrame([
        {
            "source_file": "source_comprehensive.xlsx",
            "source_file_type": "holdings",
            "account_type": "comprehensive",
            "ticker": "US00760J1088",
            "security_name": "\uc5d0\ud750\ub974 \ud14c\uc2a4\ud2b8 \uc2dc\uc2a4\ud15c\uc988",
            "market": "US",
            "asset_type": "stock",
            "currency": "KRW",
            "balance_quantity": 0.0,
            "evaluation_amount": 391019.0,
            "unrealized_pnl": 139207.0,
            "pnl_pct": 55.28,
        },
        {
            "source_file": "source_overseas.xlsx",
            "source_file_type": "overseas_balance",
            "account_type": "overseas",
            "ticker": "\uc5d0\ud750\ub974 \ud14c\uc2a4\ud2b8 \uc2dc\uc2a4\ud15c\uc988 (AEHR)",
            "security_name": "\uc5d0\ud750\ub974 \ud14c\uc2a4\ud2b8 \uc2dc\uc2a4\ud15c\uc988 (AEHR)",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "balance_quantity": 3.0,
            "evaluation_amount": 391019.0,
            "unrealized_pnl": 139207.0,
            "pnl_pct": 55.28,
        },
    ])

    deduped = dedupe_holdings(rows)

    assert len(deduped) == 1
    assert deduped["source_file_type"].iloc[0] == "overseas_balance"
    assert "AEHR" in deduped["ticker"].iloc[0]
    assert deduped["dedupe_action"].iloc[0] == "retained_preferred"
    assert int(deduped["dedupe_excluded_count"].iloc[0]) == 1
    assert float(deduped["dedupe_excluded_evaluation_amount"].iloc[0]) == pytest.approx(391019.0)

def test_dedupe_holdings_fallback_matches_name_when_isin_alias_unknown():
    rows = pd.DataFrame([
        {
            "source_file_type": "holdings",
            "account_type": "comprehensive",
            "ticker": "US1234567890",
            "security_name": "Example Robotics",
            "market": "US",
            "asset_type": "stock",
            "currency": "KRW",
            "balance_quantity": 0.0,
            "evaluation_amount": 1000.0,
            "unrealized_pnl": 100.0,
            "pnl_pct": 11.11,
        },
        {
            "source_file_type": "overseas_balance",
            "account_type": "overseas",
            "ticker": "Example Robotics (EXRB)",
            "security_name": "Example Robotics (EXRB)",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "balance_quantity": 10.0,
            "evaluation_amount": 1000.0,
            "unrealized_pnl": 100.0,
            "pnl_pct": 11.11,
        },
    ])

    deduped = dedupe_holdings(rows)

    assert len(deduped) == 1
    assert deduped["source_file_type"].iloc[0] == "overseas_balance"
    assert "EXRB" in deduped["ticker"].iloc[0]

def test_aehr_crdo_duplicates_do_not_double_count_portfolio_summary(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_comprehensive.xlsx", "source_file_type": "holdings", "account_type": "comprehensive"},
        {"source_file": "source_overseas.xlsx", "source_file_type": "overseas_balance", "account_type": "overseas"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"ticker": "US00760J1088", "security_name": "Aehr Test Systems", "account_type": "comprehensive", "market": "US", "asset_type": "stock", "currency": "KRW", "balance_quantity": 0, "evaluation_amount": 300, "unrealized_pnl": -30, "pnl_pct": -10, "source_file_type": "holdings"},
        {"ticker": "Aehr Test Systems (AEHR)", "security_name": "Aehr Test Systems (AEHR)", "account_type": "overseas", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 3, "evaluation_amount": 300, "unrealized_pnl": -30, "pnl_pct": -10, "source_file_type": "overseas_balance"},
        {"ticker": "KYG254571055", "security_name": "Credo Technology Group Holding", "account_type": "comprehensive", "market": "US", "asset_type": "stock", "currency": "KRW", "balance_quantity": 0, "evaluation_amount": 400, "unrealized_pnl": 40, "pnl_pct": 10, "source_file_type": "holdings"},
        {"ticker": "Credo Technology Group Holding (CRDO)", "security_name": "Credo Technology Group Holding (CRDO)", "account_type": "overseas", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 4, "evaluation_amount": 400, "unrealized_pnl": 40, "pnl_pct": 10, "source_file_type": "overseas_balance"},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["ticker"]).to_csv(processed / "processed_transactions.csv", index=False)

    summary, holdings, risk, _review, _history = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))

    assert len(holdings) == 2
    assert set(holdings["ticker"]) == {"Aehr Test Systems (AEHR)", "Credo Technology Group Holding (CRDO)"}
    assert set(holdings["source_file_type"]) == {"overseas_balance"}
    assert float(summary_map["total_portfolio_value"]) == 700
    assert float(summary_map["total_cost"]) == 690
    assert float(summary_map["total_unrealized_pnl"]) == 10
    assert float(summary_map["pnl_pct"]) == pytest.approx(1.4493)
    assert int(summary_map["holding_dedupe_excluded_rows"]) == 2
    assert int(summary_map["holding_dedupe_retained_rows"]) == 2
    assert float(summary_map["holding_dedupe_excluded_evaluation_amount"]) == 700
    assert risk["ticker"].tolist().count("AEHR") <= 1

def test_dedupe_does_not_remove_domestic_and_overseas_different_market_currency():
    rows = pd.DataFrame([
        {"ticker": "005930", "security_name": "Samsung Electronics", "account_type": "comprehensive", "market": "KR", "asset_type": "stock", "currency": "KRW", "balance_quantity": 1, "evaluation_amount": 70000, "source_file_type": "holdings"},
        {"ticker": "005930", "security_name": "Samsung Electronics ADR", "account_type": "overseas", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 1, "evaluation_amount": 50, "source_file_type": "overseas_balance"},
    ])

    deduped = dedupe_holdings(rows)

    assert len(deduped) == 2
    assert set(deduped["market"]) == {"KR", "US"}

def test_dedupe_does_not_remove_same_ticker_in_distinct_accounts():
    rows = pd.DataFrame([
        {"ticker": "AEHR", "security_name": "Aehr Test Systems", "account_type": "taxable_a", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 3, "evaluation_amount": 300, "source_file_type": "holdings"},
        {"ticker": "AEHR", "security_name": "Aehr Test Systems", "account_type": "taxable_b", "market": "US", "asset_type": "stock", "currency": "USD", "balance_quantity": 3, "evaluation_amount": 300, "source_file_type": "overseas_balance"},
    ])

    deduped = dedupe_holdings(rows)

    assert len(deduped) == 2
    assert set(deduped["account_type"]) == {"taxable_a", "taxable_b"}

def test_transaction_history_with_balance_columns_is_not_holdings(tmp_path: Path):
    df = pd.DataFrame([
        {
            "실거래일자": "2026-04-29",
            "거래유형": "매수",
            "상세내용": "코스피매수",
            "종목명": "삼성전자 005930",
            "수량": "1",
            "거래금액": "70000",
            "잔고금액": "70000",
        }
    ])
    path = tmp_path / "종합거래내역 상세.xls"
    assert infer_source_file_type(path, "table_0", df) == "transaction_history"
    normalized, _, _ = normalize_dataframe(df, path, "table_0")
    assert normalized["source_file_type"].iloc[0] == "transaction_history"
    assert pd.isna(normalized["balance_quantity"].iloc[0])
    assert pd.isna(normalized["evaluation_amount"].iloc[0])
    assert pd.isna(normalized["pnl_pct"].iloc[0])

def test_multiindex_transaction_history_uses_leaf_headers_for_amount_columns(tmp_path: Path):
    columns = pd.MultiIndex.from_tuples([
        (COLUMN_ALIASES["trade_date"][0], COLUMN_ALIASES["trade_date"][0]),
        (COLUMN_ALIASES["transaction_raw"][0], COLUMN_ALIASES["transaction_raw"][0]),
        (COLUMN_ALIASES["security_name"][0], COLUMN_ALIASES["security_name"][0]),
        (COLUMN_ALIASES["quantity"][0], COLUMN_ALIASES["price"][0]),
        (COLUMN_ALIASES["trade_amount"][0], COLUMN_ALIASES["settlement_amount"][0]),
    ])
    df = pd.DataFrame(
        [["2026-04-29", "buy", "Test Security 005930", "123.45", "678.90"]],
        columns=columns,
    )
    normalized, _, _ = normalize_dataframe(df, tmp_path / "transaction_history.xlsx", "table_0")

    assert len(normalized) == 1
    row = normalized.iloc[0]
    assert row["source_file_type"] == "transaction_history"
    assert row["transaction_type"] == "buy"
    assert row["quantity"] == 123.45
    assert row["price"] == 0
    assert row["trade_amount"] == 0
    assert row["settlement_amount"] == 678.9

def test_paired_namoo_transaction_rows_collapse_before_unit_normalization(tmp_path: Path):
    df = pd.DataFrame(paired_namoo_transaction_rows())
    normalized, raw_audit, _ = normalize_dataframe(df, tmp_path / "transaction_history.xlsx", "table_0")

    assert len(normalized) == 1
    row = normalized.iloc[0]
    assert row["source_file_type"] == "transaction_history"
    assert row["transaction_type"] == "buy"
    assert row["ticker"] == "AAPL"
    assert row["quantity"] == 8
    assert row["price"] == 51.5
    assert row["trade_amount"] == 412
    assert row["settlement_amount"] == 410
    assert row["fee"] == 1.25
    assert row["tax"] == 2.5
    assert pd.isna(row["balance_quantity"])
    assert pd.isna(row["evaluation_amount"])
    assert row["quantity_unit"] == "shares"
    assert row["price_kind"] == "unit_price"
    assert row["price_unit"] == "USD/share"
    assert row["currency_native"] == "USD"
    assert row["trade_amount_native"] == 412
    assert is_blank_or_na(row["trade_amount_krw"])
    assert row["settlement_amount_native"] == 410
    assert is_blank_or_na(row["settlement_amount_krw"])
    assert row["amount_kind"] == "trade_amount"
    assert row["cashflow_role"] == "trade_settlement"
    assert row["amount_review_status"] == "fx_missing"
    assert row["_source_sheet"] == "table_0"
    assert row["_raw_row_number"] == "1-2"
    assert raw_audit["row_number"].iloc[0] == "1-2"
    assert "row one memo" in row["raw_memo"]
    assert "row two memo" in row["raw_memo"]

def test_paired_namoo_transaction_rows_support_noncanonical_transaction_alias(tmp_path: Path):
    df = pd.DataFrame(paired_namoo_transaction_rows(transaction_header=COLUMN_ALIASES["transaction_raw"][1]))
    normalized, _, _ = normalize_dataframe(df, tmp_path / "transaction_history.xlsx", "table_0")

    assert len(normalized) == 1
    row = normalized.iloc[0]
    assert row["transaction_type"] == "buy"
    assert row["quantity"] == 8
    assert row["price"] == 51.5
    assert row["_raw_row_number"] == "1-2"
    assert "row one memo" in row["raw_memo"]
    assert "row two memo" in row["raw_memo"]

def test_back_to_back_paired_namoo_transactions_collapse_to_two_logical_rows(tmp_path: Path):
    tsla_rows = paired_namoo_transaction_rows()
    tsla_rows[0].update({
        COLUMN_ALIASES["trade_date"][0]: "2026-01-11",
        COLUMN_ALIASES["ticker"][0]: "TSLA",
        COLUMN_ALIASES["security_name"][0]: "Tesla",
        paired_header(COLUMN_ALIASES["quantity"][0], COLUMN_ALIASES["price"][0]): "2",
        paired_header(COLUMN_ALIASES["trade_amount"][0], COLUMN_ALIASES["settlement_amount"][0]): "200",
        paired_header(COLUMN_ALIASES["fee"][0], COLUMN_ALIASES["tax"][0]): "0.5",
    })
    tsla_rows[1].update({
        paired_header(COLUMN_ALIASES["quantity"][0], COLUMN_ALIASES["price"][0]): "100",
        paired_header(COLUMN_ALIASES["trade_amount"][0], COLUMN_ALIASES["settlement_amount"][0]): "198",
        paired_header(COLUMN_ALIASES["fee"][0], COLUMN_ALIASES["tax"][0]): "1.0",
    })
    df = pd.DataFrame(paired_namoo_transaction_rows() + tsla_rows)
    normalized, _, _ = normalize_dataframe(df, tmp_path / "transaction_history.xlsx", "table_0")

    assert len(normalized) == 2
    assert list(normalized["_raw_row_number"]) == ["1-2", "3-4"]
    assert list(normalized["ticker"]) == ["AAPL", "TSLA"]
    assert list(normalized["cashflow_role"]) == ["trade_settlement", "trade_settlement"]
    assert list(normalized["quantity"]) == [8, 2]
    assert list(normalized["price"]) == [51.5, 100]
    assert list(normalized["trade_amount"]) == [412, 200]
    assert list(normalized["settlement_amount"]) == [410, 198]
    assert list(normalized["fee"]) == [1.25, 0.5]
    assert list(normalized["tax"]) == [2.5, 1.0]
    for _, row in normalized.iterrows():
        assert row["quantity_unit"] == "shares"
        assert row["price_kind"] == "unit_price"
        assert row["currency_native"] == "USD"
        assert row["amount_review_status"] == "fx_missing"

def test_adjacent_new_transaction_row_does_not_pair_collapse(tmp_path: Path):
    first_row = paired_namoo_transaction_rows()[0]
    second_row = paired_namoo_transaction_rows()[0]
    second_row.update({
        COLUMN_ALIASES["trade_date"][0]: "2026-01-11",
        COLUMN_ALIASES["transaction_raw"][0]: "sell",
        COLUMN_ALIASES["ticker"][0]: "TSLA",
        COLUMN_ALIASES["security_name"][0]: "Tesla",
        paired_header(COLUMN_ALIASES["quantity"][0], COLUMN_ALIASES["price"][0]): "2",
        paired_header(COLUMN_ALIASES["trade_amount"][0], COLUMN_ALIASES["settlement_amount"][0]): "200",
        paired_header(COLUMN_ALIASES["fee"][0], COLUMN_ALIASES["tax"][0]): "0.5",
    })
    normalized, _, _ = normalize_dataframe(pd.DataFrame([first_row, second_row]), tmp_path / "transaction_history.xlsx", "table_0")

    assert len(normalized) == 2
    assert "1-2" not in set(normalized["_raw_row_number"])
    assert list(normalized["_raw_row_number"]) == ["1", "2"]
    assert list(normalized["transaction_type"]) == ["buy", "sell"]

def test_import_paired_namoo_transaction_rows_does_not_create_holdings(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame(paired_namoo_transaction_rows()).to_excel(raw / "transaction_history.xlsx", index=False)

    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    transactions = read_processed_csv(processed, "processed_transactions.csv")
    holdings = read_processed_csv(processed, "processed_holdings.csv")

    assert len(transactions) == 1
    row = transactions.iloc[0]
    assert row["transaction_type"] == "buy"
    assert row["quantity"] == 8
    assert row["price"] == 51.5
    assert row["trade_amount"] == 412
    assert row["settlement_amount"] == 410
    assert row["fee"] == 1.25
    assert row["tax"] == 2.5
    assert row["quantity_unit"] == "shares"
    assert row["price_kind"] == "unit_price"
    assert row["currency_native"] == "USD"
    assert row["trade_amount_native"] == 412
    assert is_blank_or_na(row["trade_amount_krw"])
    assert row["cashflow_role"] == "trade_settlement"
    assert row["amount_review_status"] == "fx_missing"
    assert holdings.empty

def test_transaction_history_precedence_over_cashflow_keywords():
    df = pd.DataFrame([
        {
            "실거래일자": "2026-04-29",
            "거래유형": "매수",
            "상세내용": "synthetic transaction row",
            "예수금": "100",
            "출금가능금액": "100",
        }
    ])
    path = Path("종합거래내역(상세)_sample.xls")
    assert infer_source_file_type(path, "Sheet1", df) == "transaction_history"

def test_import_transaction_history_does_not_create_holdings(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"실거래일자": "2026-04-29", "거래유형": "매수", "상세내용": "코스피매수", "종목명": "삼성전자 005930", "수량": "1", "거래금액": "70000", "잔고금액": "70000"},
    ]).to_excel(raw / "종합거래내역 상세.xlsx", index=False)
    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    idx = pd.read_csv(processed / "source_file_index.csv")
    tx = pd.read_csv(processed / "processed_transactions.csv")
    holdings = pd.read_csv(processed / "processed_holdings.csv")
    assert set(idx["source_file_type"]) == {"transaction_history"}
    assert len(tx) == 1
    assert len(holdings) == 0

def test_mixed_transaction_history_and_holdings_split_correctly(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"실거래일자": "2026-04-29", "거래유형": "매수", "상세내용": "코스피매수", "종목명": "삼성전자 005930", "수량": "1", "거래금액": "70000", "잔고금액": "70000"},
    ]).to_excel(raw / "종합거래내역 상세.xlsx", index=False)
    pd.DataFrame([
        {"종목명": "삼성전자", "종목코드": "005930", "보유수량": "2", "평가금액": "140000", "평가손익": "1000", "평가손익률": "0.71"},
    ]).to_excel(raw / "종합잔고.xlsx", index=False)
    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    idx = pd.read_csv(processed / "source_file_index.csv")
    tx = pd.read_csv(processed / "processed_transactions.csv")
    holdings = pd.read_csv(processed / "processed_holdings.csv")
    assert set(idx["source_file_type"]) == {"transaction_history", "holdings"}
    assert len(tx) == 1
    assert len(holdings) == 1
    assert set(holdings["source_file_type"]) == {"holdings"}

def test_raw_file_mtime_unchanged_by_import(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    path = raw / "종합거래내역 상세.xlsx"
    pd.DataFrame([
        {"실거래일자": "2026-04-29", "거래유형": "매수", "상세내용": "코스피매수", "종목명": "삼성전자 005930", "수량": "1", "거래금액": "70000"},
    ]).to_excel(path, index=False)
    before = snapshot_raw_files(raw)
    import_raw_dir(vault)
    after = snapshot_raw_files(raw)
    assert changed_entries(before, after) == []

def test_deduplicate_overlapping_transaction_rows(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    df = pd.DataFrame([
        {"거래일자": "2026-04-29", "거래유형": "매수", "종목코드": "5930", "종목명": "삼성전자", "수량": "1", "단가": "70000", "거래금액": "70000"},
        {"거래일자": "2026-04-29", "거래유형": "매수", "종목코드": "5930", "종목명": "삼성전자", "수량": "1", "단가": "70000", "거래금액": "70000"},
    ])
    path = raw / "sample.xlsx"
    df.to_excel(path, index=False)
    summary = import_raw_dir(vault)
    out = pd.read_csv(vault / "70_Imports" / "processed" / "processed_transactions.csv", dtype={"ticker": str})
    assert summary.duplicate_rows_removed == 1
    assert len(out) == 1

def test_generate_source_file_index(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([{"거래일자": "2026-04-29", "거래유형": "입금", "거래금액": "1000"}]).to_excel(raw / "cash.xlsx", index=False)
    import_raw_dir(vault)
    idx = pd.read_csv(vault / "70_Imports" / "processed" / "source_file_index.csv")
    assert len(idx) == 1
    assert idx["source_file"].iloc[0].startswith("source_")
    assert "snapshot_date" in idx.columns
    assert str(idx["snapshot_date"].fillna("").iloc[0]) == ""

def test_handle_xls_html_table_fallback(tmp_path: Path):
    html = """<html><body><table><tr><th>거래일자</th><th>거래유형</th><th>종목코드</th><th>종목명</th><th>수량</th><th>단가</th></tr><tr><td>2026.04.29</td><td>매수</td><td>5930</td><td>삼성전자</td><td>1</td><td>70000</td></tr></table></body></html>"""
    path = tmp_path / "sample.xls"
    path.write_text(html, encoding="utf-8")
    tables = load_workbook_tables(path)
    assert tables
    normalized, _, _ = normalize_dataframe(next(iter(tables.values())), path, "table_0")
    assert normalized["ticker"].iloc[0] == "005930"
