import argparse
from datetime import date, datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from types import SimpleNamespace
import uuid

import pandas as pd
import pytest

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON,
    COLUMN_ALIASES,
    MULTIINDEX_COLUMN_SEPARATOR,
    OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON,
    canonical_overseas_position_key,
    dedupe_holdings,
    extract_symbol_from_parentheses,
    import_raw_dir,
    infer_asset_type,
    infer_market,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_cash_currency,
    normalize_currency_and_fx_rate,
    normalize_dataframe,
    normalize_date,
    normalize_amount_fields,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from migrate_autogenerated_markers import resolve_company_note
import main as pipeline_main
from main import LIVE_WRITE_CONFIRMATION_TOKEN, build_parser, is_live_vault_path, live_write_guard_findings
from obsidian_writer import AUTO_END, AUTO_START, bootstrap_autogenerated_block, dashboard_content, qa_exception_cards, qa_exception_rollup_summary, replace_autogenerated_block, write_company_notes
from portfolio_model import apply_expense_fx_rates, apply_holdings_snapshot_asof_register, apply_holdings_snapshot_asof_register_to_source_index, apply_income_fx_rates, build_fx_rate_requirements, build_income_summary, build_monthly_cashflow_summary, build_performance_history, build_performance_summary, build_portfolio, build_portfolio_outputs, generate_reports, has_filled_section, load_fx_rates, resolve_fx_rate
from qa_checker import QA_EXCEPTION_ROLLUP_COLUMNS, REC_EX_01_ISSUE, REC_EX_01_SUGGESTED_FIX, build_qa_exception_rollup, run_qa
from quality_gate import (
    audit_output_schema_findings,
    audit_representation_findings,
    changed_entries,
    company_note_currency_findings,
    company_note_duplicate_findings,
    duplicate_overseas_holding_findings,
    expense_contract_findings,
    fx_internal_transfer_findings,
    fx_event_contract_findings,
    income_contract_findings,
    income_expense_separation_findings,
    income_reversal_review_findings,
    income_summary_contract_findings,
    invalid_currency_findings,
    live_vault_actual_write_guard_findings,
    non_krw_amount_without_fx_findings,
    dashboard_return_label_findings,
    official_krw_total_provenance_findings,
    principal_unit_misuse_findings,
    processed_cashflows_contract_findings,
    processed_output_schema_findings,
    performance_summary_findings,
    realized_pnl_cost_basis_findings,
    realized_pnl_review_findings,
    reconciliation_summary_findings,
    scan_generated_markdown_sensitive,
    snapshot_raw_files,
    unit_classification_findings,
)

from support import (
    AMOUNT_UNIT_AUDIT_COLUMNS,
    EXPENSE_OUTPUT_COLUMNS,
    FX_EVENT_COLUMNS,
    FX_RATE_REQUIREMENT_COLUMNS,
    INCOME_OUTPUT_COLUMNS,
    INCOME_SUMMARY_OUTPUT_COLUMNS,
    MONTHLY_CASHFLOW_SUMMARY_COLUMNS,
    PERFORMANCE_HISTORY_COLUMNS,
    PERFORMANCE_SUMMARY_METRICS,
    REALIZED_PNL_OUTPUT_COLUMNS,
    UNIT_MISMATCH_AUDIT_COLUMNS,
    assert_columns_present,
    fx_gate_row,
    is_blank_or_na,
    read_processed_csv,
    reconciliation_metrics,
    synthetic_rec_ex_01_rollup_rows,
    valid_performance_summary_rows,
    valid_reconciliation_summary_rows,
    write_stage8_output_inputs,
)


def test_build_income_summary_preserves_native_and_sums_only_ok_krw_rows():
    income = pd.DataFrame([
        {"income_type": "dividend", "currency_native": "USD", "amount_native": 10, "amount_krw": 14000, "tax_native": 1, "tax_krw": 1400, "amount_review_status": "ok"},
        {"income_type": "dividend", "currency_native": "USD", "amount_native": 5, "amount_krw": "", "tax_native": 0.5, "tax_krw": "", "amount_review_status": "fx_missing"},
        {"income_type": "interest", "currency_native": "KRW", "amount_native": 1000, "amount_krw": 1000, "tax_native": 100, "tax_krw": 100, "amount_review_status": "ok"},
        {"income_type": "distribution", "currency_native": "KRW", "amount_native": 2000, "amount_krw": 2000, "tax_native": 0, "tax_krw": 0, "amount_review_status": "needs_review"},
    ])

    summary = build_income_summary(income)
    summary_by_key = summary.set_index(["income_type", "currency_native"])

    assert_columns_present(summary, INCOME_SUMMARY_OUTPUT_COLUMNS)
    dividend = summary_by_key.loc[("dividend", "USD")]
    assert float(dividend["amount_native_sum"]) == 15
    assert float(dividend["amount_krw_sum"]) == 14000
    assert float(dividend["tax_native_sum"]) == 1.5
    assert float(dividend["tax_krw_sum"]) == 1400
    assert float(dividend["net_income_native"]) == 13.5
    assert float(dividend["net_income_krw"]) == 12600
    assert int(dividend["row_count"]) == 2
    assert int(dividend["fx_missing_row_count"]) == 1
    assert int(dividend["amount_review_needed_row_count"]) == 1
    assert dividend["income_status"] == "fx_missing"

    interest = summary_by_key.loc[("interest", "KRW")]
    assert float(interest["net_income_krw"]) == 900
    distribution = summary_by_key.loc[("distribution", "KRW")]
    assert is_blank_or_na(distribution["amount_krw_sum"])
    assert distribution["income_status"] == "needs_review"

def test_apply_income_fx_rates_converts_usd_dividend_from_local_fx_rates(tmp_path: Path):
    import_root = tmp_path / "70_Imports"
    processed = import_root / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([{
        "effective_date": "2026-01-10",
        "base_currency": "USD",
        "quote_currency": "KRW",
        "rate": "1500",
        "source_type": "local",
        "provider": "manual",
        "use_case": "dividend",
        "status": "approved",
        "source_note": "archived broker statement check",
    }]).to_csv(import_root / "fx_rates.csv", index=False)
    income = pd.DataFrame([{
        "source_file_type": "transaction_history",
        "trade_date": "2026-01-10",
        "income_type": "dividend",
        "currency_native": "USD",
        "amount_native": 12.34,
        "amount_krw": "",
        "amount_krw_source": "",
        "tax_native": 0,
        "tax_krw": 0,
        "fx_rate_to_krw": "",
        "fx_rate_source": "",
        "amount_basis": "raw_native",
        "amount_confidence": "unavailable",
        "amount_review_status": "fx_missing",
        "amount_review_reason": "non-KRW native amount has no FX rate or broker-provided KRW amount",
    }])

    fx_rates = load_fx_rates(processed)
    converted = apply_income_fx_rates(income, fx_rates)
    row = converted.iloc[0]

    assert row["amount_native"] == 12.34
    assert row["amount_krw"] == pytest.approx(18510)
    assert row["amount_krw_source"] == "local_fx_rates"
    assert row["fx_rate_to_krw"] == 1500
    assert row["fx_rate_source"] == "local_fx_rates"
    assert row["amount_review_status"] == "ok"

    summary = build_income_summary(converted)
    dividend = summary.iloc[0]
    assert dividend["amount_krw_sum"] == pytest.approx(18510)
    assert dividend["fx_missing_row_count"] == 0
    assert "local_fx_rates: 1" in dividend["fx_source_summary"]

def test_apply_income_fx_rates_missing_keeps_fx_missing_and_builds_requirement():
    income = pd.DataFrame([{
        "source_file_type": "transaction_history",
        "trade_date": "2026-01-10",
        "income_type": "dividend",
        "currency_native": "USD",
        "amount_native": 12.34,
        "amount_krw": "",
        "amount_krw_source": "",
        "tax_native": 0,
        "tax_krw": 0,
        "fx_rate_to_krw": "",
        "fx_rate_source": "",
        "amount_review_status": "fx_missing",
        "amount_review_reason": "non-KRW native amount has no FX rate or broker-provided KRW amount",
    }])

    converted = apply_income_fx_rates(income, pd.DataFrame())
    requirements = build_fx_rate_requirements(converted)

    assert is_blank_or_na(converted.iloc[0]["amount_krw"])
    assert converted.iloc[0]["amount_review_status"] == "fx_missing"
    assert_columns_present(requirements, FX_RATE_REQUIREMENT_COLUMNS)
    assert len(requirements) == 1
    assert requirements.iloc[0]["event_date"] == "2026-01-10"
    assert requirements.iloc[0]["currency"] == "USD"
    assert requirements.iloc[0]["use_case"] == "income_dividend"
    assert requirements.iloc[0]["amount_native_sum"] == pytest.approx(12.34)

def test_apply_expense_fx_rates_converts_usd_tax_and_removes_requirement():
    expenses = pd.DataFrame([{
        "source_file": "",
        "source_file_type": "transaction_history",
        "account_type": "overseas",
        "market": "US",
        "trade_date": "2026-01-10",
        "ticker": "",
        "security_name": "",
        "expense_type": "tax",
        "currency_native": "USD",
        "amount_native": 1.25,
        "amount_krw": "",
        "fx_rate_to_krw": "",
        "fx_rate_source": "",
        "amount_kind": "tax",
        "amount_basis": "raw_native",
        "amount_confidence": "unavailable",
        "amount_review_status": "fx_missing",
        "amount_review_reason": "non-KRW expense has no same-date archived FX rate",
        "affects_principal": False,
        "affects_profit": True,
        "raw_memo": "",
    }], columns=EXPENSE_OUTPUT_COLUMNS)
    fx_rates = pd.DataFrame([{
        "effective_date": "2026-01-10",
        "base_currency": "USD",
        "quote_currency": "KRW",
        "rate": "1500",
        "source_type": "api_archive",
        "provider": "eximbank",
        "use_case": "expense_tax",
        "status": "available",
        "source_note": "official same-date archived FX evidence",
    }])

    converted = apply_expense_fx_rates(expenses, fx_rates)
    requirements = build_fx_rate_requirements(pd.DataFrame(), expenses=converted)
    row = converted.iloc[0]

    assert row["amount_krw"] == pytest.approx(1875)
    assert row["fx_rate_to_krw"] == 1500
    assert row["fx_rate_source"] == "api_cached_fx_rates"
    assert row["amount_basis"] == "derived_krw_from_fx"
    assert row["amount_confidence"] == "derived"
    assert row["amount_review_status"] == "ok"
    assert requirements.empty

def test_fx_requirement_summary_distinguishes_requirement_rows_from_affected_rows():
    income = pd.DataFrame([
        {
            "source_file_type": "transaction_history",
            "trade_date": "2026-01-10",
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native": 1.0,
            "amount_krw": "",
            "amount_krw_source": "",
            "tax_native": 0,
            "tax_krw": 0,
            "fx_rate_to_krw": "",
            "fx_rate_source": "",
            "amount_review_status": "fx_missing",
            "amount_review_reason": "same-date FX provenance required",
        },
        {
            "source_file_type": "transaction_history",
            "trade_date": "2026-01-10",
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native": 2.0,
            "amount_krw": "",
            "amount_krw_source": "",
            "tax_native": 0,
            "tax_krw": 0,
            "fx_rate_to_krw": "",
            "fx_rate_source": "",
            "amount_review_status": "fx_missing",
            "amount_review_reason": "same-date FX provenance required",
        },
    ])

    requirements = build_fx_rate_requirements(income)

    assert len(requirements) == 1
    assert int(requirements.iloc[0]["row_count"]) == 2
    assert requirements.iloc[0]["amount_native_sum"] == pytest.approx(3.0)

def test_resolve_fx_rate_non_krw_zero_native_uses_raw_native_without_fx():
    row = pd.Series({
        "trade_date": "2026-01-10",
        "currency_native": "USD",
        "amount_native": 0,
        "amount_krw": "",
        "amount_krw_source": "",
        "fx_rate_to_krw": "",
        "fx_rate_source": "",
    })

    resolved = resolve_fx_rate(row, pd.DataFrame(), "income_dividend")

    assert resolved["status"] == "ok"
    assert resolved["fx_status"] == "not_required"
    assert resolved["amount_krw"] == 0.0
    assert resolved["amount_krw_source"] == "raw_native"
    assert resolved["fx_rate_source"] == "not_required"
    assert resolved["source_type"] == "not_required"

def test_income_summary_contract_uses_raw_native_for_non_krw_zero_native():
    income = pd.DataFrame([
        {
            "source_file_type": "transaction_history",
            "trade_date": "2026-01-10",
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native": 0,
            "amount_krw": "",
            "amount_krw_source": "",
            "tax_native": 0,
            "tax_krw": 0,
            "fx_rate_to_krw": "",
            "fx_rate_source": "",
            "amount_review_status": "ok",
        },
        {
            "source_file_type": "transaction_history",
            "trade_date": "2026-01-11",
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native": 1,
            "amount_krw": "",
            "amount_krw_source": "",
            "tax_native": 0,
            "tax_krw": 0,
            "fx_rate_to_krw": "",
            "fx_rate_source": "",
            "amount_review_status": "fx_missing",
        },
    ])

    converted = apply_income_fx_rates(income, pd.DataFrame())
    summary = build_income_summary(converted)

    assert "raw_native: 1" in summary.iloc[0]["fx_source_summary"]
    assert "zero_native" not in summary.iloc[0]["fx_source_summary"]
    assert income_summary_contract_findings(
        summary.astype(str).to_dict("records"),
        converted.astype(str).to_dict("records"),
    ) == []

def test_resolve_fx_rate_prefers_broker_krw_amount_over_raw_and_local_fx():
    row = pd.Series({
        "trade_date": "2026-01-10",
        "currency_native": "USD",
        "amount_native": 10,
        "amount_krw": 14000,
        "amount_krw_source": "broker_krw_amount",
        "fx_rate_to_krw": 1300,
        "fx_rate_source": "raw",
    })
    fx_rates = pd.DataFrame([{
        "effective_date": "2026-01-10",
        "base_currency": "USD",
        "quote_currency": "KRW",
        "rate": 1500,
        "source_type": "local",
        "provider": "manual",
        "use_case": "dividend",
        "status": "approved",
        "source_note": "",
    }])

    resolved = resolve_fx_rate(row, fx_rates, "income_dividend")

    assert resolved["status"] == "ok"
    assert resolved["amount_krw"] == 14000
    assert resolved["amount_krw_source"] == "broker_krw_amount"

def test_resolve_fx_rate_does_not_apply_current_rate_to_historical_row():
    row = pd.Series({
        "trade_date": "2026-01-10",
        "currency_native": "USD",
        "amount_native": 10,
        "amount_krw": "",
        "amount_krw_source": "",
        "fx_rate_to_krw": "",
        "fx_rate_source": "",
    })
    fx_rates = pd.DataFrame([{
        "effective_date": "2026-05-24",
        "base_currency": "USD",
        "quote_currency": "KRW",
        "rate": 1500,
        "source_type": "api_cached",
        "provider": "cached-provider",
        "use_case": "dividend",
        "status": "cached",
        "source_note": "current cached rate, not historical event date",
    }])

    resolved = resolve_fx_rate(row, fx_rates, "income_dividend")

    assert resolved["status"] == "fx_missing"
    assert "same-date" in resolved["missing_reason"]

def test_calculate_weight_pct(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"ticker": "A", "security_name": "A", "account_type": "종합", "market": "KR", "asset_type": "stock", "evaluation_amount": 85, "unrealized_pnl": 0, "pnl_pct": 0, "balance_quantity": 1},
        {"ticker": "B", "security_name": "B", "account_type": "종합", "market": "KR", "asset_type": "stock", "evaluation_amount": 15, "unrealized_pnl": 0, "pnl_pct": 0, "balance_quantity": 1},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    summary, holdings, _, _ = build_portfolio(processed, vault)
    assert round(float(holdings.loc[holdings["ticker"] == "A", "weight_pct"].iloc[0]), 0) == 85

def test_detect_pnl_pct_minus_ten(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    (vault / "20_Companies" / "A").mkdir(parents=True)
    (vault / "20_Companies" / "A" / "Company.md").write_text("---\ntype: company\nticker: A\nmarket: KR\n---\n# A\n", encoding="utf-8")
    pd.DataFrame([{"ticker": "A", "security_name": "A", "evaluation_amount": 100, "pnl_pct": -10.1, "balance_quantity": 1}]).to_csv(processed / "processed_holdings.csv", index=False)
    _, _, risk, review = build_portfolio(processed, vault)
    assert "LOSS_REVIEW_REQUIRED" in risk["risk_flags"].iloc[0]
    assert any(review["reason"].str.contains("-10%"))

def test_zero_weight_zero_quantity_goes_to_history_queue(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"ticker": "CURRENT", "security_name": "Current", "account_type": "종합", "evaluation_amount": 100, "pnl_pct": 0, "balance_quantity": 1},
        {"ticker": "PAST", "security_name": "Past", "account_type": "종합", "quantity": 99, "evaluation_amount": 0, "pnl_pct": 0, "balance_quantity": 0},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    assert set(holdings["ticker"]) == {"CURRENT"}
    assert "PAST" not in set(review.get("ticker", pd.Series(dtype=str)))
    assert set(history["ticker"]) == {"PAST"}

def test_transaction_only_past_ticker_goes_to_history_queue(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"ticker": "CURRENT", "security_name": "Current", "account_type": "종합", "evaluation_amount": 100, "pnl_pct": 0, "balance_quantity": 1},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame([
        {"ticker": "PAST", "security_name": "Past", "account_type": "종합", "trade_date": "2026-01-10", "transaction_type": "sell", "quantity": 99},
    ]).to_csv(processed / "processed_transactions.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    assert set(holdings["ticker"]) == {"CURRENT"}
    assert "PAST" not in set(review.get("ticker", pd.Series(dtype=str)))
    assert set(history["ticker"]) == {"PAST"}
    assert history["history_reason"].iloc[0] == "TRANSACTION_HISTORY_NO_CURRENT_POSITION"

def test_no_balance_files_keeps_portfolio_value_unknown(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_abc.xls", "source_file_type": "transaction_history", "account_type": "comprehensive"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"ticker": "A", "security_name": "A", "account_type": "comprehensive", "trade_date": "2026-04-29", "transaction_type": "buy", "quantity": 1, "trade_amount": 100},
    ]).to_csv(processed / "processed_transactions.csv", index=False)
    pd.DataFrame(columns=["ticker", "security_name", "balance_quantity", "evaluation_amount", "pnl_pct"]).to_csv(processed / "processed_holdings.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))
    assert holdings.empty
    assert str(summary_map["balance_data_available"]).lower() == "false"
    assert summary_map["total_portfolio_value_status"] == "unknown"
    assert summary_map["total_portfolio_value_basis"] == "unknown_no_balance_file"

def test_holdings_file_makes_portfolio_summary_available(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_balance.xls", "source_file_type": "holdings", "account_type": "ISA"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"ticker": "005930", "security_name": "Samsung", "account_type": "ISA", "market": "KR", "asset_type": "stock", "currency": "KRW", "balance_quantity": 2, "evaluation_amount": 100000, "unrealized_pnl": 1000, "pnl_pct": 1.0, "source_file_type": "holdings"},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["ticker"]).to_csv(processed / "processed_transactions.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))
    assert len(holdings) == 1
    assert summary_map["total_portfolio_value_status"] == "available"
    assert float(summary_map["total_portfolio_value"]) == 100000
    assert summary_map["currency_normalization_status"] == "pending"
    assert summary_map["amount_unit_classification_status"] == "pending"
    assert summary_map["profit_result_status"] == "preliminary"
    assert summary_map["reconciliation_status"] == "currency_normalization_pending"

def write_reconciliation_baseline(
    processed: Path,
    holdings_rows: list[dict[str, object]],
    transaction_rows: list[dict[str, object]] | None = None,
    cashflow_rows: list[dict[str, object]] | None = None,
    income_rows: list[dict[str, object]] | None = None,
    expense_rows: list[dict[str, object]] | None = None,
    fx_rows: list[dict[str, object]] | None = None,
) -> None:
    processed.mkdir(parents=True, exist_ok=True)
    source_rows = [
        {"source_file": "source_balance.csv", "source_file_type": "holdings", "account_type": "ISA"},
        {"source_file": "source_cashflow.csv", "source_file_type": "cashflow", "account_type": "ISA"},
    ]
    if transaction_rows is not None:
        source_rows.append({"source_file": "source_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA"})
    pd.DataFrame(source_rows).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame(holdings_rows).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(transaction_rows or [], columns=None).to_csv(processed / "processed_transactions.csv", index=False)
    pd.DataFrame(cashflow_rows or []).to_csv(processed / "processed_cashflows.csv", index=False)
    pd.DataFrame(income_rows or [], columns=INCOME_OUTPUT_COLUMNS).to_csv(processed / "processed_income.csv", index=False)
    pd.DataFrame(expense_rows or [], columns=EXPENSE_OUTPUT_COLUMNS).to_csv(processed / "processed_expenses.csv", index=False)
    pd.DataFrame(fx_rows or [], columns=FX_EVENT_COLUMNS).to_csv(processed / "processed_fx_events.csv", index=False)

def performance_metrics(processed: Path) -> dict[str, str]:
    df = pd.read_csv(processed / "performance_summary.csv", dtype=str)
    return dict(zip(df["metric"], df["value"].fillna("")))

def stage9_cash_holding(amount_krw: int | float) -> dict[str, object]:
    return {
        "ticker": "CASH_KRW",
        "security_name": "Synthetic KRW Cash",
        "account_type": "SYNTH",
        "market": "KR",
        "asset_type": "cash",
        "currency": "KRW",
        "currency_native": "KRW",
        "balance_quantity": 1,
        "evaluation_amount": amount_krw,
        "evaluation_amount_krw": amount_krw,
        "source_file_type": "holdings",
    }

def stage9_trade(
    import_id: str,
    ticker: str,
    transaction_type: str,
    amount_krw: int | float,
    *,
    quantity: int | float = 1,
    trade_date: str = "2026-01-01",
    security_name: str | None = None,
    market: str = "US",
    fee_krw: int | float = 0,
    tax_krw: int | float = 0,
) -> dict[str, object]:
    row: dict[str, object] = {
        "import_id": import_id,
        "source_file": "synthetic_stage9_transactions.csv",
        "source_file_type": "transaction_history",
        "account_type": "SYNTH",
        "market": market,
        "asset_type": "stock",
        "ticker": ticker,
        "security_name": security_name or f"{ticker} Synthetic",
        "trade_date": trade_date,
        "transaction_type": transaction_type,
        "quantity": quantity,
        "trade_amount_krw": amount_krw,
        "amount_krw": amount_krw,
        "currency_native": "KRW",
        "amount_review_status": "ok",
        "cashflow_role": "trade_settlement",
    }
    if fee_krw:
        row["fee_native"] = fee_krw
        row["fee_krw"] = fee_krw
    if tax_krw:
        row["tax_native"] = tax_krw
        row["tax_krw"] = tax_krw
    return row

def stage9_sold_position_rows() -> list[dict[str, object]]:
    return [
        stage9_trade("buy-tsla-loss", "TSLA", "buy", 10000, trade_date="2026-01-01"),
        stage9_trade("sell-tsla-loss", "TSLA", "sell", 7000, trade_date="2026-01-02"),
        stage9_trade("buy-tsll-gain", "TSLL", "buy", 2000, trade_date="2026-01-03"),
        stage9_trade("sell-tsll-gain", "TSLL", "sell", 2500, trade_date="2026-01-04"),
        stage9_trade("buy-rgtz-loss", "RGTZ", "buy", 3000, trade_date="2026-01-05", market="KR"),
        stage9_trade("sell-rgtz-loss", "RGTZ", "sell", 1500, trade_date="2026-01-06", market="KR"),
    ]

def test_stage9_loss_sales_do_not_change_principal_and_populate_realized_loss_metrics(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(96000)],
        transaction_rows=stage9_sold_position_rows(),
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 100000,
                "amount_krw": 100000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    reconciliation = reconciliation_metrics(processed)
    performance = performance_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    holdings = read_processed_csv(processed, "processed_holdings.csv")
    realized_by_ticker = realized.set_index("ticker")

    assert set(realized["ticker"]) == {"TSLA", "TSLL", "RGTZ"}
    assert set(realized["position_status"]) == {"closed"}
    assert set(realized["cost_basis_method"]) == {"fifo"}
    assert set(holdings["ticker"]) == {"CASH_KRW"}
    assert not {"TSLA", "TSLL", "RGTZ"}.intersection(set(holdings["ticker"]))

    assert float(realized_by_ticker.loc["TSLA", "realized_trade_pnl_gross_krw"]) == -3000
    assert realized_by_ticker.loc["TSLA", "realized_result"] == "loss"
    assert float(realized_by_ticker.loc["TSLL", "realized_trade_pnl_gross_krw"]) == 500
    assert realized_by_ticker.loc["TSLL", "realized_result"] == "gain"
    assert float(realized_by_ticker.loc["RGTZ", "realized_trade_pnl_gross_krw"]) == -1500
    assert realized_by_ticker.loc["RGTZ", "realized_result"] == "loss"

    assert float(reconciliation["net_external_principal_krw"]) == 100000
    assert float(performance["net_external_principal_krw"]) == 100000
    assert float(reconciliation["realized_trade_pnl_gross_krw"]) == -4000
    assert float(performance["realized_trade_pnl_gross_krw"]) == -4000
    assert float(performance["realized_gain_krw"]) == 500
    assert float(performance["realized_loss_krw"]) == -4500
    assert float(performance["realized_loss_abs_krw"]) == 4500
    assert float(performance["cumulative_return_krw"]) == -4000
    assert float(performance["explained_profit_krw"]) == -4000
    assert float(performance["reconciliation_residual_krw"]) == 0
    assert reconciliation["realized_cost_basis_method"] == "fifo"
    assert reconciliation["realized_pnl_status"] == "available"

    principles = (Path(__file__).resolve().parents[3] / "05_Principles" / "Portfolio_Return_Principal_Rules.md").read_text(encoding="utf-8")
    assert "FIFO cost-basis ledger" in principles

def test_stage9_income_summary_separates_dividend_interest_and_distribution(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(104200)],
        transaction_rows=[],
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 100000,
                "amount_krw": 100000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
        income_rows=[
            {"income_type": "dividend", "currency_native": "KRW", "amount_native": 3000, "amount_krw": 3000, "tax_native": 0, "tax_krw": 0, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"income_type": "interest", "currency_native": "KRW", "amount_native": 500, "amount_krw": 500, "tax_native": 0, "tax_krw": 0, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"income_type": "distribution", "currency_native": "KRW", "amount_native": 700, "amount_krw": 700, "tax_native": 0, "tax_krw": 0, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    income_summary = read_processed_csv(processed, "income_summary.csv")
    performance = performance_metrics(processed)
    summary_by_type = income_summary.set_index("income_type")

    assert set(income_summary["income_type"]) == {"dividend", "interest", "distribution"}
    assert float(summary_by_type.loc["dividend", "amount_krw_sum"]) == 3000
    assert float(summary_by_type.loc["interest", "amount_krw_sum"]) == 500
    assert float(summary_by_type.loc["distribution", "amount_krw_sum"]) == 700
    assert set(income_summary["income_status"]) == {"available"}
    assert float(performance["dividend_income_krw"]) == 3000
    assert float(performance["interest_income_krw"]) == 500
    assert float(performance["distribution_income_krw"]) == 700
    assert float(performance["income_total_krw"]) == 4200

def test_generate_reports_applies_fx_rates_to_usd_dividend_and_preserves_native_values(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(120000)],
        transaction_rows=[],
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 100000,
                "amount_krw": 100000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
        income_rows=[
            {
                "source_file_type": "transaction_history",
                "trade_date": "2026-01-10",
                "income_type": "dividend",
                "currency_native": "USD",
                "amount_native": 12.34,
                "amount_krw": "",
                "amount_krw_source": "",
                "tax_native": 0,
                "tax_krw": 0,
                "fx_rate_to_krw": "",
                "fx_rate_source": "",
                "amount_review_status": "fx_missing",
                "amount_review_reason": "non-KRW native amount has no FX rate or broker-provided KRW amount",
                "affects_principal": False,
                "affects_profit": True,
            },
        ],
    )
    pd.DataFrame([{
        "effective_date": "2026-01-10",
        "base_currency": "USD",
        "quote_currency": "KRW",
        "rate": 1500,
        "source_type": "local",
        "provider": "manual",
        "use_case": "income",
        "status": "approved",
        "source_note": "same-date archived manual rate",
    }]).to_csv(tmp_path / "70_Imports" / "fx_rates.csv", index=False)

    generate_reports(tmp_path, processed_dir=processed)

    income = read_processed_csv(processed, "processed_income.csv")
    income_summary = read_processed_csv(processed, "income_summary.csv")
    performance = performance_metrics(processed)
    requirements = read_processed_csv(processed, "fx_rate_requirements.csv")

    assert income.iloc[0]["amount_native"] == 12.34
    assert income.iloc[0]["amount_krw"] == pytest.approx(18510)
    assert income.iloc[0]["amount_krw_source"] == "local_fx_rates"
    assert income.iloc[0]["amount_review_status"] == "ok"
    assert income_summary.iloc[0]["amount_krw_sum"] == pytest.approx(18510)
    assert income_summary.iloc[0]["net_income_krw"] == pytest.approx(18510)
    assert income_summary.iloc[0]["income_status"] == "available"
    assert "local_fx_rates: 1" in income_summary.iloc[0]["fx_source_summary"]
    assert float(performance["dividend_income_krw"]) == pytest.approx(18510)
    assert float(performance["income_total_krw"]) == pytest.approx(18510)
    assert float(performance["income_fx_missing_row_count"]) == 0
    assert requirements.empty

def test_generate_reports_writes_fx_requirements_without_officializing_usd_realized_pnl(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    usd_trade_rows = [
        {
            "import_id": "buy-usd-aapl",
            "source_file": "synthetic_usd_transactions.csv",
            "source_file_type": "transaction_history",
            "account_type": "SYNTH",
            "market": "US",
            "asset_type": "stock",
            "ticker": "AAPL",
            "security_name": "Apple",
            "trade_date": "2026-01-10",
            "transaction_type": "buy",
            "quantity": 1,
            "trade_amount": 100,
            "trade_amount_native": 100,
            "amount_native": 100,
            "currency_native": "USD",
            "amount_review_status": "fx_missing",
            "amount_review_reason": "trade amount has no KRW-normalized value",
            "cashflow_role": "trade_settlement",
        },
        {
            "import_id": "sell-usd-aapl",
            "source_file": "synthetic_usd_transactions.csv",
            "source_file_type": "transaction_history",
            "account_type": "SYNTH",
            "market": "US",
            "asset_type": "stock",
            "ticker": "AAPL",
            "security_name": "Apple",
            "trade_date": "2026-01-11",
            "transaction_type": "sell",
            "quantity": 1,
            "trade_amount": 120,
            "trade_amount_native": 120,
            "amount_native": 120,
            "currency_native": "USD",
            "amount_review_status": "fx_missing",
            "amount_review_reason": "trade amount has no KRW-normalized value",
            "cashflow_role": "trade_settlement",
        },
    ]
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(100000)],
        transaction_rows=usd_trade_rows,
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 100000,
                "amount_krw": 100000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
        income_rows=[
            {
                "source_file_type": "transaction_history",
                "trade_date": "2026-01-10",
                "income_type": "dividend",
                "currency_native": "USD",
                "amount_native": 12.34,
                "amount_krw": "",
                "amount_krw_source": "",
                "tax_native": 0,
                "tax_krw": 0,
                "amount_review_status": "fx_missing",
                "amount_review_reason": "non-KRW native amount has no FX rate or broker-provided KRW amount",
                "affects_principal": False,
                "affects_profit": True,
            },
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)

    requirements = read_processed_csv(processed, "fx_rate_requirements.csv")
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    performance = performance_metrics(processed)

    assert_columns_present(requirements, FX_RATE_REQUIREMENT_COLUMNS)
    assert {"income_dividend", "realized_pnl_trade_settlement"}.issubset(set(requirements["use_case"]))
    assert set(requirements["status"]) == {"fx_missing"}
    assert set(realized["amount_review_status"]) == {"fx_missing"}
    assert set(realized["fx_status"]) == {"fx_missing"}
    assert all(is_blank_or_na(value) for value in realized["realized_trade_pnl_gross_krw"])
    assert performance["realized_pnl_status"] == "fx_missing"
    assert performance["fx_status"] == "fx_missing"
    assert float(performance["fx_rate_requirement_row_count"]) >= 2

def test_generate_reports_applies_cached_fx_rates_to_usd_realized_pnl(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(100000)],
        transaction_rows=[
            {
                "import_id": "buy-usd-synthetic",
                "source_file": "synthetic_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "SYN",
                "security_name": "Synthetic Equity",
                "trade_date": "2026-01-10",
                "transaction_type": "buy",
                "quantity": 1,
                "trade_amount": 100,
                "trade_amount_native": 100,
                "trade_amount_krw": 0,
                "amount_krw": 0,
                "currency_native": "USD",
                "amount_review_status": "fx_missing",
                "amount_review_reason": "trade amount has no KRW-normalized value",
                "cashflow_role": "trade_settlement",
            },
            {
                "import_id": "sell-usd-synthetic",
                "source_file": "synthetic_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "SYN",
                "security_name": "Synthetic Equity",
                "trade_date": "2026-01-11",
                "transaction_type": "sell",
                "quantity": 1,
                "trade_amount": 120,
                "trade_amount_native": 120,
                "trade_amount_krw": 0,
                "amount_krw": 0,
                "fee_native": 1,
                "tax_native": 2,
                "currency_native": "USD",
                "amount_review_status": "fx_missing",
                "amount_review_reason": "trade amount has no KRW-normalized value",
                "cashflow_role": "trade_settlement",
            },
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )
    fx_cache = tmp_path / "70_Imports" / "cache"
    fx_cache.mkdir(parents=True, exist_ok=True)
    pd.DataFrame([
        {
            "effective_date": "2026-01-10",
            "base_currency": "USD",
            "quote_currency": "KRW",
            "rate": 1300,
            "source_type": "api_cached",
            "provider": "synthetic",
            "use_case": "realized_pnl_trade_settlement",
            "status": "available",
            "source_note": "synthetic same-date archived FX evidence",
        },
        {
            "effective_date": "2026-01-11",
            "base_currency": "USD",
            "quote_currency": "KRW",
            "rate": 1400,
            "source_type": "api_cached",
            "provider": "synthetic",
            "use_case": "realized_pnl_trade_settlement",
            "status": "available",
            "source_note": "synthetic same-date archived FX evidence",
        },
    ]).to_csv(fx_cache / "fx_rates.csv", index=False)

    generate_reports(tmp_path, processed_dir=processed)

    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    requirements = read_processed_csv(processed, "fx_rate_requirements.csv")
    metrics = reconciliation_metrics(processed)
    row = realized.iloc[0]

    assert requirements.empty
    assert row["amount_review_status"] == "ok"
    assert row["fx_status"] == "available"
    assert float(row["proceeds_krw"]) == pytest.approx(168000)
    assert float(row["cost_basis_krw"]) == pytest.approx(130000)
    assert float(row["fee_krw"]) == pytest.approx(1400)
    assert float(row["tax_krw"]) == pytest.approx(2800)
    assert float(row["realized_trade_pnl_gross_krw"]) == pytest.approx(38000)
    assert float(row["realized_trade_pnl_net_krw"]) == pytest.approx(33800)
    assert metrics["realized_pnl_status"] == "available"
    assert int(metrics["realized_pnl_unavailable_row_count"]) == 0

def test_generate_reports_does_not_forward_fill_realized_pnl_fx_rates(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(100000)],
        transaction_rows=[
            {
                "import_id": "buy-usd-synthetic",
                "source_file": "synthetic_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "SYN",
                "security_name": "Synthetic Equity",
                "trade_date": "2026-01-10",
                "transaction_type": "buy",
                "quantity": 1,
                "trade_amount": 100,
                "currency_native": "USD",
                "amount_review_status": "fx_missing",
                "cashflow_role": "trade_settlement",
            },
            {
                "import_id": "sell-usd-synthetic",
                "source_file": "synthetic_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "SYN",
                "security_name": "Synthetic Equity",
                "trade_date": "2026-01-11",
                "transaction_type": "sell",
                "quantity": 1,
                "trade_amount": 120,
                "currency_native": "USD",
                "amount_review_status": "fx_missing",
                "cashflow_role": "trade_settlement",
            },
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )
    fx_cache = tmp_path / "70_Imports" / "cache"
    fx_cache.mkdir(parents=True, exist_ok=True)
    pd.DataFrame([
        {
            "effective_date": "2026-01-10",
            "base_currency": "USD",
            "quote_currency": "KRW",
            "rate": 1300,
            "source_type": "api_cached",
            "provider": "synthetic",
            "use_case": "realized_pnl_trade_settlement",
            "status": "available",
            "source_note": "synthetic same-date archived FX evidence",
        },
    ]).to_csv(fx_cache / "fx_rates.csv", index=False)

    generate_reports(tmp_path, processed_dir=processed)

    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    requirements = read_processed_csv(processed, "fx_rate_requirements.csv")
    metrics = reconciliation_metrics(processed)

    assert set(realized["amount_review_status"]) == {"fx_missing"}
    assert set(realized["fx_status"]) == {"fx_missing"}
    assert is_blank_or_na(realized.iloc[0]["realized_trade_pnl_gross_krw"])
    assert metrics["realized_pnl_status"] == "fx_missing"
    assert set(requirements["use_case"]) == {"realized_pnl_trade_settlement"}
    assert int(requirements["row_count"].sum()) == 1

def test_generate_reports_builds_realized_fx_requirements_when_transaction_status_is_ok_but_krw_missing(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(100000)],
        transaction_rows=[
            {
                "import_id": "buy-usd-synthetic",
                "source_file": "synthetic_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "SYN",
                "security_name": "Synthetic Equity",
                "trade_date": "2026-01-10",
                "transaction_type": "buy",
                "quantity": 1,
                "trade_amount": 100,
                "currency_native": "USD",
                "amount_review_status": "ok",
                "cashflow_role": "trade_settlement",
            },
            {
                "import_id": "sell-usd-synthetic",
                "source_file": "synthetic_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "SYN",
                "security_name": "Synthetic Equity",
                "trade_date": "2026-01-11",
                "transaction_type": "sell",
                "quantity": 1,
                "trade_amount": 120,
                "currency_native": "USD",
                "amount_review_status": "ok",
                "cashflow_role": "trade_settlement",
            },
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)

    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    requirements = read_processed_csv(processed, "fx_rate_requirements.csv")

    assert set(realized["amount_review_status"]) == {"fx_missing"}
    assert set(realized["fx_status"]) == {"fx_missing"}
    assert set(requirements["use_case"]) == {"realized_pnl_trade_settlement"}
    assert int(requirements["row_count"].sum()) == 2

def test_stage9_fee_tax_are_separate_and_explained_profit_uses_gross_once(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(101820)],
        transaction_rows=[
            stage9_trade("buy-fee-tax-stage9", "FTX", "buy", 1000, trade_date="2026-01-01", market="KR"),
            stage9_trade(
                "sell-fee-tax-stage9",
                "FTX",
                "sell",
                3000,
                trade_date="2026-01-02",
                market="KR",
                fee_krw=120,
                tax_krw=60,
            ),
        ],
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 100000,
                "amount_krw": 100000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
        expense_rows=[
            {"expense_type": "fee", "currency_native": "KRW", "amount_native": 120, "amount_krw": 120, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"expense_type": "tax", "currency_native": "KRW", "amount_native": 60, "amount_krw": 60, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    reconciliation = reconciliation_metrics(processed)
    performance = performance_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    row = realized.iloc[0]

    assert float(row["realized_trade_pnl_gross_krw"]) == 2000
    assert float(row["realized_trade_pnl_net_krw"]) == 1820
    assert float(performance["fee_expense_krw"]) == 120
    assert float(performance["tax_expense_krw"]) == 60
    assert float(performance["explained_profit_krw"]) == 1820
    assert float(performance["explained_profit_krw"]) != 1640
    assert float(reconciliation["explained_profit_krw"]) == 1820
    assert float(reconciliation["residual_krw"]) == 0
    assert float(performance["reconciliation_residual_krw"]) == 0

def test_stage9_current_holdings_return_and_cumulative_return_stay_separately_labeled(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {
                "ticker": "CURR",
                "security_name": "Current Holding Synthetic",
                "account_type": "SYNTH",
                "market": "KR",
                "asset_type": "stock",
                "currency": "KRW",
                "currency_native": "KRW",
                "balance_quantity": 1,
                "evaluation_amount": 100000,
                "evaluation_amount_krw": 100000,
                "unrealized_pnl": 1000,
                "unrealized_pnl_krw": 1000,
                "source_file_type": "holdings",
            },
        ],
        transaction_rows=[],
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 70000,
                "amount_krw": 70000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    portfolio_summary = read_processed_csv(processed, "portfolio_summary.csv")
    performance = performance_metrics(processed)
    content = dashboard_content("Portfolio.md", processed)
    holdings_return = float(portfolio_summary.loc[portfolio_summary["metric"].eq("pnl_pct"), "value"].iloc[0])
    cumulative_return_pct = float(performance["cumulative_return_pct"])

    assert holdings_return == round(1000 / 99000 * 100, 4)
    assert round(cumulative_return_pct, 6) == round(30000 / 70000 * 100, 6)
    assert round(holdings_return, 6) != round(cumulative_return_pct, 6)
    assert '<span class="stock-kpi-label">Return</span>' not in content
    assert "Portfolio Cost Basis" not in content
    assert "Total Return %" not in content

def test_stage9_transaction_history_only_does_not_create_current_holdings(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {
            "source_file": "synthetic_stage9_transactions.csv",
            "source_file_type": "transaction_history",
            "account_type": "SYNTH",
        },
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        stage9_trade("buy-history-only", "HIST", "buy", 1000, trade_date="2026-01-01", market="KR"),
        stage9_trade("sell-history-only", "HIST", "sell", 1500, trade_date="2026-01-02", market="KR"),
    ]).to_csv(processed / "processed_transactions.csv", index=False)
    pd.DataFrame(columns=["ticker", "security_name", "asset_type", "source_file_type", "balance_quantity", "evaluation_amount", "pnl_pct"]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["transaction_type", "cashflow_role", "amount_krw", "amount_review_status", "affects_principal"]).to_csv(processed / "processed_cashflows.csv", index=False)
    pd.DataFrame(columns=INCOME_OUTPUT_COLUMNS).to_csv(processed / "processed_income.csv", index=False)
    pd.DataFrame(columns=EXPENSE_OUTPUT_COLUMNS).to_csv(processed / "processed_expenses.csv", index=False)
    pd.DataFrame(columns=FX_EVENT_COLUMNS).to_csv(processed / "processed_fx_events.csv", index=False)

    result = generate_reports(tmp_path, processed_dir=processed)
    holdings = read_processed_csv(processed, "processed_holdings.csv")
    portfolio_summary = read_processed_csv(processed, "portfolio_summary.csv")
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    summary = dict(zip(portfolio_summary["metric"], portfolio_summary["value"].fillna("")))

    assert result["holding_rows"] == 0
    assert holdings.empty
    assert summary["holding_count"] == "0"
    assert summary["balance_data_available"] in {False, "False", "false"}
    assert set(realized["ticker"]) == {"HIST"}

def test_stage9_fx_missing_preserves_native_realized_amounts_and_blocks_official_krw(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[stage9_cash_holding(100000)],
        transaction_rows=[
            {
                "import_id": "buy-fx-stage9",
                "source_file": "synthetic_stage9_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "FXMISS",
                "security_name": "FX Missing Synthetic",
                "trade_date": "2026-01-01",
                "transaction_type": "buy",
                "quantity": 1,
                "trade_amount": 100,
                "currency_native": "USD",
                "amount_review_status": "fx_missing",
                "cashflow_role": "trade_settlement",
            },
            {
                "import_id": "sell-fx-stage9",
                "source_file": "synthetic_stage9_transactions.csv",
                "source_file_type": "transaction_history",
                "account_type": "SYNTH",
                "market": "US",
                "asset_type": "stock",
                "ticker": "FXMISS",
                "security_name": "FX Missing Synthetic",
                "trade_date": "2026-01-02",
                "transaction_type": "sell",
                "quantity": 1,
                "trade_amount": 120,
                "trade_amount_krw": 0,
                "currency_native": "USD",
                "amount_review_status": "fx_missing",
                "cashflow_role": "trade_settlement",
            },
        ],
        cashflow_rows=[
            {
                "transaction_type": "deposit",
                "cashflow_role": "external_principal",
                "settlement_amount_krw": 100000,
                "amount_krw": 100000,
                "amount_review_status": "ok",
                "affects_principal": True,
            },
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    reconciliation = reconciliation_metrics(processed)
    performance = performance_metrics(processed)
    row = realized.iloc[0]

    assert float(row["proceeds_native"]) == 120
    assert float(row["cost_basis_native"]) == 100
    assert float(row["realized_trade_pnl_gross_native"]) == 20
    assert is_blank_or_na(row["proceeds_krw"])
    assert is_blank_or_na(row["realized_trade_pnl_gross_krw"])
    assert row["amount_review_status"] == "fx_missing"
    assert row["fx_status"] == "fx_missing"
    assert reconciliation["realized_pnl_status"] == "fx_missing"
    assert reconciliation["explained_profit_status"] == "fx_missing"
    assert performance["realized_pnl_status"] == "fx_missing"
    assert performance["performance_status"] == "fx_missing"
    assert performance["explained_profit_krw"] == ""

def test_stage9_markdown_update_preserves_user_content_outside_auto_generated(tmp_path: Path):
    note = tmp_path / "10_Dashboard" / "Portfolio.md"
    note.parent.mkdir(parents=True)
    before = "# Portfolio\n\nmanual before\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n\nmanual after\n"
    note.write_text(before, encoding="utf-8")

    ok, _ = replace_autogenerated_block(note, "new generated dashboard")
    text = note.read_text(encoding="utf-8")

    assert ok
    assert "new generated dashboard" in text
    assert "manual before" in text
    assert "manual after" in text
    assert "old" not in text

def test_reconciliation_total_return_available_with_krw_assets_and_principal(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {
                "ticker": "005930",
                "security_name": "Samsung",
                "account_type": "ISA",
                "market": "KR",
                "asset_type": "stock",
                "currency": "KRW",
                "currency_native": "KRW",
                "balance_quantity": 2,
                "evaluation_amount": 100000,
                "evaluation_amount_krw": 100000,
                "unrealized_pnl": 1000,
                "unrealized_pnl_krw": 1000,
                "source_file_type": "holdings",
            },
        ],
        cashflow_rows=[
            {"trade_date": "2026-01-01", "transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 80000, "amount_krw": 80000, "amount_review_status": "ok", "affects_principal": True},
            {"trade_date": "2026-01-02", "transaction_type": "withdrawal", "cashflow_role": "external_principal", "settlement_amount_krw": 10000, "amount_krw": 10000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)

    assert float(metrics["total_assets_krw"]) == 100000
    assert metrics["total_assets_status"] == "available"
    assert float(metrics["external_deposit_krw"]) == 80000
    assert float(metrics["external_withdrawal_krw"]) == 10000
    assert float(metrics["net_external_principal_krw"]) == 70000
    assert metrics["net_external_principal_status"] == "available"
    assert metrics["reconciliation_summary_role"] == "audit_status_residual"
    assert metrics["total_return_alias_of"] == "performance_summary.cumulative_return_krw"
    assert metrics["total_return_pct_alias_of"] == "performance_summary.cumulative_return_pct"
    assert float(metrics["total_return_krw"]) == 30000
    assert metrics["total_return_status"] == "available"
    assert float(metrics["unrealized_pnl_krw"]) == 1000

def test_performance_summary_calculates_whole_investment_return_separate_from_holdings_return(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {
                "ticker": "005930",
                "security_name": "Samsung",
                "account_type": "ISA",
                "market": "KR",
                "asset_type": "stock",
                "currency": "KRW",
                "currency_native": "KRW",
                "balance_quantity": 2,
                "evaluation_amount": 100000,
                "evaluation_amount_krw": 100000,
                "unrealized_pnl": 1000,
                "unrealized_pnl_krw": 1000,
                "pnl_pct": 1,
                "source_file_type": "holdings",
            },
        ],
        cashflow_rows=[
            {"trade_date": "2026-01-01", "transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 80000, "amount_krw": 80000, "amount_review_status": "ok", "affects_principal": True},
            {"trade_date": "2026-01-02", "transaction_type": "withdrawal", "cashflow_role": "external_principal", "settlement_amount_krw": 10000, "amount_krw": 10000, "amount_review_status": "ok", "affects_principal": True},
        ],
        transaction_rows=[],
    )

    generate_reports(tmp_path, processed_dir=processed)
    summary = read_processed_csv(processed, "portfolio_summary.csv")
    reconciliation = reconciliation_metrics(processed)
    metrics = performance_metrics(processed)

    assert set(metrics) >= set(PERFORMANCE_SUMMARY_METRICS)
    assert float(metrics["external_deposit_krw"]) == 80000
    assert float(metrics["external_withdrawal_krw"]) == 10000
    assert float(metrics["net_external_principal_krw"]) == 70000
    assert float(metrics["current_total_assets_krw"]) == 100000
    assert float(metrics["cumulative_return_krw"]) == 30000
    assert round(float(metrics["cumulative_return_pct"]), 6) == round(30000 / 70000 * 100, 6)
    assert float(metrics["unrealized_pnl_krw"]) == 1000
    assert float(metrics["income_total_krw"]) == 0
    assert metrics["performance_status"] == "available"
    assert metrics["realized_pnl_status"] == "available"
    assert metrics["income_status"] == "available"
    assert metrics["fx_status"] == "available"
    assert reconciliation["total_return_alias_of"] == "performance_summary.cumulative_return_krw"
    assert float(reconciliation["total_return_krw"]) == float(metrics["cumulative_return_krw"])
    assert float(reconciliation["total_return_pct"]) == float(metrics["cumulative_return_pct"])
    holdings_return = float(summary.loc[summary["metric"].eq("pnl_pct"), "value"].iloc[0])
    assert round(holdings_return, 4) == 1.0101
    assert round(holdings_return, 6) != round(float(metrics["cumulative_return_pct"]), 6)

def test_reconciliation_total_return_unavailable_when_usd_holding_lacks_fx(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {
                "ticker": "AAPL",
                "security_name": "Apple",
                "account_type": "overseas",
                "market": "US",
                "asset_type": "stock",
                "currency": "USD",
                "currency_native": "USD",
                "balance_quantity": 1,
                "evaluation_amount": 100,
                "evaluation_amount_krw": "",
                "amount_review_status": "fx_missing",
                "source_file_type": "overseas_balance",
            },
        ],
        cashflow_rows=[
            {"trade_date": "2026-01-01", "transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    performance = performance_metrics(processed)

    assert metrics["total_assets_krw"] == ""
    assert metrics["total_assets_status"] == "fx_missing"
    assert metrics["total_return_krw"] == ""
    assert metrics["total_return_status"] == "fx_missing"
    assert metrics["residual_krw"] == ""
    assert metrics["residual_status"] == "unavailable"
    assert int(metrics["fx_missing_row_count"]) >= 1
    assert performance["current_total_assets_krw"] == ""
    assert performance["current_cash_krw"] == ""
    assert performance["current_holding_assets_krw"] == ""
    assert performance["unrealized_pnl_krw"] == ""
    assert performance["cumulative_return_krw"] == ""
    assert performance["cumulative_return_pct"] == ""
    assert performance["performance_status"] == "fx_missing"
    assert performance["fx_status"] == "fx_missing"

def test_reconciliation_income_breakdown_does_not_change_net_principal(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "005930", "security_name": "Samsung", "account_type": "ISA", "market": "KR", "asset_type": "stock", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 120000, "evaluation_amount_krw": 120000, "unrealized_pnl_krw": 2000, "source_file_type": "holdings"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
        transaction_rows=[],
        income_rows=[
            {"income_type": "dividend", "currency_native": "KRW", "amount_native": 3000, "amount_krw": 3000, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"income_type": "interest", "currency_native": "KRW", "amount_native": 500, "amount_krw": 500, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"income_type": "distribution", "currency_native": "KRW", "amount_native": 700, "amount_krw": 700, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
        ],
        expense_rows=[
            {"expense_type": "fee", "currency_native": "KRW", "amount_native": 100, "amount_krw": 100, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"expense_type": "tax", "currency_native": "KRW", "amount_native": 200, "amount_krw": 200, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    income_summary = read_processed_csv(processed, "income_summary.csv")
    income_summary_by_type = income_summary.set_index("income_type")

    assert float(metrics["net_external_principal_krw"]) == 100000
    assert float(metrics["dividend_income_krw"]) == 3000
    assert float(metrics["interest_income_krw"]) == 500
    assert float(metrics["distribution_income_krw"]) == 700
    assert float(metrics["fee_expense_krw"]) == 100
    assert float(metrics["tax_expense_krw"]) == 200
    assert float(metrics["explained_profit_krw"]) == 5900
    assert_columns_present(income_summary, INCOME_SUMMARY_OUTPUT_COLUMNS)
    assert set(income_summary["income_type"]) == {"dividend", "interest", "distribution"}
    assert float(income_summary_by_type.loc["dividend", "amount_krw_sum"]) == 3000
    assert float(income_summary_by_type.loc["interest", "net_income_krw"]) == 500
    assert float(income_summary_by_type.loc["distribution", "net_income_krw"]) == 700

def test_performance_summary_reflects_income_fx_missing_without_treating_missing_krw_as_zero(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "CASH_KRW", "security_name": "KRW Cash", "account_type": "ISA", "market": "KR", "asset_type": "cash", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 100000, "evaluation_amount_krw": 100000, "source_file_type": "holdings"},
        ],
        transaction_rows=[],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
        income_rows=[
            {"income_type": "dividend", "currency_native": "USD", "amount_native": 12.34, "amount_krw": "", "tax_native": 1.0, "tax_krw": "", "amount_review_status": "fx_missing", "affects_principal": False, "affects_profit": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    income_summary = read_processed_csv(processed, "income_summary.csv")
    reconciliation = reconciliation_metrics(processed)
    performance = performance_metrics(processed)
    row = income_summary.iloc[0]

    assert float(row["amount_native_sum"]) == 12.34
    assert is_blank_or_na(row["amount_krw_sum"])
    assert row["income_status"] == "fx_missing"
    assert reconciliation["explained_profit_krw"] == ""
    assert reconciliation["explained_profit_status"] == "fx_missing"
    assert reconciliation["residual_krw"] == ""
    assert reconciliation["residual_status"] == "unavailable"
    assert performance["dividend_income_krw"] == ""
    assert performance["income_total_krw"] == ""
    assert performance["explained_profit_krw"] == ""
    assert performance["income_status"] == "fx_missing"
    assert performance["performance_status"] == "fx_missing"

def test_fifo_realized_pnl_ledger_handles_closed_positions_without_recreating_holdings(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "CASH_KRW", "security_name": "KRW Cash", "account_type": "ISA", "market": "KR", "asset_type": "cash", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 102000, "evaluation_amount_krw": 102000, "source_file_type": "holdings"},
        ],
        transaction_rows=[
            {"import_id": "buy-tsla-1", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "US", "asset_type": "stock", "ticker": "TSLA", "security_name": "Tesla", "trade_date": "2026-01-01", "transaction_type": "buy", "quantity": 5, "trade_amount_krw": 4000, "amount_krw": 4000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "buy-tsla-2", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "US", "asset_type": "stock", "ticker": "TSLA", "security_name": "Tesla", "trade_date": "2026-01-02", "transaction_type": "buy", "quantity": 5, "trade_amount_krw": 5000, "amount_krw": 5000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-tsla", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "US", "asset_type": "stock", "ticker": "TSLA", "security_name": "Tesla", "trade_date": "2026-01-03", "transaction_type": "sell", "quantity": 10, "trade_amount_krw": 13000, "amount_krw": 13000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "buy-rgtz", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "RGTZ", "security_name": "RGTZ", "trade_date": "2026-01-04", "transaction_type": "buy", "quantity": 5, "trade_amount_krw": 10000, "amount_krw": 10000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-rgtz", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "RGTZ", "security_name": "RGTZ", "trade_date": "2026-01-05", "transaction_type": "sell", "quantity": 5, "trade_amount_krw": 8000, "amount_krw": 8000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    holdings = read_processed_csv(processed, "processed_holdings.csv")

    assert_columns_present(realized, REALIZED_PNL_OUTPUT_COLUMNS)
    assert set(realized["ticker"]) == {"TSLA", "RGTZ"}
    assert set(realized["cost_basis_method"]) == {"fifo"}
    assert set(realized["position_status"]) == {"closed"}
    assert set(holdings["ticker"]) == {"CASH_KRW"}
    assert float(metrics["current_cash_krw"]) == 102000
    assert float(metrics["current_holding_assets_krw"]) == 0
    assert float(metrics["realized_pnl_krw"]) == 2000
    assert float(metrics["realized_trade_pnl_gross_krw"]) == 2000
    assert float(metrics["realized_trade_pnl_net_krw"]) == 2000
    assert float(metrics["realized_gain_krw"]) == 4000
    assert float(metrics["realized_loss_krw"]) == -2000
    assert metrics["realized_cost_basis_method"] == "fifo"
    assert metrics["realized_pnl_basis"] == "gross_trade_pnl_krw_fee_tax_separate"
    assert metrics["realized_pnl_status"] == "available"
    assert int(metrics["realized_closed_position_count"]) == 2
    assert float(metrics["total_return_krw"]) == 2000
    assert float(metrics["total_return_pct"]) == 2
    assert float(metrics["explained_profit_krw"]) == 2000
    assert float(metrics["residual_krw"]) == 0

def test_realized_pnl_uses_gross_with_fee_tax_separate_to_prevent_double_count(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "CASH_KRW", "security_name": "KRW Cash", "account_type": "ISA", "market": "KR", "asset_type": "cash", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 101820, "evaluation_amount_krw": 101820, "source_file_type": "holdings"},
        ],
        transaction_rows=[
            {"import_id": "buy-fee-tax", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "FEE", "security_name": "Fee Tax Test", "trade_date": "2026-01-01", "transaction_type": "buy", "quantity": 1, "trade_amount_krw": 1000, "amount_krw": 1000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-fee-tax", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "FEE", "security_name": "Fee Tax Test", "trade_date": "2026-01-02", "transaction_type": "sell", "quantity": 1, "trade_amount_krw": 3000, "amount_krw": 3000, "fee_native": 120, "fee_krw": 120, "tax_native": 60, "tax_krw": 60, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
        expense_rows=[
            {"expense_type": "fee", "currency_native": "KRW", "amount_native": 120, "amount_krw": 120, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
            {"expense_type": "tax", "currency_native": "KRW", "amount_native": 60, "amount_krw": 60, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    performance = performance_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    row = realized.iloc[0]

    assert float(row["realized_trade_pnl_gross_krw"]) == 2000
    assert float(row["realized_trade_pnl_net_krw"]) == 1820
    assert float(metrics["realized_pnl_krw"]) == 2000
    assert float(metrics["realized_trade_pnl_gross_krw"]) == 2000
    assert float(metrics["realized_trade_pnl_net_krw"]) == 1820
    assert metrics["realized_pnl_basis"] == "gross_trade_pnl_krw_fee_tax_separate"
    assert float(metrics["fee_expense_krw"]) == 120
    assert float(metrics["tax_expense_krw"]) == 60
    assert float(metrics["total_return_krw"]) == 1820
    assert float(metrics["explained_profit_krw"]) == 1820
    assert float(metrics["residual_krw"]) == 0
    assert float(performance["realized_trade_pnl_gross_krw"]) == 2000
    assert float(performance["realized_trade_pnl_net_krw"]) == 1820
    assert float(performance["fee_expense_krw"]) == 120
    assert float(performance["tax_expense_krw"]) == 60
    assert float(performance["explained_profit_krw"]) == 1820
    assert float(performance["reconciliation_residual_krw"]) == 0

def test_fifo_realized_pnl_consumes_oldest_lot_before_later_lot(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "CASH_KRW", "security_name": "KRW Cash", "account_type": "ISA", "market": "KR", "asset_type": "cash", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 100500, "evaluation_amount_krw": 100500, "source_file_type": "holdings"},
        ],
        transaction_rows=[
            {"import_id": "buy-oldest", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "FIFO", "security_name": "FIFO Test", "trade_date": "2026-01-01", "transaction_type": "buy", "quantity": 1, "trade_amount_krw": 1000, "amount_krw": 1000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "buy-later", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "FIFO", "security_name": "FIFO Test", "trade_date": "2026-01-02", "transaction_type": "buy", "quantity": 1, "trade_amount_krw": 3000, "amount_krw": 3000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-first", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "FIFO", "security_name": "FIFO Test", "trade_date": "2026-01-03", "transaction_type": "sell", "quantity": 1, "trade_amount_krw": 2500, "amount_krw": 2500, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-second", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "FIFO", "security_name": "FIFO Test", "trade_date": "2026-01-04", "transaction_type": "sell", "quantity": 1, "trade_amount_krw": 2000, "amount_krw": 2000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    realized_by_sell = realized.set_index("sell_import_id")
    holdings = read_processed_csv(processed, "processed_holdings.csv")

    assert set(realized["cost_basis_method"]) == {"fifo"}
    assert float(realized_by_sell.loc["sell-first", "cost_basis_krw"]) == 1000
    assert float(realized_by_sell.loc["sell-first", "realized_trade_pnl_gross_krw"]) == 1500
    assert float(realized_by_sell.loc["sell-first", "realized_trade_pnl_net_krw"]) == 1500
    assert float(realized_by_sell.loc["sell-second", "cost_basis_krw"]) == 3000
    assert float(realized_by_sell.loc["sell-second", "realized_trade_pnl_gross_krw"]) == -1000
    assert float(realized_by_sell.loc["sell-second", "realized_trade_pnl_net_krw"]) == -1000
    assert set(realized["position_status"]) == {"closed"}
    assert set(holdings["ticker"]) == {"CASH_KRW"}
    assert metrics["realized_cost_basis_method"] == "fifo"
    assert float(metrics["realized_pnl_krw"]) == 500
    assert float(metrics["total_return_krw"]) == 500
    assert float(metrics["residual_krw"]) == 0

def test_fifo_realized_pnl_lot_missing_stays_review_status_without_blocking_pipeline(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "CASH_KRW", "security_name": "KRW Cash", "account_type": "ISA", "market": "KR", "asset_type": "cash", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 100000, "evaluation_amount_krw": 100000, "source_file_type": "holdings"},
        ],
        transaction_rows=[
            {"import_id": "buy-partial", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "MISS", "security_name": "Missing Lot Test", "trade_date": "2026-01-01", "transaction_type": "buy", "quantity": 1, "trade_amount_krw": 1000, "amount_krw": 1000, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-missing", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "KR", "asset_type": "stock", "ticker": "MISS", "security_name": "Missing Lot Test", "trade_date": "2026-01-02", "transaction_type": "sell", "quantity": 2, "trade_amount_krw": 2500, "amount_krw": 2500, "currency_native": "KRW", "amount_review_status": "ok", "cashflow_role": "trade_settlement"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    holdings = read_processed_csv(processed, "processed_holdings.csv")
    row = realized.iloc[0]

    assert len(realized) == 1
    assert row["cost_basis_method"] == "fifo"
    assert row["amount_review_status"] == "lot_missing"
    assert "sell quantity exceeds matched buy lots" in row["amount_review_reason"]
    assert is_blank_or_na(row["realized_trade_pnl_gross_krw"])
    assert is_blank_or_na(row["realized_trade_pnl_net_krw"])
    assert set(holdings["ticker"]) == {"CASH_KRW"}
    assert metrics["realized_cost_basis_method"] == "fifo"
    assert metrics["realized_pnl_status"] == "lot_missing"
    assert int(metrics["realized_pnl_unavailable_row_count"]) == 1
    assert metrics["explained_profit_krw"] == ""
    assert metrics["explained_profit_status"] == "lot_missing"
    assert metrics["residual_krw"] == ""
    assert metrics["residual_status"] == "unavailable"

def test_realized_pnl_fx_missing_blocks_official_profit_decomposition(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "CASH_KRW", "security_name": "KRW Cash", "account_type": "ISA", "market": "KR", "asset_type": "cash", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 100000, "evaluation_amount_krw": 100000, "source_file_type": "holdings"},
        ],
        transaction_rows=[
            {"import_id": "buy-tsll", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "US", "asset_type": "stock", "ticker": "TSLL", "security_name": "TSLL", "trade_date": "2026-01-01", "transaction_type": "buy", "quantity": 1, "trade_amount": 100, "currency_native": "USD", "amount_review_status": "fx_missing", "cashflow_role": "trade_settlement"},
            {"import_id": "sell-tsll", "source_file": "synthetic_transactions.csv", "source_file_type": "transaction_history", "account_type": "ISA", "market": "US", "asset_type": "stock", "ticker": "TSLL", "security_name": "TSLL", "trade_date": "2026-01-02", "transaction_type": "sell", "quantity": 1, "trade_amount": 120, "currency_native": "USD", "amount_review_status": "fx_missing", "cashflow_role": "trade_settlement"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)
    realized = read_processed_csv(processed, "processed_realized_pnl.csv")
    row = realized.iloc[0]

    assert metrics["realized_pnl_krw"] == ""
    assert metrics["realized_pnl_status"] == "fx_missing"
    assert int(metrics["realized_pnl_unavailable_row_count"]) == 1
    assert metrics["explained_profit_krw"] == ""
    assert metrics["explained_profit_status"] == "fx_missing"
    assert metrics["residual_krw"] == ""
    assert metrics["residual_status"] == "unavailable"
    assert set(realized["amount_review_status"]) == {"fx_missing"}
    assert set(realized["fx_status"]) == {"fx_missing"}
    assert float(row["proceeds_native"]) == 120
    assert float(row["cost_basis_native"]) == 100
    assert float(row["realized_trade_pnl_gross_native"]) == 20
    assert float(row["realized_trade_pnl_net_native"]) == 20
    assert is_blank_or_na(row["realized_trade_pnl_gross_krw"])
    assert is_blank_or_na(row["realized_trade_pnl_net_krw"])

def test_reconciliation_exchange_rows_do_not_change_principal(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "005930", "security_name": "Samsung", "account_type": "ISA", "market": "KR", "asset_type": "stock", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 100000, "evaluation_amount_krw": 100000, "source_file_type": "holdings"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
            {"transaction_type": "exchange", "cashflow_role": "internal_fx_exchange", "settlement_amount_krw": 50000, "amount_krw": 50000, "amount_review_status": "ok", "affects_principal": False},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)

    assert float(metrics["external_deposit_krw"]) == 100000
    assert float(metrics["net_external_principal_krw"]) == 100000

def test_reconciliation_summary_exposes_fx_event_counts(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "005930", "security_name": "Samsung", "account_type": "ISA", "market": "KR", "asset_type": "stock", "currency": "KRW", "currency_native": "KRW", "balance_quantity": 1, "evaluation_amount": 100000, "evaluation_amount_krw": 100000, "source_file_type": "holdings"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "settlement_amount_krw": 100000, "amount_krw": 100000, "amount_review_status": "ok", "affects_principal": True},
        ],
        fx_rows=[
            fx_gate_row(fx_event_id="FX-1", fx_pair_status="paired", currency_native="KRW"),
            fx_gate_row(fx_event_id="FX-1", fx_pair_status="paired", currency_native="USD"),
            fx_gate_row(fx_event_id="FX-2", fx_pair_status="partial", currency_native="USD"),
            fx_gate_row(fx_event_id="FX-3", fx_pair_status="unpaired", currency_native="KRW"),
            fx_gate_row(fx_event_id="FX-4", fx_pair_status="needs_review", currency_native="USD", amount_review_status="needs_review"),
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)

    assert int(metrics["fx_event_id_count"]) == 4
    assert int(metrics["fx_event_leg_count"]) == 5
    assert int(metrics["fx_paired_event_count"]) == 1
    assert int(metrics["fx_partial_event_count"]) == 1
    assert int(metrics["fx_unpaired_event_count"]) == 1
    assert int(metrics["fx_needs_review_event_count"]) == 1
    assert int(metrics["fx_unpaired_or_needs_review_row_count"]) == 2
    assert int(metrics["fx_internal_transfer_row_count"]) == 5
    assert metrics["fx_pnl_status"] == "unavailable"
    assert float(metrics["net_external_principal_krw"]) == 100000

def test_reconciliation_does_not_use_quantity_or_price_for_assets_or_principal(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_baseline(
        processed,
        holdings_rows=[
            {"ticker": "AAPL", "security_name": "Apple", "account_type": "overseas", "market": "US", "asset_type": "stock", "currency": "USD", "currency_native": "USD", "balance_quantity": 8, "quantity": 8, "price": 51.5, "evaluation_amount": "", "evaluation_amount_krw": "", "source_file_type": "overseas_balance"},
        ],
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "quantity": 8, "price": 51.5, "settlement_amount_krw": "", "amount_krw": "", "amount_review_status": "unit_ambiguous", "affects_principal": False},
        ],
    )

    generate_reports(tmp_path, processed_dir=processed)
    metrics = reconciliation_metrics(processed)

    assert metrics["total_assets_krw"] != "412"
    assert metrics["net_external_principal_krw"] != "412"
    assert metrics["total_assets_status"] in {"fx_missing", "unit_ambiguous"}
    assert metrics["net_external_principal_status"] in {"unit_ambiguous", "unavailable"}

def test_monthly_cashflow_summary_calculates_deposit_withdrawal_net_cumulative():
    cashflows = pd.DataFrame([
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "cashflow_role": "external_principal",
            "settlement_amount_krw": 1000,
            "amount_krw": 999,
            "amount_review_status": "ok",
            "affects_principal": True,
        },
        {
            "trade_date": "2025-08-01",
            "transaction_type": "withdrawal",
            "cashflow_role": "external_principal",
            "settlement_amount_krw": 200,
            "amount_krw": 200,
            "amount_review_status": "ok",
            "affects_principal": True,
        },
        {
            "trade_date": "2025-08-15",
            "transaction_type": "deposit",
            "cashflow_role": "external_principal",
            "settlement_amount_krw": 500,
            "amount_krw": 500,
            "amount_review_status": "ok",
            "affects_principal": True,
        },
        {
            "trade_date": "2025-08-20",
            "transaction_type": "deposit",
            "cashflow_role": "income_dividend",
            "settlement_amount_krw": 700,
            "amount_krw": 700,
            "amount_review_status": "ok",
            "affects_principal": False,
        },
    ])

    summary = build_monthly_cashflow_summary(cashflows)
    rows = summary.set_index("month")

    assert list(summary.columns) == MONTHLY_CASHFLOW_SUMMARY_COLUMNS
    assert float(rows.loc["2025-07", "external_deposit_krw"]) == 1000
    assert float(rows.loc["2025-07", "external_withdrawal_krw"]) == 0
    assert float(rows.loc["2025-07", "net_principal_flow_krw"]) == 1000
    assert float(rows.loc["2025-07", "cumulative_principal_krw"]) == 1000
    assert float(rows.loc["2025-08", "external_deposit_krw"]) == 500
    assert float(rows.loc["2025-08", "external_withdrawal_krw"]) == 200
    assert float(rows.loc["2025-08", "net_principal_flow_krw"]) == 300
    assert float(rows.loc["2025-08", "cumulative_principal_krw"]) == 1300

def test_performance_history_upserts_snapshot_without_estimating_past_assets():
    existing = pd.DataFrame([
        {
            "snapshot_month": "2026-04",
            "snapshot_date": "2026-04-30",
            "cumulative_principal_krw": "100000",
            "current_total_assets_krw": "110000",
            "cumulative_return_krw": "10000",
            "cumulative_return_pct": "10",
            "performance_status": "available",
        },
    ])
    performance = pd.DataFrame(valid_performance_summary_rows(
        net_external_principal_krw="120000",
        current_total_assets_krw="125000",
        cumulative_return_krw="5000",
        cumulative_return_pct="4.166667",
    ))

    history = build_performance_history(performance, existing, snapshot_date=date(2026, 5, 24))
    rows = history.set_index("snapshot_month")

    assert list(history.columns) == PERFORMANCE_HISTORY_COLUMNS
    assert list(history["snapshot_month"]) == ["2026-04", "2026-05"]
    assert float(rows.loc["2026-04", "current_total_assets_krw"]) == 110000
    assert float(rows.loc["2026-05", "cumulative_principal_krw"]) == 120000
    assert float(rows.loc["2026-05", "current_total_assets_krw"]) == 125000
    assert float(rows.loc["2026-05", "cumulative_return_krw"]) == 5000

def test_generate_reports_applies_user_confirmed_holdings_snapshot_asof_register(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    cache = tmp_path / "70_Imports" / "cache"
    processed.mkdir(parents=True)
    cache.mkdir(parents=True)
    pd.DataFrame([
        {
            "ticker": "SYNTH",
            "security_name": "Synthetic Holding",
            "account_type": "ISA",
            "market": "KR",
            "asset_type": "stock",
            "currency": "KRW",
            "balance_quantity": 1,
            "evaluation_amount": 1000,
            "evaluation_amount_krw": 1000,
            "unrealized_pnl": 10,
            "pnl_pct": 1,
            "source_file_type": "holdings",
            "snapshot_date": "",
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame([
        {"source_file": "synthetic_source.xlsx", "source_file_type": "holdings", "account_type": "ISA", "snapshot_date": ""},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {
            "source_file_type": "holdings",
            "account_type": "ISA",
            "market": "KR",
            "snapshot_date": "2026-07-02",
            "source_type": "user_confirmed",
            "status": "active",
            "source_note": "operator confirmed export as-of date",
            "created_at_utc": "2026-07-09T00:00:00Z",
            "rule_version": "test",
        },
    ]).to_csv(cache / "holdings_snapshot_asof.csv", index=False)

    generate_reports(tmp_path, processed_dir=processed)

    holdings = read_processed_csv(processed, "processed_holdings.csv")
    source_index = read_processed_csv(processed, "source_file_index.csv")
    assert holdings["snapshot_date"].iloc[0] == "2026-07-02"
    assert holdings["snapshot_date_source"].iloc[0] == "user_confirmed_asof_register"
    assert holdings["snapshot_date_status"].iloc[0] == "user_confirmed"
    assert source_index["snapshot_date"].iloc[0] == "2026-07-02"
    assert source_index["snapshot_date_source"].iloc[0] == "user_confirmed_asof_register"

def test_source_index_missing_market_accepts_one_date_across_market_scopes():
    source_index = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "ISA", "snapshot_date": ""},
    ])
    register = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "isa", "market": "KR", "snapshot_date": "2026-07-02", "source_type": "user_confirmed", "status": "user_confirmed"},
        {"source_file_type": "holdings", "account_type": "isa", "market": "US", "snapshot_date": "2026-07-02", "source_type": "user_confirmed", "status": "user_confirmed"},
    ])

    result = apply_holdings_snapshot_asof_register_to_source_index(source_index, register)

    assert result["snapshot_date"].iloc[0] == "2026-07-02"
    assert result["snapshot_date_source"].iloc[0] == "user_confirmed_asof_register"
    assert result["snapshot_date_status"].iloc[0] == "user_confirmed"

def test_source_index_missing_market_blocks_multiple_register_dates():
    source_index = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "ISA", "snapshot_date": ""},
    ])
    register = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "isa", "market": "KR", "snapshot_date": "2026-07-02", "source_type": "user_confirmed", "status": "user_confirmed"},
        {"source_file_type": "holdings", "account_type": "isa", "market": "US", "snapshot_date": "2026-07-03", "source_type": "user_confirmed", "status": "user_confirmed"},
    ])

    result = apply_holdings_snapshot_asof_register_to_source_index(source_index, register)

    assert result["snapshot_date"].iloc[0] == ""
    assert result["snapshot_date_source"].iloc[0] == ""
    assert result["snapshot_date_status"].iloc[0] == "asof_register_conflict"

def test_holdings_missing_market_does_not_use_market_specific_register():
    holdings = pd.DataFrame([
        {"ticker": "SYNTH", "account_type": "ISA", "source_file_type": "holdings", "snapshot_date": ""},
    ])
    register = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "isa", "market": "KR", "snapshot_date": "2026-07-02", "source_type": "user_confirmed", "status": "user_confirmed"},
    ])

    result = apply_holdings_snapshot_asof_register(holdings, register)

    assert result["snapshot_date"].iloc[0] == ""
    assert result["snapshot_date_source"].iloc[0] == ""
    assert result["snapshot_date_status"].iloc[0] == ""

def test_holdings_snapshot_asof_register_preserves_broker_snapshot_date():
    holdings = pd.DataFrame([
        {"ticker": "SYNTH", "account_type": "ISA", "market": "KR", "source_file_type": "holdings", "snapshot_date": "2026-06-28"},
    ])
    register = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "isa", "market": "KR", "snapshot_date": "2026-07-02", "source_type": "user_confirmed", "status": "active"},
    ])

    result = apply_holdings_snapshot_asof_register(holdings, register)

    assert result["snapshot_date"].iloc[0] == "2026-06-28"
    assert result["snapshot_date_source"].iloc[0] == "broker_export"
    assert result["snapshot_date_status"].iloc[0] == "available"

def test_holdings_snapshot_asof_register_ignores_transaction_history_source():
    holdings = pd.DataFrame([
        {"ticker": "SYNTH", "account_type": "ISA", "market": "KR", "source_file_type": "transaction_history", "snapshot_date": ""},
    ])
    register = pd.DataFrame([
        {"source_file_type": "holdings", "account_type": "isa", "market": "KR", "snapshot_date": "2026-07-02", "source_type": "user_confirmed", "status": "active"},
    ])

    result = apply_holdings_snapshot_asof_register(holdings, register)

    assert result["snapshot_date"].iloc[0] == ""
    assert result["snapshot_date_source"].iloc[0] == ""
