from pathlib import Path
import sys

import pandas as pd

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    import_raw_dir,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_dataframe,
    normalize_date,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from obsidian_writer import replace_autogenerated_block
from portfolio_model import build_portfolio, build_portfolio_outputs
from qa_checker import run_qa
from quality_gate import changed_entries, scan_generated_markdown_sensitive, snapshot_raw_files


def test_parse_korean_numeric_strings():
    assert parse_korean_number("1,234,567") == 1234567
    assert parse_korean_number("(1,200)") == -1200
    assert parse_korean_number("▲1,200원") == -1200


def test_parse_korean_percentage_strings():
    assert parse_korean_percent("-10.25%") == -10.25
    assert parse_korean_percent("12.3 %") == 12.3


def test_normalize_date_columns():
    assert normalize_date("2026.04.29") == "2026-04-29"
    assert normalize_date("20260429") == "2026-04-29"


def test_classify_transaction_types():
    assert classify_transaction_type("주식 매수") == "buy"
    assert classify_transaction_type("현금배당") == "dividend"
    assert classify_transaction_type("알수없음") == "unknown"


def test_detect_leveraged_etf_names():
    assert is_leveraged_etf_name("Direxion Daily Semiconductor Bull 3X")
    assert is_leveraged_etf_name("KODEX 2차전지산업레버리지")
    assert not is_leveraged_etf_name("Apple Inc")


def test_calculate_weight_pct(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"ticker": "A", "security_name": "A", "account_type": "종합", "market": "KR", "asset_type": "stock", "evaluation_amount": 85, "unrealized_pnl": 0, "pnl_pct": 0, "balance_quantity": 1},
        {"ticker": "B", "security_name": "B", "account_type": "종합", "market": "KR", "asset_type": "stock", "evaluation_amount": 15, "unrealized_pnl": 0, "pnl_pct": 0, "balance_quantity": 1},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    summary, holdings, _, _ = build_portfolio(processed, vault)
    assert round(float(holdings.loc[holdings["ticker"] == "A", "weight_pct"].iloc[0]), 0) == 85


def test_detect_pnl_pct_minus_ten(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    (vault / "20_Companies" / "A").mkdir(parents=True)
    (vault / "20_Companies" / "A" / "Company.md").write_text("---\ntype: company\nticker: A\nmarket: KR\n---\n# A\n", encoding="utf-8")
    pd.DataFrame([{"ticker": "A", "security_name": "A", "evaluation_amount": 100, "pnl_pct": -10.1, "balance_quantity": 1}]).to_csv(processed / "processed_holdings.csv", index=False)
    _, _, risk, review = build_portfolio(processed, vault)
    assert "LOSS_REVIEW_REQUIRED" in risk["risk_flags"].iloc[0]
    assert any(review["reason"].str.contains("-10%"))


def test_zero_weight_zero_quantity_goes_to_history_queue(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"ticker": "CURRENT", "security_name": "Current", "account_type": "종합", "evaluation_amount": 100, "pnl_pct": 0, "balance_quantity": 1},
        {"ticker": "PAST", "security_name": "Past", "account_type": "종합", "quantity": 99, "evaluation_amount": 0, "pnl_pct": 0, "balance_quantity": 0},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    assert set(holdings["ticker"]) == {"CURRENT"}
    assert "PAST" not in set(review.get("ticker", pd.Series(dtype=str)))
    assert set(history["ticker"]) == {"PAST"}


def test_transaction_only_past_ticker_goes_to_history_queue(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"ticker": "CURRENT", "security_name": "Current", "account_type": "종합", "evaluation_amount": 100, "pnl_pct": 0, "balance_quantity": 1},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame([
        {"ticker": "PAST", "security_name": "Past", "account_type": "종합", "trade_date": "2026-01-10", "transaction_type": "sell", "quantity": 99},
    ]).to_csv(processed / "processed_transactions.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    assert set(holdings["ticker"]) == {"CURRENT"}
    assert "PAST" not in set(review.get("ticker", pd.Series(dtype=str)))
    assert set(history["ticker"]) == {"PAST"}
    assert history["history_reason"].iloc[0] == "TRANSACTION_HISTORY_NO_CURRENT_POSITION"


def test_transaction_history_with_balance_columns_is_not_holdings(tmp_path: Path):
    df = pd.DataFrame([
        {
            "실거래일자": "2026-04-29",
            "거래유형": "매수",
            "상세내용": "코스피매수",
            "종목명": "삼성전자 005930",
            "수량": "1",
            "거래금액": "70000",
            "잔고금액": "70000",
        }
    ])
    path = tmp_path / "종합거래내역 상세.xls"
    assert infer_source_file_type(path, "table_0", df) == "transaction_history"
    normalized, _, _ = normalize_dataframe(df, path, "table_0")
    assert normalized["source_file_type"].iloc[0] == "transaction_history"
    assert pd.isna(normalized["balance_quantity"].iloc[0])
    assert pd.isna(normalized["evaluation_amount"].iloc[0])
    assert pd.isna(normalized["pnl_pct"].iloc[0])


def test_import_transaction_history_does_not_create_holdings(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"실거래일자": "2026-04-29", "거래유형": "매수", "상세내용": "코스피매수", "종목명": "삼성전자 005930", "수량": "1", "거래금액": "70000", "잔고금액": "70000"},
    ]).to_excel(raw / "종합거래내역 상세.xlsx", index=False)
    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    idx = pd.read_csv(processed / "source_file_index.csv")
    tx = pd.read_csv(processed / "processed_transactions.csv")
    holdings = pd.read_csv(processed / "processed_holdings.csv")
    assert set(idx["source_file_type"]) == {"transaction_history"}
    assert len(tx) == 1
    assert len(holdings) == 0


def test_no_balance_files_keeps_portfolio_value_unknown(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_abc.xls", "source_file_type": "transaction_history", "account_type": "comprehensive"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"ticker": "A", "security_name": "A", "account_type": "comprehensive", "trade_date": "2026-04-29", "transaction_type": "buy", "quantity": 1, "trade_amount": 100},
    ]).to_csv(processed / "processed_transactions.csv", index=False)
    pd.DataFrame(columns=["ticker", "security_name", "balance_quantity", "evaluation_amount", "pnl_pct"]).to_csv(processed / "processed_holdings.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))
    assert holdings.empty
    assert str(summary_map["balance_data_available"]).lower() == "false"
    assert summary_map["total_portfolio_value_status"] == "unknown"
    assert summary_map["total_portfolio_value_basis"] == "unknown_no_balance_file"


def test_holdings_file_makes_portfolio_summary_available(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_balance.xls", "source_file_type": "holdings", "account_type": "ISA"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"ticker": "005930", "security_name": "Samsung", "account_type": "ISA", "market": "KR", "asset_type": "stock", "currency": "KRW", "balance_quantity": 2, "evaluation_amount": 100000, "unrealized_pnl": 1000, "pnl_pct": 1.0, "source_file_type": "holdings"},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["ticker"]).to_csv(processed / "processed_transactions.csv", index=False)
    summary, holdings, risk, review, history = build_portfolio_outputs(processed, vault)
    summary_map = dict(zip(summary["metric"], summary["value"]))
    assert len(holdings) == 1
    assert summary_map["total_portfolio_value_status"] == "available"
    assert float(summary_map["total_portfolio_value"]) == 100000


def test_mixed_transaction_history_and_holdings_split_correctly(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([
        {"실거래일자": "2026-04-29", "거래유형": "매수", "상세내용": "코스피매수", "종목명": "삼성전자 005930", "수량": "1", "거래금액": "70000", "잔고금액": "70000"},
    ]).to_excel(raw / "종합거래내역 상세.xlsx", index=False)
    pd.DataFrame([
        {"종목명": "삼성전자", "종목코드": "005930", "보유수량": "2", "평가금액": "140000", "평가손익": "1000", "평가손익률": "0.71"},
    ]).to_excel(raw / "종합잔고.xlsx", index=False)
    import_raw_dir(vault)
    processed = vault / "70_Imports" / "processed"
    idx = pd.read_csv(processed / "source_file_index.csv")
    tx = pd.read_csv(processed / "processed_transactions.csv")
    holdings = pd.read_csv(processed / "processed_holdings.csv")
    assert set(idx["source_file_type"]) == {"transaction_history", "holdings"}
    assert len(tx) == 1
    assert len(holdings) == 1
    assert set(holdings["source_file_type"]) == {"holdings"}


def test_raw_file_mtime_unchanged_by_import(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    path = raw / "종합거래내역 상세.xlsx"
    pd.DataFrame([
        {"실거래일자": "2026-04-29", "거래유형": "매수", "상세내용": "코스피매수", "종목명": "삼성전자 005930", "수량": "1", "거래금액": "70000"},
    ]).to_excel(path, index=False)
    before = snapshot_raw_files(raw)
    import_raw_dir(vault)
    after = snapshot_raw_files(raw)
    assert changed_entries(before, after) == []


def test_generated_markdown_sensitive_scan_detects_candidate(tmp_path: Path):
    dash = tmp_path / "10_Dashboard"
    dash.mkdir(parents=True)
    (dash / "Portfolio.md").write_text(
        "# Portfolio\n\n<!-- AUTO-GENERATED:START -->\nphone: 010-1234-5678\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )
    assert scan_generated_markdown_sensitive(tmp_path) == ["10_Dashboard\\Portfolio.md"] or scan_generated_markdown_sensitive(tmp_path) == ["10_Dashboard/Portfolio.md"]


def test_file_without_autogenerated_markers_is_not_overwritten(tmp_path: Path):
    note = tmp_path / "Manual.md"
    note.write_text("# Manual\n\nuser-written text\n", encoding="utf-8")
    ok, warning = replace_autogenerated_block(note, "generated")
    assert not ok
    assert "AUTO-GENERATED" in warning
    assert note.read_text(encoding="utf-8") == "# Manual\n\nuser-written text\n"


def test_deduplicate_overlapping_transaction_rows(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    df = pd.DataFrame([
        {"거래일자": "2026-04-29", "거래유형": "매수", "종목코드": "5930", "종목명": "삼성전자", "수량": "1", "단가": "70000", "거래금액": "70000"},
        {"거래일자": "2026-04-29", "거래유형": "매수", "종목코드": "5930", "종목명": "삼성전자", "수량": "1", "단가": "70000", "거래금액": "70000"},
    ])
    path = raw / "sample.xlsx"
    df.to_excel(path, index=False)
    summary = import_raw_dir(vault)
    out = pd.read_csv(vault / "70_Imports" / "processed" / "processed_transactions.csv", dtype={"ticker": str})
    assert summary.duplicate_rows_removed == 1
    assert len(out) == 1


def test_generate_source_file_index(tmp_path: Path):
    vault = tmp_path
    raw = vault / "70_Imports" / "raw"
    raw.mkdir(parents=True)
    pd.DataFrame([{"거래일자": "2026-04-29", "거래유형": "입금", "거래금액": "1000"}]).to_excel(raw / "cash.xlsx", index=False)
    import_raw_dir(vault)
    idx = pd.read_csv(vault / "70_Imports" / "processed" / "source_file_index.csv")
    assert len(idx) == 1
    assert idx["source_file"].iloc[0].startswith("source_")


def test_preserve_user_written_markdown_sections(tmp_path: Path):
    note = tmp_path / "Company.md"
    note.write_text("# A\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n\n## 사용자 판단 영역\nkeep me\n", encoding="utf-8")
    replace_autogenerated_block(note, "new")
    text = note.read_text(encoding="utf-8")
    assert "new" in text
    assert "keep me" in text


def test_update_only_autogenerated_block(tmp_path: Path):
    note = tmp_path / "Dashboard.md"
    note.write_text("before\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\nafter\n", encoding="utf-8")
    ok, _ = replace_autogenerated_block(note, "new")
    assert ok
    assert note.read_text(encoding="utf-8") == "before\n<!-- AUTO-GENERATED:START -->\nnew\n<!-- AUTO-GENERATED:END -->\nafter\n"


def test_generate_qa_exception_for_missing_thesis(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "A"
    company.mkdir(parents=True)
    (company / "Company.md").write_text("---\ntype: company\nticker: A\nmarket: KR\n---\n# A\n## 투자 논리(Thesis)\n- \n", encoding="utf-8")
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text("# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n", encoding="utf-8")
    qa = run_qa(vault)
    assert "INV-EX-03" in set(qa["exception_id"])


def test_generate_qa_exception_for_missing_sell_criteria(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "A"
    company.mkdir(parents=True)
    (company / "Company.md").write_text("---\ntype: company\nticker: A\nmarket: KR\n---\n# A\n## 투자 논리(Thesis)\n핵심 가정이 충분히 작성되어 있습니다.\n", encoding="utf-8")
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text("# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n", encoding="utf-8")
    qa = run_qa(vault)
    assert "INV-EX-08" in set(qa["exception_id"])


def test_handle_xls_html_table_fallback(tmp_path: Path):
    html = """<html><body><table><tr><th>거래일자</th><th>거래유형</th><th>종목코드</th><th>종목명</th><th>수량</th><th>단가</th></tr><tr><td>2026.04.29</td><td>매수</td><td>5930</td><td>삼성전자</td><td>1</td><td>70000</td></tr></table></body></html>"""
    path = tmp_path / "sample.xls"
    path.write_text(html, encoding="utf-8")
    tables = load_workbook_tables(path)
    assert tables
    normalized, _, _ = normalize_dataframe(next(iter(tables.values())), path, "table_0")
    assert normalized["ticker"].iloc[0] == "005930"
