import argparse
from datetime import date, datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from types import SimpleNamespace
import uuid

import pandas as pd
import pytest

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON,
    COLUMN_ALIASES,
    MULTIINDEX_COLUMN_SEPARATOR,
    OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON,
    canonical_overseas_position_key,
    dedupe_holdings,
    extract_symbol_from_parentheses,
    import_raw_dir,
    infer_asset_type,
    infer_market,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_cash_currency,
    normalize_currency_and_fx_rate,
    normalize_dataframe,
    normalize_date,
    normalize_amount_fields,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from migrate_autogenerated_markers import resolve_company_note
import main as pipeline_main
from main import LIVE_WRITE_CONFIRMATION_TOKEN, build_parser, is_live_vault_path, live_write_guard_findings
from obsidian_writer import AUTO_END, AUTO_START, bootstrap_autogenerated_block, dashboard_content, qa_exception_cards, qa_exception_rollup_summary, replace_autogenerated_block, write_company_notes
from portfolio_model import apply_expense_fx_rates, apply_holdings_snapshot_asof_register, apply_holdings_snapshot_asof_register_to_source_index, apply_income_fx_rates, build_fx_rate_requirements, build_income_summary, build_monthly_cashflow_summary, build_performance_history, build_performance_summary, build_portfolio, build_portfolio_outputs, generate_reports, has_filled_section, load_fx_rates, resolve_fx_rate
from qa_checker import QA_EXCEPTION_ROLLUP_COLUMNS, REC_EX_01_ISSUE, REC_EX_01_SUGGESTED_FIX, build_qa_exception_rollup, run_qa
from quality_gate import (
    audit_output_schema_findings,
    audit_representation_findings,
    changed_entries,
    company_note_currency_findings,
    company_note_duplicate_findings,
    duplicate_overseas_holding_findings,
    expense_contract_findings,
    fx_internal_transfer_findings,
    fx_event_contract_findings,
    income_contract_findings,
    income_expense_separation_findings,
    income_reversal_review_findings,
    income_summary_contract_findings,
    invalid_currency_findings,
    live_vault_actual_write_guard_findings,
    non_krw_amount_without_fx_findings,
    dashboard_return_label_findings,
    official_krw_total_provenance_findings,
    principal_unit_misuse_findings,
    processed_cashflows_contract_findings,
    processed_output_schema_findings,
    performance_summary_findings,
    realized_pnl_cost_basis_findings,
    realized_pnl_review_findings,
    reconciliation_summary_findings,
    scan_generated_markdown_sensitive,
    snapshot_raw_files,
    unit_classification_findings,
)

from support import (
    AMOUNT_UNIT_AUDIT_COLUMNS,
    EXPENSE_OUTPUT_COLUMNS,
    FX_EVENT_COLUMNS,
    FX_RATE_REQUIREMENT_COLUMNS,
    INCOME_OUTPUT_COLUMNS,
    INCOME_SUMMARY_OUTPUT_COLUMNS,
    MONTHLY_CASHFLOW_SUMMARY_COLUMNS,
    PERFORMANCE_HISTORY_COLUMNS,
    PERFORMANCE_SUMMARY_METRICS,
    REALIZED_PNL_OUTPUT_COLUMNS,
    UNIT_MISMATCH_AUDIT_COLUMNS,
    assert_columns_present,
    fx_gate_row,
    is_blank_or_na,
    read_processed_csv,
    reconciliation_metrics,
    synthetic_rec_ex_01_rollup_rows,
    valid_performance_summary_rows,
    valid_reconciliation_summary_rows,
    write_stage8_output_inputs,
)


def test_qa_exception_cards_export_for_live_qa_checker():
    qa = pd.DataFrame([
        {
            "exception_id": "INV-EX-03",
            "severity": "advisory",
            "file": "20_Companies/AEHR/Company.md",
            "issue": "missing thesis",
            "suggested_fix": "write the missing section manually",
        }
    ])
    content = qa_exception_cards(qa)
    assert "QA Exceptions" in content
    assert "Exception Summary" in content
    assert "INV-EX-03" in content
    assert "[[20_Companies/AEHR/Company\\|AEHR]]" in content

def test_qa_rollup_rec_ex_01_preserves_displayed_finding_count():
    qa = synthetic_rec_ex_01_rollup_rows()

    rollup = build_qa_exception_rollup(qa)
    row = rollup[rollup["exception_id"].eq("REC-EX-01") & rollup["severity"].eq("blocking")].iloc[0]

    assert row["displayed_finding_count"] == 4
    assert len(qa) == 4

def test_qa_rollup_rec_ex_01_groups_parallel_audit_layers_by_safe_categories():
    rollup = build_qa_exception_rollup(synthetic_rec_ex_01_rollup_rows())
    row = rollup[rollup["exception_id"].eq("REC-EX-01") & rollup["severity"].eq("blocking")].iloc[0]

    assert row["distinct_issue_group_count"] == 2
    assert "amount_unit_audit: 2" in row["audit_layer_counts"]
    assert "unit_mismatch_audit: 2" in row["audit_layer_counts"]

def test_qa_rollup_keeps_blocking_severity_when_grouping():
    qa = pd.DataFrame([
        {
            "exception_id": "REC-EX-20",
            "severity": "blocking",
            "file": "70_Imports/processed/amount_unit_audit.csv:row2",
            "source_file_type": "transaction_history",
            "cashflow_role": "trade_settlement",
        },
        {
            "exception_id": "REC-EX-20",
            "severity": "advisory",
            "file": "70_Imports/processed/amount_unit_audit.csv:row3",
            "source_file_type": "transaction_history",
            "cashflow_role": "trade_settlement",
        },
    ])

    rollup = build_qa_exception_rollup(qa)
    blocking = rollup[rollup["severity"].eq("blocking")].iloc[0]
    advisory = rollup[rollup["severity"].eq("advisory")].iloc[0]

    assert set(rollup["severity"]) == {"blocking", "advisory"}
    assert blocking["max_severity"] == "blocking"
    assert bool(blocking["has_blocking"])
    assert advisory["max_severity"] == "advisory"
    assert not bool(advisory["has_blocking"])

def test_qa_rollup_excludes_private_identity_fields():
    private_tokens = [
        "PRIVATE_ACCOUNT_123",
        "SYNTHETIC_TICKER_SECRET",
        "Synthetic Private Company",
        "raw private memo",
        "private raw header",
        "999999999",
    ]
    qa = pd.DataFrame([{
        "exception_id": "REC-EX-01",
        "severity": "blocking",
        "file": "PRIVATE_ACCOUNT_123/source.xlsx:row2",
        "audit_layer": "PRIVATE_ACCOUNT_123",
        "source_file_type": "transaction_history",
        "account_type": "comprehensive",
        "transaction_type": "buy",
        "cashflow_role": "trade_settlement",
        "amount_kind": "settlement_amount",
        "amount_basis": "raw_native",
        "currency_native": "USD",
        "raw_filename": "PRIVATE_ACCOUNT_123.xlsx",
        "raw_header": "private raw header",
        "account_identifier": "PRIVATE_ACCOUNT_123",
        "ticker": "SYNTHETIC_TICKER_SECRET",
        "security_name": "Synthetic Private Company",
        "amount_native": "999999999",
        "raw_memo": "raw private memo",
    }])

    rollup = build_qa_exception_rollup(qa)
    serialized = rollup.to_json(force_ascii=False)

    assert "file" not in rollup.columns
    assert "raw_header" not in rollup.columns
    assert "ticker" not in rollup.columns
    for token in private_tokens:
        assert token not in serialized

def test_qa_rollup_builds_summary_without_hiding_row_level_exceptions():
    qa = pd.concat([
        synthetic_rec_ex_01_rollup_rows(),
        pd.DataFrame([{
            "exception_id": "REC-EX-05",
            "severity": "advisory",
            "file": "70_Imports/processed/processed_income.csv:row2",
            "source_file_type": "transaction_history",
            "transaction_type": "dividend",
            "cashflow_role": "income_dividend",
        }]),
    ], ignore_index=True)
    original = qa.copy(deep=True)

    rollup = build_qa_exception_rollup(qa)

    pd.testing.assert_frame_equal(qa, original)
    assert int(rollup["displayed_finding_count"].sum()) == len(qa)
    assert "file" not in rollup.columns
    assert set(rollup["exception_id"]) == {"REC-EX-01", "REC-EX-05"}

def test_rec_ex_01_rollup_distinguishes_row_findings_from_issue_groups():
    qa = synthetic_rec_ex_01_rollup_rows()

    rollup = build_qa_exception_rollup(qa)
    rec_ex_01 = rollup[rollup["exception_id"].eq("REC-EX-01") & rollup["severity"].eq("blocking")].iloc[0]

    assert len(qa) == 4
    assert rec_ex_01["displayed_finding_count"] == 4
    assert rec_ex_01["distinct_issue_group_count"] == 2
    assert rec_ex_01["max_severity"] == "blocking"
    assert bool(rec_ex_01["has_blocking"])

def write_reconciliation_qa_inputs(
    processed: Path,
    amount_rows: list[dict[str, object]] | None = None,
    unit_mismatch_rows: list[dict[str, object]] | None = None,
    cashflow_rows: list[dict[str, object]] | None = None,
    income_rows: list[dict[str, object]] | None = None,
    fx_rows: list[dict[str, object]] | None = None,
    holdings_rows: list[dict[str, object]] | None = None,
    realized_rows: list[dict[str, object]] | None = None,
    income_summary_rows: list[dict[str, object]] | None = None,
    performance_rows: list[dict[str, object]] | None = None,
    reconciliation_rows: list[dict[str, object]] | None = None,
    write_required_outputs: bool = True,
) -> None:
    processed.mkdir(parents=True, exist_ok=True)
    if write_required_outputs:
        pd.DataFrame(income_summary_rows or [], columns=INCOME_SUMMARY_OUTPUT_COLUMNS).to_csv(processed / "income_summary.csv", index=False)
        pd.DataFrame(performance_rows or valid_performance_summary_rows()).to_csv(processed / "performance_summary.csv", index=False)
        pd.DataFrame(columns=MONTHLY_CASHFLOW_SUMMARY_COLUMNS).to_csv(processed / "monthly_cashflow_summary.csv", index=False)
        pd.DataFrame(columns=PERFORMANCE_HISTORY_COLUMNS).to_csv(processed / "performance_history.csv", index=False)
        pd.DataFrame(realized_rows or [], columns=REALIZED_PNL_OUTPUT_COLUMNS).to_csv(processed / "processed_realized_pnl.csv", index=False)
    if amount_rows is not None:
        pd.DataFrame(amount_rows).to_csv(processed / "amount_unit_audit.csv", index=False)
    if unit_mismatch_rows is not None:
        pd.DataFrame(unit_mismatch_rows).to_csv(processed / "unit_mismatch_audit.csv", index=False)
    if cashflow_rows is not None:
        pd.DataFrame(cashflow_rows).to_csv(processed / "processed_cashflows.csv", index=False)
    if income_rows is not None:
        pd.DataFrame(income_rows).to_csv(processed / "processed_income.csv", index=False)
    if fx_rows is not None:
        pd.DataFrame(fx_rows).to_csv(processed / "processed_fx_events.csv", index=False)
    if holdings_rows is not None:
        pd.DataFrame(holdings_rows).to_csv(processed / "processed_holdings.csv", index=False)
    if reconciliation_rows is not None:
        pd.DataFrame(reconciliation_rows).to_csv(processed / "reconciliation_summary.csv", index=False)

def qa_for_processed(vault: Path) -> pd.DataFrame:
    return run_qa(vault, vault / "70_Imports" / "processed", dry_run=True)

def write_rollup_output_qa_inputs(processed: Path, private_like_fields: bool = False) -> None:
    amount_row = {
        "amount_review_status": "fx_missing",
        "currency_native": "USD",
        "amount_native": 10,
        "amount_krw": "",
        "cashflow_role": "trade_settlement",
    }
    unit_row = {
        "amount_normalization_status": "fx_missing",
        "currency_native": "USD",
        "amount_native": 10,
        "amount_krw": "",
        "cashflow_role": "trade_settlement",
    }
    if private_like_fields:
        private_fields = {
            "raw_filename": "PRIVATE_RAW_FILE_TOKEN.xlsx",
            "account_identifier": "PRIVATE_ACCOUNT_TOKEN",
            "ticker": "PRIVATE_TICKER_TOKEN",
            "security_name": "PRIVATE_SECURITY_TOKEN",
            "raw_header": "PRIVATE_HEADER_TOKEN",
            "raw_memo": "PRIVATE_MEMO_TOKEN",
            "amount_private_token": "999999999",
        }
        amount_row.update(private_fields)
        unit_row.update(private_fields)
    write_reconciliation_qa_inputs(processed, amount_rows=[amount_row], unit_mismatch_rows=[unit_row])

def run_qa_rollup_output_fixture(vault: Path, dry_run: bool = False, private_like_fields: bool = False) -> tuple[Path, pd.DataFrame]:
    processed = vault / "70_Imports" / "processed"
    write_rollup_output_qa_inputs(processed, private_like_fields=private_like_fields)
    return processed, run_qa(vault, processed, dry_run=dry_run)

def test_run_qa_writes_qa_exception_rollup_when_not_dry_run(tmp_path: Path):
    processed, qa = run_qa_rollup_output_fixture(tmp_path, dry_run=False)
    rollup_path = processed / "qa_exception_rollup.csv"

    assert rollup_path.exists()
    rollup = pd.read_csv(rollup_path)
    assert list(rollup.columns) == QA_EXCEPTION_ROLLUP_COLUMNS
    assert int(rollup["displayed_finding_count"].sum()) == len(qa)

def test_run_qa_preserves_reviewed_fx_unavailable_note_when_rewriting_qa_dashboard(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    cache = vault / "70_Imports" / "cache"
    dashboard = vault / "10_Dashboard" / "QA_Exceptions.md"
    write_rollup_output_qa_inputs(processed)
    cache.mkdir(parents=True)
    dashboard.parent.mkdir(parents=True)
    dashboard.write_text(
        f"# QA\n\n{AUTO_START}\nold\n{AUTO_END}\n",
        encoding="utf-8",
    )
    pd.DataFrame([
        {
            "event_date": "2026-01-02",
            "currency": "USD",
            "use_case": "income_dividend",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "income",
            "status": "fx_missing",
        },
    ], columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)
    pd.DataFrame([
        {
            "requirement_key": "2026-01-02|USD|income_dividend",
            "decision": "still_review_gated",
            "reason_code": "official_fx_unavailable_same_date",
            "operator_review_label": "official_fx_unavailable_non_business_day",
            "provider": "eximbank",
        },
    ]).to_csv(cache / "fx_unavailable_exceptions.csv", index=False)

    run_qa(vault, processed, dry_run=False)

    content = dashboard.read_text(encoding="utf-8")
    assert "Remaining FX requirements: `1`" in content
    assert "reviewed official-FX-unavailable keys `1`; unreviewed keys `0`" in content
    assert "not FX rate provenance, archive promotion, or REC closure" in content
    assert "REC-EX-01 row-level findings remain blocking by policy" in content
    assert "unreviewed FX requirement keys are `0`, not that row-level REC findings are closed" in content
    assert content.index("REC-EX-01 row-level context") < content.index("## Exception Summary")
    assert "## Rollup Summary" in content

def test_run_qa_rewrites_dashboard_with_inv_ex_08_user_decision_gate(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "SYNTH"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: SYNTH\nmarket: KR\nasset_type: stock\n---\n"
        "# SYNTH\n"
        "## Thesis\n"
        "- Durable synthetic thesis text for test coverage.\n"
        "## sell criteria\n"
        "- \n",
        encoding="utf-8",
    )
    dashboard = vault / "10_Dashboard" / "QA_Exceptions.md"
    dashboard.parent.mkdir(parents=True)
    dashboard.write_text(
        "# QA\n\nmanual before\n\n"
        f"{AUTO_START}\nold\n{AUTO_END}\n\n"
        "manual after\n",
        encoding="utf-8",
    )

    run_qa(vault, dry_run=False)

    content = dashboard.read_text(encoding="utf-8")
    generated = content.split(AUTO_START, 1)[1].split(AUTO_END, 1)[0]
    outside = content.split(AUTO_START, 1)[0] + content.split(AUTO_END, 1)[1]

    assert "manual before" in outside
    assert "manual after" in outside
    assert "INV-EX-08 sell criteria review" in generated
    assert "QA findings `1`" in generated
    assert "not automated thesis, sell criteria, or buy/sell recommendations" in generated
    assert "keep INV-EX-08 review-gated" in generated

def test_run_qa_dry_run_does_not_write_qa_exception_rollup(tmp_path: Path):
    processed, _qa = run_qa_rollup_output_fixture(tmp_path, dry_run=True)

    assert not (processed / "qa_exception_rollup.csv").exists()
    assert not (processed / "qa_exceptions.csv").exists()

def test_main_dry_run_with_qa_rollup_evidence_does_not_write_qa_exception_rollup(tmp_path: Path, monkeypatch):
    processed = tmp_path / "70_Imports" / "processed"
    write_rollup_output_qa_inputs(processed)
    evidence_path = tmp_path / "evidence" / "qa-dry-run.json"
    monkeypatch.setattr(pipeline_main, "dry_run_evidence_output_path_findings", lambda *_args, **_kwargs: [])
    monkeypatch.setattr(sys, "argv", [
        "main.py",
        "qa",
        "--vault-root",
        str(tmp_path),
        "--dry-run",
        "--dry-run-evidence-out",
        str(evidence_path),
    ])

    assert pipeline_main.main() == 0
    payload = json.loads(evidence_path.read_text(encoding="utf-8"))

    assert payload["schema_version"] == 2
    assert set(payload["planned_categories"]["qa"]) == set(pipeline_main.REQUIRED_QA_ROLLUP_EVIDENCE_COUNTS)
    assert not (processed / "qa_exception_rollup.csv").exists()
    assert not (processed / "qa_exceptions.csv").exists()

def test_qa_exception_rollup_output_schema_is_stable(tmp_path: Path):
    processed, _qa = run_qa_rollup_output_fixture(tmp_path, dry_run=False)

    rollup = pd.read_csv(processed / "qa_exception_rollup.csv")

    assert list(rollup.columns) == [
        "exception_id",
        "severity",
        "displayed_finding_count",
        "distinct_issue_group_count",
        "audit_layer_counts",
        "max_severity",
        "has_blocking",
    ]

def test_qa_exception_rollup_output_preserves_row_level_qa_exceptions(tmp_path: Path):
    processed, qa = run_qa_rollup_output_fixture(tmp_path, dry_run=False)

    saved = pd.read_csv(processed / "qa_exceptions.csv")

    assert list(saved.columns) == ["exception_id", "severity", "file", "issue", "suggested_fix"]
    assert len(saved) == len(qa)
    assert saved.fillna("").to_dict("records") == qa.fillna("").to_dict("records")

def test_qa_exception_rollup_output_excludes_private_fields(tmp_path: Path):
    processed, _qa = run_qa_rollup_output_fixture(tmp_path, dry_run=False, private_like_fields=True)

    rollup = pd.read_csv(processed / "qa_exception_rollup.csv")
    serialized = rollup.to_csv(index=False)

    forbidden_columns = {
        "file",
        "source_row_ref",
        "raw_filename",
        "account_identifier",
        "ticker",
        "security_name",
        "amount_native",
        "amount_krw",
        "raw_header",
        "raw_memo",
        "issue",
        "suggested_fix",
    }
    assert not forbidden_columns.intersection(rollup.columns)
    for token in [
        "PRIVATE_RAW_FILE_TOKEN",
        "PRIVATE_ACCOUNT_TOKEN",
        "PRIVATE_TICKER_TOKEN",
        "PRIVATE_SECURITY_TOKEN",
        "PRIVATE_HEADER_TOKEN",
        "PRIVATE_MEMO_TOKEN",
        "999999999",
        "row2",
    ]:
        assert token not in serialized

def test_qa_exception_rollup_output_preserves_blocking_severity(tmp_path: Path):
    processed, _qa = run_qa_rollup_output_fixture(tmp_path, dry_run=False)

    rollup = pd.read_csv(processed / "qa_exception_rollup.csv")
    rec_ex_01 = rollup[rollup["exception_id"].eq("REC-EX-01")].iloc[0]

    assert rec_ex_01["severity"] == "blocking"
    assert rec_ex_01["max_severity"] == "blocking"
    assert str(rec_ex_01["has_blocking"]).strip().lower() == "true"

def test_qa_exception_rollup_output_counts_match_builder(tmp_path: Path):
    processed, qa = run_qa_rollup_output_fixture(tmp_path, dry_run=False)

    expected = build_qa_exception_rollup(qa).fillna("").reset_index(drop=True)
    actual = pd.read_csv(processed / "qa_exception_rollup.csv").fillna("").reset_index(drop=True)

    pd.testing.assert_frame_equal(actual, expected, check_dtype=False)

def test_qa_exception_dashboard_shows_rollup_row_and_group_counts():
    qa = synthetic_rec_ex_01_rollup_rows()
    rollup = build_qa_exception_rollup(qa)

    content = qa_exception_cards(qa, rollup)

    assert "## Rollup Summary" in content
    assert "row-level findings" in content
    assert "safe triage groups" in content
    assert "| `REC-EX-01` |" in content
    assert "| 4 | 2 |" in content

def test_qa_exception_dashboard_preserves_blocking_severity_in_rollup_summary():
    qa = synthetic_rec_ex_01_rollup_rows()
    rollup = build_qa_exception_rollup(qa)

    summary = qa_exception_rollup_summary(rollup)

    assert "blocking rollup rows" in summary
    assert '<span class="stock-tag stock-tag-blocking">blocking</span>' in summary
    assert "| yes |" in summary

def test_qa_exception_dashboard_rollup_summary_excludes_private_fields():
    private_tokens = [
        "PRIVATE_RAW_FILE_TOKEN",
        "PRIVATE_ACCOUNT_TOKEN",
        "PRIVATE_TICKER_TOKEN",
        "PRIVATE_SECURITY_TOKEN",
        "PRIVATE_HEADER_TOKEN",
        "PRIVATE_MEMO_TOKEN",
        "999999999",
        "row2",
    ]
    qa = pd.DataFrame([{
        "exception_id": "REC-EX-01",
        "severity": "blocking",
        "file": "PRIVATE_RAW_FILE_TOKEN.xlsx:row2",
        "audit_layer": "PRIVATE_ACCOUNT_TOKEN",
        "source_file_type": "transaction_history",
        "account_type": "comprehensive",
        "transaction_type": "buy",
        "cashflow_role": "trade_settlement",
        "amount_kind": "settlement_amount",
        "amount_basis": "raw_native",
        "currency_native": "USD",
        "raw_filename": "PRIVATE_RAW_FILE_TOKEN.xlsx",
        "raw_header": "PRIVATE_HEADER_TOKEN",
        "account_identifier": "PRIVATE_ACCOUNT_TOKEN",
        "ticker": "PRIVATE_TICKER_TOKEN",
        "security_name": "PRIVATE_SECURITY_TOKEN",
        "amount_native": "999999999",
        "raw_memo": "PRIVATE_MEMO_TOKEN",
    }])

    rollup = build_qa_exception_rollup(qa)
    summary = qa_exception_rollup_summary(rollup)

    for token in private_tokens:
        assert token not in summary

def test_qa_exception_dashboard_keeps_row_level_exception_details_available():
    qa = synthetic_rec_ex_01_rollup_rows()
    rollup = build_qa_exception_rollup(qa)

    content = qa_exception_cards(qa, rollup)

    assert "## Blocking" in content
    assert "FX provenance required" in content
    assert REC_EX_01_SUGGESTED_FIX in content

def test_qa_exception_dashboard_handles_missing_rollup_output_gracefully(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    synthetic_rec_ex_01_rollup_rows()[["exception_id", "severity", "file", "issue", "suggested_fix"]].to_csv(
        processed / "qa_exceptions.csv",
        index=False,
    )

    content = dashboard_content("QA_Exceptions.md", processed)

    assert "## Rollup Summary" in content
    assert "_No data to display._" in content
    assert "## Blocking" in content

def test_qa_exception_dashboard_rollup_summary_uses_neutral_triage_language():
    qa = synthetic_rec_ex_01_rollup_rows()
    rollup = build_qa_exception_rollup(qa)

    content = qa_exception_cards(qa, rollup).lower()

    assert "row-level findings" in content
    assert "safe triage groups" in content
    assert "duplicate" not in content
    assert "noise" not in content
    assert "false positive" not in content

def test_qa_exception_dashboard_rollup_summary_is_inside_autogenerated_block(tmp_path: Path):
    dashboard = tmp_path / "10_Dashboard" / "QA_Exceptions.md"
    dashboard.parent.mkdir(parents=True)
    dashboard.write_text(
        "# QA\n\nmanual before\n\n"
        f"{AUTO_START}\nold\n{AUTO_END}\n\n"
        "manual after\n",
        encoding="utf-8",
    )

    run_qa_rollup_output_fixture(tmp_path, dry_run=False)
    content = dashboard.read_text(encoding="utf-8")
    generated = content.split(AUTO_START, 1)[1].split(AUTO_END, 1)[0]
    outside = content.split(AUTO_START, 1)[0] + content.split(AUTO_END, 1)[1]

    assert "manual before" in outside
    assert "manual after" in outside
    assert "## Rollup Summary" in generated
    assert "row-level findings" in generated
    assert "safe triage groups" in generated
    assert "## Rollup Summary" not in outside

def test_run_qa_dry_run_does_not_write_dashboard_or_rollup_outputs(tmp_path: Path):
    processed, _qa = run_qa_rollup_output_fixture(tmp_path, dry_run=True)

    assert not (processed / "qa_exception_rollup.csv").exists()
    assert not (processed / "qa_exceptions.csv").exists()
    assert not (tmp_path / "10_Dashboard" / "QA_Exceptions.md").exists()

def test_qa_reconciliation_fx_missing_row_creates_exception(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {"amount_review_status": "fx_missing", "currency_native": "USD", "amount_native": 12.34, "amount_krw": "", "cashflow_role": "trade_settlement"},
    ])

    qa = qa_for_processed(tmp_path)

    assert "REC-EX-01" in set(qa["exception_id"])
    rec_ex_01 = qa.loc[qa["exception_id"].eq("REC-EX-01")].iloc[0]
    assert set(qa.loc[qa["exception_id"].eq("REC-EX-01"), "severity"]) == {"blocking"}
    assert rec_ex_01["issue"] == REC_EX_01_ISSUE
    assert "review-gated exception" in rec_ex_01["suggested_fix"]
    assert "previous-business-day substitution" in rec_ex_01["suggested_fix"]
    assert "until resolved" not in rec_ex_01["suggested_fix"].lower()

def test_qa_reconciliation_currency_ambiguous_row_creates_exception(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {"amount_review_status": "currency_ambiguous", "currency_native": "", "amount_native": 412, "amount_krw": "", "cashflow_role": "external_principal"},
    ])

    qa = qa_for_processed(tmp_path)

    assert "REC-EX-02" in set(qa["exception_id"])
    assert set(qa.loc[qa["exception_id"].eq("REC-EX-02"), "severity"]) == {"blocking"}

def test_qa_reconciliation_unit_ambiguous_row_creates_exception(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {"amount_review_status": "unit_ambiguous", "currency_native": "KRW", "amount_native": 412, "amount_krw": "", "cashflow_role": "external_principal"},
    ])

    qa = qa_for_processed(tmp_path)

    assert "REC-EX-03" in set(qa["exception_id"])
    assert set(qa.loc[qa["exception_id"].eq("REC-EX-03"), "severity"]) == {"blocking"}

def test_qa_reconciliation_normal_krw_principal_row_creates_no_exception(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(
        processed,
        cashflow_rows=[
            {"transaction_type": "deposit", "cashflow_role": "external_principal", "currency_native": "KRW", "settlement_amount_krw": 1000, "amount_krw": 1000, "amount_review_status": "ok", "affects_principal": True},
        ],
        amount_rows=[
            {"amount_review_status": "ok", "currency_native": "KRW", "amount_native": 1000, "amount_krw": 1000, "cashflow_role": "external_principal"},
        ],
    )

    qa = qa_for_processed(tmp_path)

    assert not set(qa["exception_id"]).intersection({f"REC-EX-{idx:02d}" for idx in range(1, 10)})

def test_qa_reconciliation_income_excluded_from_principal_is_advisory(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, income_rows=[
        {"income_type": "dividend", "currency_native": "KRW", "amount_native": 1000, "amount_krw": 1000, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
    ])

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-05"), "severity"])

    assert severities == {"advisory"}

def test_qa_reconciliation_exchange_excluded_from_principal_is_advisory(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, fx_rows=[
        {"fx_event_id": "FX-1", "fx_pair_status": "partial", "cashflow_role": "internal_fx_exchange", "is_internal_transfer": True, "amount_review_status": "ok", "affects_principal": False},
    ])

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-04"), "severity"])

    assert severities == {"advisory"}

def test_qa_reconciliation_quantity_price_in_principal_candidate_is_blocking(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, cashflow_rows=[
        {"transaction_type": "deposit", "cashflow_role": "external_principal", "quantity": 8, "price": 51.5, "amount_kind": "quantity", "amount_review_status": "unit_ambiguous", "affects_principal": True},
    ])

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-09"), "severity"])

    assert severities == {"blocking"}

def test_rec_ex_09_blocks_principal_candidate_with_quantity_or_price_unit(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, cashflow_rows=[
        {
            "transaction_type": "deposit",
            "cashflow_role": "external_principal",
            "currency_native": "KRW",
            "amount_krw": 1000,
            "amount_review_status": "ok",
            "affects_principal": True,
            "quantity_unit": "shares",
        },
        {
            "transaction_type": "withdrawal",
            "cashflow_role": "external_principal",
            "currency_native": "KRW",
            "amount_krw": 1000,
            "amount_review_status": "ok",
            "affects_principal": True,
            "price_unit": "native_per_share",
        },
    ])

    qa = qa_for_processed(tmp_path)
    rec_ex_09 = qa[qa["exception_id"].eq("REC-EX-09")]

    assert set(rec_ex_09["severity"]) == {"blocking"}
    assert len(rec_ex_09) == 2

def test_rec_ex_09_ignores_holdings_valuation_snapshots_with_quantity_price_units(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    amount_row = {
        "source_file_type": "holdings",
        "transaction_type": "deposit",
        "raw_quantity": 8,
        "raw_price": 51.5,
        "quantity_unit": "shares",
        "price_unit": "native_per_share",
        "amount_kind": "evaluation_amount",
        "amount_basis": "raw_native",
        "amount_krw": 1000,
        "cashflow_role": "valuation_snapshot",
        "affects_principal": False,
        "is_valuation_snapshot": True,
        "amount_review_status": "ok",
    }
    unit_mismatch_row = {
        "source_file_type": "holdings",
        "transaction_type": "deposit",
        "quantity": 8,
        "price": 51.5,
        "cashflow_role": "valuation_snapshot",
        "affects_principal": False,
    }
    holdings_row = {
        "source_file_type": "holdings",
        "transaction_type": "deposit",
        "quantity": 8,
        "price": 51.5,
        "quantity_unit": "shares",
        "price_unit": "native_per_share",
        "amount_kind": "evaluation_amount",
        "amount_basis": "raw_native",
        "amount_krw": 1000,
        "cashflow_role": "valuation_snapshot",
        "affects_principal": False,
        "is_valuation_snapshot": True,
        "amount_review_status": "ok",
    }
    write_reconciliation_qa_inputs(
        processed,
        amount_rows=[amount_row],
        unit_mismatch_rows=[unit_mismatch_row],
        holdings_rows=[holdings_row],
    )

    qa = qa_for_processed(tmp_path)

    assert qa[qa["exception_id"].eq("REC-EX-09")].empty

def test_qa_reconciliation_total_return_unavailable_creates_exception(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, reconciliation_rows=valid_reconciliation_summary_rows(
        total_assets_krw="",
        total_assets_status="fx_missing",
        total_return_krw="",
        total_return_status="fx_missing",
        residual_krw="",
        residual_status="unavailable",
    ))

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-06"), "severity"])

    assert severities == {"blocking"}

def test_qa_reconciliation_residual_threshold_creates_advisory(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, reconciliation_rows=valid_reconciliation_summary_rows(
        total_return_krw="20000",
        explained_profit_krw="18000",
        residual_krw="2000",
        residual_status="available",
    ))

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-07"), "severity"])

    assert severities == {"advisory"}

def test_qa_reconciliation_realized_unavailable_is_advisory(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, reconciliation_rows=valid_reconciliation_summary_rows(
        realized_pnl_krw="",
        realized_gain_krw="",
        realized_loss_krw="",
        realized_pnl_status="transaction_history_missing",
        explained_profit_status="transaction_history_missing",
        residual_krw="",
        residual_status="unavailable",
    ))

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-10"), "severity"])

    assert severities == {"advisory"}

def test_qa_reconciliation_non_krw_amount_without_provenance_creates_exception(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {"amount_review_status": "ok", "currency_native": "USD", "amount_native": 100, "amount_krw": 140000, "fx_rate_to_krw": "", "amount_krw_source": "", "amount_basis": "raw_native"},
    ])

    qa = qa_for_processed(tmp_path)
    severities = set(qa.loc[qa["exception_id"].eq("REC-EX-08"), "severity"])

    assert severities == {"blocking"}

def test_rec_ex_08_allows_zero_non_krw_native_and_krw_amount_without_fx(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {
            "amount_review_status": "ok",
            "currency_native": "USD",
            "amount_native": 0,
            "amount_krw": 0,
            "fx_rate_to_krw": "",
            "amount_krw_source": "raw_native",
            "amount_basis": "raw_native",
        },
    ])

    qa = qa_for_processed(tmp_path)

    assert "REC-EX-08" not in set(qa["exception_id"])

def test_rec_ex_08_allows_non_krw_amount_with_fx_rate_to_krw(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {
            "amount_review_status": "ok",
            "currency_native": "USD",
            "amount_native": 100,
            "amount_krw": 140000,
            "fx_rate_to_krw": 1400,
            "amount_krw_source": "derived_krw_from_fx",
            "amount_basis": "raw_native",
        },
    ])

    qa = qa_for_processed(tmp_path)

    assert "REC-EX-08" not in set(qa["exception_id"])

def test_rec_ex_08_allows_non_krw_amount_with_broker_krw_source(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, amount_rows=[
        {
            "amount_review_status": "ok",
            "currency_native": "USD",
            "amount_native": 100,
            "amount_krw": 140000,
            "fx_rate_to_krw": "",
            "amount_krw_source": "broker_krw",
            "amount_basis": "raw_native",
        },
    ])

    qa = qa_for_processed(tmp_path)

    assert "REC-EX-08" not in set(qa["exception_id"])

def test_inv_ex_11_reports_unclassified_rows_without_private_details(tmp_path: Path):
    private_tokens = [
        "PRIVATE_RAW_FILE_TOKEN",
        "PRIVATE_HEADER_TOKEN",
        "PRIVATE_ACCOUNT_TOKEN",
        "PRIVATE_TICKER_TOKEN",
        "PRIVATE_MEMO_TOKEN",
        "999999999",
    ]
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed)
    pd.DataFrame([{
        "source_file": "PRIVATE_RAW_FILE_TOKEN.xlsx",
        "raw_header": "PRIVATE_HEADER_TOKEN",
        "account_identifier": "PRIVATE_ACCOUNT_TOKEN",
        "ticker": "PRIVATE_TICKER_TOKEN",
        "raw_memo": "PRIVATE_MEMO_TOKEN",
        "amount": "999999999",
    }]).to_csv(processed / "unclassified_rows.csv", index=False)

    qa = qa_for_processed(tmp_path)
    inv_ex_11 = qa[qa["exception_id"].eq("INV-EX-11")]
    serialized = inv_ex_11.to_json(force_ascii=False)

    assert set(inv_ex_11["severity"]) == {"blocking"}
    assert len(inv_ex_11) == 1
    assert set(inv_ex_11["file"]) == {"70_Imports/processed/unclassified_rows.csv"}
    for token in private_tokens:
        assert token not in serialized

def test_inv_ex_11_distinguishes_quantity_only_non_money_unclassified_rows(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed)
    pd.DataFrame([{
        "source_file_type": "transaction_history",
        "market": "US",
        "asset_type": "etf",
        "transaction_type": "unknown",
        "cashflow_role": "unclassified",
        "amount_kind": "quantity",
        "amount_basis": "not_money",
        "amount_review_status": "not_applicable",
        "amount_normalization_status": "not_applicable",
        "currency_native": "USD",
        "amount_native": "",
        "amount_krw": "",
        "quantity": "1",
    }]).to_csv(processed / "unclassified_rows.csv", index=False)

    qa = qa_for_processed(tmp_path)
    inv_ex_11 = qa[qa["exception_id"].eq("INV-EX-11")]

    assert set(inv_ex_11["severity"]) == {"blocking"}
    assert len(inv_ex_11) == 1
    assert "quantity-only non-money" in inv_ex_11.iloc[0]["issue"]
    assert "cashflow/KRW totals" in inv_ex_11.iloc[0]["suggested_fix"]

def test_qa_flags_missing_performance_accounting_outputs_and_schema_gaps(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, write_required_outputs=False)
    pd.DataFrame(columns=["metric"]).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame(columns=[col for col in REALIZED_PNL_OUTPUT_COLUMNS if col != "cost_basis_method"]).to_csv(processed / "processed_realized_pnl.csv", index=False)

    qa = qa_for_processed(tmp_path)
    output_rows = qa[qa["exception_id"].eq("REC-EX-11")]
    text = "\n".join(output_rows["issue"].astype(str))

    assert set(output_rows["severity"]) == {"blocking"}
    assert "income_summary.csv is missing" in text
    assert "performance_summary.csv is missing required columns" in text
    assert "processed_realized_pnl.csv is missing required columns" in text

def test_qa_flags_realized_ledger_review_rows_and_lot_missing(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(
        processed,
        realized_rows=[
            {
                "ticker": "MISS",
                "quantity_sold": "2",
                "cost_basis_method": "fifo",
                "amount_review_status": "lot_missing",
                "fx_status": "not_required",
                "amount_review_reason": "sell quantity exceeds matched buy lots",
            },
            {
                "ticker": "FX",
                "cost_basis_method": "fifo",
                "amount_review_status": "fx_missing",
                "fx_status": "fx_missing",
            },
        ],
    )

    qa = qa_for_processed(tmp_path)

    assert set(qa.loc[qa["exception_id"].eq("REC-EX-12"), "severity"]) == {"advisory"}
    assert set(qa.loc[qa["exception_id"].eq("REC-EX-13"), "severity"]) == {"advisory"}

def test_qa_flags_fee_tax_double_count_and_large_performance_residual(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(
        processed,
        reconciliation_rows=valid_reconciliation_summary_rows(
            realized_trade_pnl_gross_krw="2000",
            realized_trade_pnl_net_krw="1820",
            unrealized_pnl_krw="0",
            dividend_income_krw="0",
            interest_income_krw="0",
            distribution_income_krw="0",
            fee_expense_krw="120",
            tax_expense_krw="60",
            explained_profit_krw="1640",
        ),
        performance_rows=valid_performance_summary_rows(
            reconciliation_residual_krw="5000",
        ),
    )

    qa = qa_for_processed(tmp_path)

    assert set(qa.loc[qa["exception_id"].eq("REC-EX-14"), "severity"]) == {"blocking"}
    assert set(qa.loc[qa["exception_id"].eq("REC-EX-15"), "severity"]) == {"advisory"}

def test_qa_flags_ambiguous_portfolio_dashboard_labels(tmp_path: Path):
    dashboard = tmp_path / "10_Dashboard"
    dashboard.mkdir(parents=True)
    (dashboard / "Portfolio.md").write_text(
        "# Portfolio\n\n"
        f"{AUTO_START}\n"
        '<span class="stock-kpi-label">Return</span>\n'
        "Portfolio Cost Basis\n"
        f"{AUTO_END}\n",
        encoding="utf-8",
    )
    write_reconciliation_qa_inputs(tmp_path / "70_Imports" / "processed")

    qa = qa_for_processed(tmp_path)

    assert set(qa.loc[qa["exception_id"].eq("REC-EX-17"), "severity"]) == {"blocking"}

def test_qa_flags_transaction_history_rows_in_current_holdings(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(
        processed,
        holdings_rows=[
            {
                "ticker": "TSLA",
                "asset_type": "stock",
                "source_file_type": "transaction_history",
                "balance_quantity": "1",
                "evaluation_amount": "100",
            },
        ],
    )

    qa = qa_for_processed(tmp_path)

    assert set(qa.loc[qa["exception_id"].eq("REC-EX-18"), "severity"]) == {"blocking"}

def test_qa_flags_non_krw_current_holding_official_value_without_provenance(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(
        processed,
        holdings_rows=[
            {
                "ticker": "AAPL",
                "asset_type": "stock",
                "source_file_type": "overseas_balance",
                "currency_native": "USD",
                "evaluation_amount_krw": "140000",
                "fx_rate_to_krw": "",
            },
        ],
    )

    qa = qa_for_processed(tmp_path)

    assert set(qa.loc[qa["exception_id"].eq("REC-EX-08"), "severity"]) == {"blocking"}

def test_generate_qa_exception_for_missing_thesis(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "A"
    company.mkdir(parents=True)
    (company / "Company.md").write_text("---\ntype: company\nticker: A\nmarket: KR\n---\n# A\n## 투자 논리(Thesis)\n- \n", encoding="utf-8")
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text("# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n", encoding="utf-8")
    qa = run_qa(vault)
    assert "INV-EX-03" in set(qa["exception_id"])

def test_generate_qa_exception_for_missing_sell_criteria(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "A"
    company.mkdir(parents=True)
    (company / "Company.md").write_text("---\ntype: company\nticker: A\nmarket: KR\n---\n# A\n## 투자 논리(Thesis)\n핵심 가정이 충분히 작성되어 있습니다.\n", encoding="utf-8")
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text("# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n", encoding="utf-8")
    qa = run_qa(vault)
    assert "INV-EX-08" in set(qa["exception_id"])

def test_placeholder_thesis_remains_unresolved(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "A"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: A\nmarket: KR\nasset_type: stock\n---\n"
        "# A\n"
        "## 투자 논리(Thesis)\n"
        "- 현재 사용자 확정 thesis는 미작성.\n"
        "- 관련 조사 및 사용자 재검토 필요.\n"
        "## 매도/비중축소 조건\n"
        "- 분기 실적에서 핵심 가정이 훼손되면 비중 축소를 검토한다.\n",
        encoding="utf-8",
    )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    qa = run_qa(vault)

    assert "INV-EX-03" in set(qa["exception_id"])

def test_placeholder_sell_criteria_remains_unresolved(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "A"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: A\nmarket: KR\nasset_type: stock\n---\n"
        "# A\n"
        "## 투자 논리(Thesis)\n"
        "- 핵심 고객 수요가 유지된다는 가정으로 보유한다.\n"
        "## 매도/비중축소 조건\n"
        "- 현재 명시적 매도·비중축소 기준은 미정.\n"
        "- 조사 필요 / 사용자 재검토 필요.\n",
        encoding="utf-8",
    )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    qa = run_qa(vault)

    assert "INV-EX-08" in set(qa["exception_id"])

def test_appx_no_loss_line_and_continue_hold_is_not_sell_criteria(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "APPX"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: APPX\nmarket: US\nasset_type: etf\n"
        "leveraged_etf_rule_link: \"[[05_Principles/Leveraged_ETF_Rules]]\"\n---\n"
        "# APPX\n"
        "## 투자 논리(Thesis)\n"
        "- 사용자는 별도의 손실 기준선을 설정하지 않았고 현재 판단은 계속 보유이다.\n"
        "## 매도/비중축소 조건\n"
        "- 손실 허용선: 명시적 기준 없음.\n"
        "- 추가 검토 필요: 레버리지 ETF 구조, 변동성 decay, 기초자산 thesis 훼손 여부.\n",
        encoding="utf-8",
    )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    qa = run_qa(vault)

    assert "INV-EX-08" in set(qa["exception_id"])

def test_inv_ex_05_uses_company_note_index_for_leveraged_holding_rule_link(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, holdings_rows=[{
        "ticker": "LEV3X",
        "security_name": "Synthetic Daily 3X ETF",
        "market": "US",
        "asset_type": "etf",
        "pnl_pct": 0,
    }])
    company = vault / "20_Companies" / "DifferentFolder"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: LEV3X\nmarket: US\nasset_type: etf\n"
        "leveraged_etf_rule_link: \"[[05_Principles/Leveraged_ETF_Rules]]\"\n---\n"
        "# Synthetic leveraged ETF\n"
        "## Thesis\n"
        "- Synthetic thesis text for rule-link coverage.\n"
        "## sell criteria\n"
        "- Synthetic sell criteria text for rule-link coverage.\n",
        encoding="utf-8",
    )

    qa = run_qa(vault, processed)

    assert "INV-EX-05" not in set(qa["exception_id"])

def test_inv_ex_04_uses_company_note_index_for_recent_loss_review(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, holdings_rows=[{
        "ticker": "LOSS",
        "security_name": "Synthetic Loss Holding",
        "market": "US",
        "asset_type": "stock",
        "pnl_pct": -12,
    }])
    company = vault / "20_Companies" / "ReviewedFolder"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: LOSS\nmarket: US\nasset_type: stock\n"
        f"last_review: {date.today().isoformat()}\n---\n"
        "# Synthetic loss holding\n"
        "## Thesis\n"
        "- Synthetic thesis text for review coverage.\n"
        "## sell criteria\n"
        "- Synthetic sell criteria text for review coverage.\n",
        encoding="utf-8",
    )

    qa = run_qa(vault, processed)

    assert "INV-EX-04" not in set(qa["exception_id"])

def test_inv_ex_04_flags_loss_holding_without_recent_review(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    write_reconciliation_qa_inputs(processed, holdings_rows=[{
        "ticker": "LOSS",
        "security_name": "Synthetic Loss Holding",
        "market": "US",
        "asset_type": "stock",
        "pnl_pct": -12,
    }])

    qa = run_qa(vault, processed)

    assert "INV-EX-04" in set(qa["exception_id"])

def test_nvdl_switching_threshold_counts_as_sell_criteria_with_open_details():
    text = (
        "# NVDL\n"
        "## 매도/비중축소 조건\n"
        "- 수익률 50% 이상 달성 시 NVDL에서 NVDA 본주로 스위칭하는 것을 원칙으로 한다.\n"
        "- [확인 필요] 수익률 측정 기준가, 전량/부분 스위칭 여부, 실행 시점.\n"
    )

    assert has_filled_section(text, ["매도", "비중축소", "sell criteria", "청산 조건"])

def test_samsung_ai_example_invalid_is_not_user_thesis(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "005930"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: 005930\nmarket: KR\nasset_type: stock\n---\n"
        "# 삼성전자\n"
        "## 투자 논리(Thesis)\n"
        "- 이전 AI 예시는 무효이며, 새 사용자 판단은 미작성. 조사 및 재검토 필요.\n"
        "## 매도/비중축소 조건\n"
        "- 현재 명시적 매도·비중축소 기준은 미정.\n",
        encoding="utf-8",
    )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    qa = run_qa(vault)

    assert "INV-EX-03" in set(qa["exception_id"])
    assert "INV-EX-08" in set(qa["exception_id"])

def test_samsung_template_prompt_labels_are_not_user_thesis(tmp_path: Path):
    vault = tmp_path
    company = vault / "20_Companies" / "005930"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: 005930\nmarket: KR\nasset_type: stock\n---\n"
        "# 삼성전자\n"
        "## 1) 투자 논리(Thesis)\n"
        "- 핵심 가정:\n"
        "- 내가 틀릴 수 있는 지점:\n"
        "## 2) 관찰 포인트\n"
        "- 메모리 가격/재고\n",
        encoding="utf-8",
    )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    qa = run_qa(vault)

    assert "INV-EX-03" in set(qa["exception_id"])

def test_qa_skips_stale_duplicate_company_note_for_current_holding(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {
            "ticker": "Aehr Test Systems (AEHR)",
            "security_name": "Aehr Test Systems (AEHR)",
            "account_type": "overseas",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "source_file_type": "overseas_balance",
        }
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    old = vault / "20_Companies" / "US00760J1088" / "Company.md"
    current = vault / "20_Companies" / "Aehr_Test_Systems_AEHR" / "Company.md"
    for path, ticker in [
        (old, "US00760J1088"),
        (current, "Aehr Test Systems (AEHR)"),
    ]:
        path.parent.mkdir(parents=True)
        path.write_text(
            f"---\ntype: company\nticker: \"{ticker}\"\nname: \"Aehr Test Systems\"\nmarket: US\nasset_type: stock\n---\n# A\n",
            encoding="utf-8",
        )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    qa = run_qa(vault)
    files = set(qa["file"])

    assert str(old.relative_to(vault)) not in files
    assert str(current.relative_to(vault)) in files
