import argparse
from datetime import date, datetime, timedelta, timezone
import json
import os
from pathlib import Path
import re
import sys
import tempfile
from types import SimpleNamespace
import uuid

import pandas as pd
import pytest

sys.path.append(str(Path(__file__).resolve().parents[3] / "scripts"))

from nh_importer import (
    BROKER_ADJACENT_DUPLICATE_CASHFLOW_SKIP_REASON,
    COLUMN_ALIASES,
    MULTIINDEX_COLUMN_SEPARATOR,
    OVERSEAS_CASHFLOW_AMOUNT_ONLY_SKIP_REASON,
    canonical_overseas_position_key,
    dedupe_holdings,
    extract_symbol_from_parentheses,
    import_raw_dir,
    infer_asset_type,
    infer_market,
    infer_source_file_type,
    is_leveraged_etf_name,
    load_workbook_tables,
    normalize_cash_currency,
    normalize_currency_and_fx_rate,
    normalize_dataframe,
    normalize_date,
    normalize_amount_fields,
    parse_korean_number,
    parse_korean_percent,
    classify_transaction_type,
)
from migrate_autogenerated_markers import resolve_company_note
import main as pipeline_main
from main import LIVE_WRITE_CONFIRMATION_TOKEN, build_parser, is_live_vault_path, live_write_guard_findings
from obsidian_writer import AUTO_END, AUTO_START, bootstrap_autogenerated_block, dashboard_content, qa_exception_cards, qa_exception_rollup_summary, replace_autogenerated_block, write_company_notes
from portfolio_model import apply_expense_fx_rates, apply_holdings_snapshot_asof_register, apply_holdings_snapshot_asof_register_to_source_index, apply_income_fx_rates, build_fx_rate_requirements, build_income_summary, build_monthly_cashflow_summary, build_performance_history, build_performance_summary, build_portfolio, build_portfolio_outputs, generate_reports, has_filled_section, load_fx_rates, resolve_fx_rate
from qa_checker import QA_EXCEPTION_ROLLUP_COLUMNS, REC_EX_01_ISSUE, REC_EX_01_SUGGESTED_FIX, build_qa_exception_rollup, run_qa
from quality_gate import (
    audit_output_schema_findings,
    audit_representation_findings,
    changed_entries,
    company_note_currency_findings,
    company_note_duplicate_findings,
    duplicate_overseas_holding_findings,
    expense_contract_findings,
    fx_internal_transfer_findings,
    fx_event_contract_findings,
    income_contract_findings,
    income_expense_separation_findings,
    income_reversal_review_findings,
    income_summary_contract_findings,
    invalid_currency_findings,
    live_vault_actual_write_guard_findings,
    non_krw_amount_without_fx_findings,
    dashboard_return_label_findings,
    official_krw_total_provenance_findings,
    principal_unit_misuse_findings,
    processed_cashflows_contract_findings,
    processed_output_schema_findings,
    performance_summary_findings,
    realized_pnl_cost_basis_findings,
    realized_pnl_review_findings,
    reconciliation_summary_findings,
    scan_generated_markdown_sensitive,
    snapshot_raw_files,
    unit_classification_findings,
)

from support import (
    AMOUNT_UNIT_AUDIT_COLUMNS,
    EXPENSE_OUTPUT_COLUMNS,
    FX_EVENT_COLUMNS,
    FX_RATE_REQUIREMENT_COLUMNS,
    INCOME_OUTPUT_COLUMNS,
    INCOME_SUMMARY_OUTPUT_COLUMNS,
    MONTHLY_CASHFLOW_SUMMARY_COLUMNS,
    PERFORMANCE_HISTORY_COLUMNS,
    PERFORMANCE_SUMMARY_METRICS,
    REALIZED_PNL_OUTPUT_COLUMNS,
    UNIT_MISMATCH_AUDIT_COLUMNS,
    assert_columns_present,
    fx_gate_row,
    is_blank_or_na,
    read_processed_csv,
    reconciliation_metrics,
    synthetic_rec_ex_01_rollup_rows,
    valid_performance_summary_rows,
    valid_reconciliation_summary_rows,
    write_stage8_output_inputs,
)


def test_cash_holdings_do_not_create_company_review_items(tmp_path: Path):
    # Wrapper venv paths are not integration-tested here because that would create host venvs.
    assert infer_asset_type("USD", "USD") == "cash"
    assert infer_asset_type("외화예수금", "") == "cash"
    assert normalize_cash_currency("USD", "USD", "KRW") == "USD"

    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"source_file": "source_cash.xlsx", "source_file_type": "overseas_balance", "account_type": "overseas"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {
            "ticker": "USD",
            "security_name": "USD",
            "account_type": "overseas",
            "market": "US",
            "asset_type": "cash",
            "currency": "USD",
            "balance_quantity": 1000,
            "evaluation_amount": 1000,
            "unrealized_pnl": 0,
            "pnl_pct": 0,
            "source_file_type": "overseas_balance",
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["ticker"]).to_csv(processed / "processed_transactions.csv", index=False)

    _, holdings, risk, review, _ = build_portfolio_outputs(processed, vault)
    assert set(holdings["asset_type"]) == {"cash"}
    assert risk.empty
    assert review.empty

    assert write_company_notes(vault, processed, create_companies=True) == []
    assert not (vault / "20_Companies" / "USD" / "Company.md").exists()

    company = vault / "20_Companies" / "USD"
    company.mkdir(parents=True)
    (company / "Company.md").write_text(
        "---\ntype: company\nticker: USD\nmarket: US\n---\n# USD\n",
        encoding="utf-8",
    )
    (vault / "10_Dashboard").mkdir()
    (vault / "10_Dashboard" / "QA_Exceptions.md").write_text(
        "# QA\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )
    qa = run_qa(vault)
    assert not {"INV-EX-03", "INV-EX-08"} & set(qa["exception_id"])

def test_company_note_writer_reuses_existing_canonical_note(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {
            "ticker": "테슬라 (TSLA)",
            "security_name": "테슬라 (TSLA)",
            "account_type": "overseas",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "source_file_type": "overseas_balance",
            "evaluation_amount": 100,
            "weight_pct": 1,
            "pnl_pct": 0,
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)

    existing = vault / "20_Companies" / "US88160R1014"
    existing.mkdir(parents=True)
    (existing / "Company.md").write_text(
        "---\ntype: company\nticker: US88160R1014\nname: 테슬라\nmarket: US\nasset_type: stock\n---\n"
        "# Tesla\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n",
        encoding="utf-8",
    )

    assert write_company_notes(vault, processed, create_companies=True) == []
    assert (existing / "Company.md").exists()
    assert not (vault / "20_Companies" / "테슬라_TSLA" / "Company.md").exists()
    assert "old" not in (existing / "Company.md").read_text(encoding="utf-8")

def test_company_note_create_treats_false_string_as_not_leveraged(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {
            "ticker": "NOK",
            "security_name": "Nokia",
            "account_type": "overseas",
            "market": "US",
            "asset_type": "stock",
            "currency": "USD",
            "source_file_type": "overseas_balance",
            "is_leveraged": "False",
            "evaluation_amount": 100,
            "weight_pct": 1,
            "pnl_pct": 0,
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)

    assert write_company_notes(vault, processed, create_companies=True) == []
    note = (vault / "20_Companies" / "NOK" / "Company.md").read_text(encoding="utf-8")

    assert 'currency: "USD"' in note
    assert "is_leveraged: false" in note
    assert "leveraged_etf_rule_link" not in note

def test_company_note_create_overrides_sol_ai_semiconductor_top2_to_etf(tmp_path: Path):
    vault = tmp_path
    processed = vault / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {
            "ticker": "0167A0",
            "security_name": "SOL AI반도체TOP2플러스",
            "account_type": "ISA",
            "market": "",
            "asset_type": "stock",
            "currency": "KRW",
            "source_file_type": "holdings",
            "is_leveraged": "False",
            "evaluation_amount": 10000,
            "weight_pct": 1,
            "pnl_pct": 0,
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)

    assert write_company_notes(vault, processed, create_companies=True) == []
    note = (vault / "20_Companies" / "0167A0" / "Company.md").read_text(encoding="utf-8")

    assert 'market: "KR"' in note
    assert 'asset_type: "etf"' in note
    assert 'currency: "KRW"' in note
    assert "is_leveraged: false" in note
    assert "### 1. 보유 목적" in note
    assert "- 현재 미작성 / 조사 필요" in note

def test_file_without_autogenerated_markers_is_not_overwritten(tmp_path: Path):
    note = tmp_path / "Manual.md"
    note.write_text("# Manual\n\nuser-written text\n", encoding="utf-8")
    ok, warning = replace_autogenerated_block(note, "generated")
    assert not ok
    assert "AUTO-GENERATED" in warning
    assert note.read_text(encoding="utf-8") == "# Manual\n\nuser-written text\n"

def test_import_review_dashboard_includes_holding_dedupe_summary(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "raw_file_count", "value": "2"},
        {"metric": "transaction_history_file_count", "value": "0"},
        {"metric": "holdings_file_count", "value": "2"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "holding_dedupe_candidate_rows", "value": "2"},
        {"metric": "holding_dedupe_retained_rows", "value": "1"},
        {"metric": "holding_dedupe_excluded_rows", "value": "1"},
        {"metric": "holding_dedupe_excluded_evaluation_amount", "value": "300"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame([
        {
            "ticker": "AEHR",
            "security_name": "Aehr Test Systems",
            "account_type": "overseas",
            "market": "US",
            "currency": "USD",
            "preferred_source": "overseas_balance",
            "dedupe_action": "retained_preferred",
            "dedupe_reason": "overseas_balance_retained_over_holdings_duplicate",
            "dedupe_excluded_count": 1,
            "dedupe_excluded_evaluation_amount": 300,
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)

    content = dashboard_content("Import_Review.md", processed)

    assert "## Holding dedupe" in content
    assert "AEHR" in content
    assert "overseas_balance_retained_over_holdings_duplicate" in content

def test_import_review_dashboard_surfaces_stage8_output_status(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "raw_file_count", "value": "1"},
        {"metric": "transaction_history_file_count", "value": "1"},
        {"metric": "holdings_file_count", "value": "0"},
        {"metric": "total_portfolio_value_status", "value": "unknown"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame([
        {"transaction_type": "unknown", "amount_review_status": "unit_ambiguous"},
    ]).to_csv(processed / "unclassified_rows.csv", index=False)
    write_stage8_output_inputs(
        processed,
        income_rows=[
            {
                "income_type": "dividend",
                "currency_native": "USD",
                "amount_native": 12.34,
                "amount_krw": "",
                "amount_review_status": "fx_missing",
                "affects_principal": False,
                "affects_profit": True,
            }
        ],
        expense_rows=[
            {
                "expense_type": "fee",
                "currency_native": "KRW",
                "amount_native": 100,
                "amount_krw": 100,
                "amount_review_status": "ok",
                "affects_principal": False,
                "affects_profit": True,
            }
        ],
        fx_rows=[
            {
                "fx_event_id": "FX-1",
                "fx_pair_status": "partial",
                "cashflow_role": "internal_fx_exchange",
                "is_internal_transfer": True,
                "affects_principal": False,
                "affects_profit": False,
                "amount_review_status": "ok",
            }
        ],
    )

    content = dashboard_content("Import_Review.md", processed)

    assert "## Processed Output Availability" in content
    assert "processed_income.csv" in content
    assert "processed_expenses.csv" in content
    assert "processed_fx_events.csv" in content
    assert "| processed_income.csv | True | 1 | ok |  |" in content
    assert "| processed_expenses.csv | True | 1 | ok |  |" in content
    assert "| processed_fx_events.csv | True | 1 | ok |  |" in content
    assert "## Review-Gated Status Counts" in content
    assert "income_fx_missing" in content
    assert "| fx_partial | 1 |" in content
    assert "| unclassified_rows | 1 |" in content

def test_import_review_dashboard_surfaces_amount_unit_audit_summary(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "raw_file_count", "value": "1"},
        {"metric": "transaction_history_file_count", "value": "1"},
        {"metric": "holdings_file_count", "value": "1"},
        {"metric": "total_portfolio_value_status", "value": "available"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    write_stage8_output_inputs(
        processed,
        income_rows=[
            {"income_type": "dividend", "currency_native": "KRW", "amount_native": 1000, "amount_krw": 1000, "amount_review_status": "ok", "affects_principal": False, "affects_profit": True},
        ],
        fx_rows=[
            {"fx_event_id": "FX-1", "fx_pair_status": "paired", "cashflow_role": "internal_fx_exchange", "is_internal_transfer": True, "amount_review_status": "ok"},
            {"fx_event_id": "FX-1", "fx_pair_status": "paired", "cashflow_role": "internal_fx_exchange", "is_internal_transfer": True, "amount_review_status": "ok"},
        ],
    )
    pd.DataFrame([
        {"amount_review_status": "fx_missing", "cashflow_role": "trade_settlement", "amount_kind": "trade_amount", "amount_krw": "", "quantity_unit": "", "price_unit": ""},
        {"amount_review_status": "currency_ambiguous", "cashflow_role": "income_dividend", "amount_kind": "cash_amount", "amount_krw": "", "quantity_unit": "", "price_unit": ""},
        {"amount_review_status": "unit_ambiguous", "cashflow_role": "internal_fx_exchange", "amount_kind": "quantity", "amount_krw": "", "quantity_unit": "shares", "price_unit": ""},
    ], columns=AMOUNT_UNIT_AUDIT_COLUMNS).to_csv(processed / "amount_unit_audit.csv", index=False)
    pd.DataFrame([
        {"amount_normalization_status": "fx_missing", "cashflow_role": "trade_settlement", "amount_krw": ""},
    ], columns=UNIT_MISMATCH_AUDIT_COLUMNS).to_csv(processed / "unit_mismatch_audit.csv", index=False)

    content = dashboard_content("Import_Review.md", processed)

    assert "## Amount/Unit Audit Summary" in content
    assert "| fx_missing_count | 1 |" in content
    assert "| currency_ambiguous_count | 1 |" in content
    assert "| unit_ambiguous_count | 1 |" in content
    assert "| internal_fx_events | 2 |" in content
    assert "| income_excluded_from_principal | 1 |" in content
    assert "| trade_settlements_excluded_from_principal | 1 |" in content
    assert "| raw_amount_rows_not_official_krw | 3 |" in content
    assert "| quantity_price_not_aggregated_as_money | 1 |" in content

def write_cashflow_dashboard_inputs(processed: Path, cashflow_rows: list[dict[str, object]]) -> None:
    processed.mkdir(parents=True, exist_ok=True)
    pd.DataFrame(cashflow_rows).to_csv(processed / "processed_cashflows.csv", index=False)
    pd.DataFrame(columns=["trade_date", "ticker", "security_name", "settlement_amount", "currency"]).to_csv(processed / "processed_dividends.csv", index=False)

def test_cashflow_dashboard_detail_displays_amount_krw_fallback(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "ticker": "",
            "security_name": "",
            "quantity": 0,
            "price": 0,
            "settlement_amount_krw": "",
            "amount_krw": 1234,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
    ])

    content = dashboard_content("Cashflows.md", processed)

    assert "principal_amount_krw" in content
    assert "1,234" in content
    assert "| net_principal | 1,234 |" in content

def test_cashflow_dashboard_principal_amount_prefers_settlement_amount_krw(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "ticker": "",
            "security_name": "",
            "quantity": 0,
            "price": 0,
            "settlement_amount_krw": 1000,
            "amount_krw": 999,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
    ])

    content = dashboard_content("Cashflows.md", processed)
    recent = content.split("## Recent Cashflows", 1)[1].split("## Details", 1)[0]

    assert "principal_amount_krw" in recent
    assert "1,000" in recent
    assert "| net_principal | 1,000 |" in content

def test_cashflow_dashboard_principal_detail_excludes_non_principal_rows(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "ticker": "",
            "security_name": "",
            "quantity": 0,
            "price": 0,
            "settlement_amount_krw": 777,
            "amount_krw": 777,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-07-11",
            "transaction_type": "dividend",
            "account_type": "comprehensive",
            "settlement_amount_krw": 111,
            "amount_krw": 111,
            "currency": "KRW",
            "cashflow_role": "income_dividend",
            "affects_principal": False,
            "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-07-12",
            "transaction_type": "interest",
            "account_type": "comprehensive",
            "settlement_amount_krw": 222,
            "amount_krw": 222,
            "currency": "KRW",
            "cashflow_role": "income_interest",
            "affects_principal": False,
            "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-07-13",
            "transaction_type": "exchange",
            "account_type": "comprehensive",
            "settlement_amount_krw": 333,
            "amount_krw": 333,
            "currency": "KRW",
            "cashflow_role": "internal_fx_exchange",
            "affects_principal": False,
            "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-07-14",
            "transaction_type": "buy",
            "account_type": "comprehensive",
            "ticker": "AAPL",
            "security_name": "Apple",
            "quantity": 1,
            "price": 10,
            "settlement_amount_krw": 444,
            "amount_krw": 444,
            "currency": "KRW",
            "cashflow_role": "trade_settlement",
            "affects_principal": False,
            "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-07-15",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "ticker": "",
            "security_name": "",
            "quantity": 0,
            "price": 0,
            "settlement_amount_krw": "",
            "amount_krw": "",
            "currency": "USD",
            "cashflow_role": "external_principal",
            "affects_principal": False,
            "amount_review_status": "fx_missing",
        },
    ])

    content = dashboard_content("Cashflows.md", processed)

    assert "| net_principal | 777 |" in content
    assert "## Principal exclusions and unresolved amounts" in content
    assert "| income_rows_excluded_from_principal | 2 |" in content
    assert "| fx_exchange_rows_excluded_from_principal | 1 |" in content
    assert "| trade_settlement_rows_excluded_from_principal | 1 |" in content
    assert "| fx_missing_rows | 1 |" in content
    recent_and_details = content.split("## Recent Cashflows", 1)[1]
    assert "111" not in recent_and_details
    assert "222" not in recent_and_details
    assert "333" not in recent_and_details
    assert "444" not in recent_and_details

def test_cashflow_dashboard_surfaces_income_expense_and_fx_summaries(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "ticker": "",
            "security_name": "",
            "quantity": 0,
            "price": 0,
            "settlement_amount_krw": 777,
            "amount_krw": 777,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
    ])
    write_stage8_output_inputs(
        processed,
        income_rows=[
            {
                "income_type": "dividend",
                "currency_native": "USD",
                "amount_native": 12.34,
                "amount_krw": "",
                "amount_review_status": "fx_missing",
                "affects_principal": False,
                "affects_profit": True,
            },
            {
                "income_type": "interest",
                "currency_native": "KRW",
                "amount_native": 1000,
                "amount_krw": 1000,
                "amount_review_status": "ok",
                "affects_principal": False,
                "affects_profit": True,
            },
        ],
        expense_rows=[
            {
                "expense_type": "fee",
                "currency_native": "KRW",
                "amount_native": 12,
                "amount_krw": 12,
                "amount_review_status": "ok",
                "affects_principal": False,
                "affects_profit": True,
            },
            {
                "expense_type": "tax",
                "currency_native": "USD",
                "amount_native": 1.5,
                "amount_krw": "",
                "amount_review_status": "fx_missing",
                "affects_principal": False,
                "affects_profit": True,
            },
        ],
        fx_rows=[
            {
                "fx_event_id": "FX-1",
                "leg": "KRW_OUT",
                "currency_native": "KRW",
                "amount_native": 140000,
                "amount_krw": 140000,
                "fx_pair_status": "paired",
                "cashflow_role": "internal_fx_exchange",
                "is_internal_transfer": True,
                "affects_principal": False,
                "affects_profit": False,
                "amount_review_status": "ok",
            },
            {
                "fx_event_id": "FX-1",
                "leg": "USD_IN",
                "currency_native": "USD",
                "amount_native": 100,
                "amount_krw": 140000,
                "fx_rate_to_krw": 1400,
                "fx_pair_status": "paired",
                "cashflow_role": "internal_fx_exchange",
                "is_internal_transfer": True,
                "affects_principal": False,
                "affects_profit": False,
                "amount_review_status": "ok",
            },
            {
                "fx_event_id": "FX-2",
                "leg": "PARTIAL",
                "currency_native": "KRW",
                "amount_native": 70000,
                "amount_krw": 70000,
                "fx_pair_status": "partial",
                "cashflow_role": "internal_fx_exchange",
                "is_internal_transfer": True,
                "affects_principal": False,
                "affects_profit": False,
                "amount_review_status": "ok",
            },
        ],
    )

    content = dashboard_content("Cashflows.md", processed)

    assert "| net_principal | 777 |" in content
    assert "## 현금성 수익" in content
    assert "배당" in content
    assert "이자" in content
    assert "분배금" in content
    assert "원천징수세" in content
    assert "KRW 환산 가능 배당/이자/분배금" in content
    assert '<span class="stock-kpi-label">USD dividend native total</span><strong>12.34 USD</strong>' in content
    assert "FX 미해결 income row count" in content
    assert '<span class="stock-kpi-label">income_status</span><strong>fx_missing: 1 / available: 1</strong>' in content
    assert "FX 누락 건수" in content
    assert "native 기준 수익" in content
    assert "KRW 환산 가능 수익" in content
    assert "## Expense summary" in content
    assert "## FX Events" in content
    assert "fx_missing: 1" in content
    assert "| interest | KRW | 1,000 | 1,000 | 0 | 0 | 1,000 | 1,000 | 1 | 0 | 0 | not_required: 1 | raw_native: 1 | available |" in content
    assert "| dividend | USD | 12.34 USD |  | 0 USD |  | 12.34 USD |  | 1 | 1 | 1 | fx_missing: 1 | fx_missing: 1 | fx_missing |" in content
    assert "| fee | 1 | 12 | 0 | ok: 1 |" in content
    assert "| paired_events | 1 |" in content
    assert "| partial_events | 1 |" in content
    assert "| internal_transfer_rows | 3 |" in content

def test_cashflow_dashboard_income_kpis_format_count_native_and_krw_values(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_stage8_output_inputs(
        processed,
        income_summary_rows=[
            {
                "income_type": "dividend",
                "currency_native": "KRW",
                "amount_native_sum": "31751.0",
                "amount_krw_sum": "31751.0",
                "tax_native_sum": "0",
                "tax_krw_sum": "0",
                "net_income_native": "31751.0",
                "net_income_krw": "31751.0",
                "row_count": "1",
                "fx_missing_row_count": "0",
                "amount_review_needed_row_count": "0",
                "income_status": "available",
            },
            {
                "income_type": "dividend",
                "currency_native": "USD",
                "amount_native_sum": "175.0",
                "amount_krw_sum": "",
                "tax_native_sum": "13190.0",
                "tax_krw_sum": "",
                "net_income_native": "-13015.0",
                "net_income_krw": "",
                "row_count": "19.0",
                "fx_missing_row_count": "19.0",
                "amount_review_needed_row_count": "19.0",
                "income_status": "fx_missing",
            },
        ],
    )

    content = dashboard_content("Cashflows.md", processed)
    raw_income_summary = pd.read_csv(processed / "income_summary.csv", dtype=str)
    raw_by_currency = raw_income_summary.set_index("currency_native")

    assert '<span class="stock-kpi-label">FX 누락 건수</span><strong>19</strong>' in content
    assert '<span class="stock-kpi-label">USD dividend native total</span><strong>175 USD</strong>' in content
    assert '<span class="stock-kpi-label">FX 미해결 income row count</span><strong>19</strong>' in content
    assert '<span class="stock-kpi-label">native 기준 수익</span><strong>KRW 31,751 / USD FX 검토 필요</strong>' in content
    assert '<span class="stock-kpi-label">KRW 환산 가능 수익</span><strong>31,751</strong>' in content
    assert "USD -13,015" not in content
    assert "31751.0" not in content
    assert "-13015.0" not in content
    assert "19.0" not in content
    assert raw_by_currency.loc["KRW", "net_income_native"] == "31751.0"
    assert raw_by_currency.loc["KRW", "net_income_krw"] == "31751.0"
    assert raw_by_currency.loc["USD", "net_income_native"] == "-13015.0"
    assert raw_by_currency.loc["USD", "fx_missing_row_count"] == "19.0"

def test_reconciliation_dashboard_surfaces_unit_aware_summary(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="120000",
        net_external_principal_krw="100000",
        total_return_krw="20000",
        total_return_status="available",
        residual_krw="0",
        residual_status="available",
        fx_missing_row_count="1",
        unit_ambiguous_row_count="2",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame([
        {
            "event_date": "2026-01-02",
            "currency": "USD",
            "use_case": "realized_pnl_trade_settlement",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "transaction_history",
            "status": "fx_missing",
        }
    ], columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)

    content = dashboard_content("Reconciliation.md", processed)

    assert "## Reconciliation Scope" in content
    assert "FX review gate" in content
    assert "Remaining FX requirements: `1`" in content
    assert "official-FX-unavailable review-gated exceptions" in content
    assert "previous-business-day substitution" in content
    assert "reconciliation_summary_role" in content
    assert "audit_status_residual" in content
    assert "total_return_alias_of" in content
    assert "performance_summary.cumulative_return_krw" in content
    assert "fee_tax_treatment" in content
    assert "gross_realized_pnl_minus_fee_tax_separate" in content
    assert "fx_pnl_treatment" in content
    assert "not_modeled_residual_context" in content
    assert "## Audit Totals" in content
    assert "total_assets_krw" in content
    assert "net_external_principal_krw" in content
    assert "total_return_krw" in content
    assert "total_return_pct" in content
    assert "## Explained Profit Components" in content
    assert "distribution_income_krw" in content
    assert "realized_pnl_krw" in content
    assert "## Residual Status" in content
    assert "## Realized PnL Ledger" in content
    assert "## Review-Gated Status Counts" in content
    assert "| fx_missing_row_count | 1 |" in content
    assert "| unit_ambiguous_row_count | 2 |" in content

def test_cashflow_dashboard_monthly_activity_sorts_by_month_and_shows_principal(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10", "transaction_type": "deposit", "account_type": "comprehensive",
            "settlement_amount": 1000, "settlement_amount_krw": 1000, "amount_krw": 1000, "currency": "KRW",
            "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-09-02", "transaction_type": "deposit", "account_type": "comprehensive",
            "settlement_amount": 2000, "settlement_amount_krw": 2000, "amount_krw": 2000, "currency": "KRW",
            "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-09-03", "transaction_type": "deposit", "account_type": "comprehensive",
            "ticker": "AAPL", "quantity": 1, "settlement_amount": 999, "settlement_amount_krw": 999, "amount_krw": 999, "currency": "KRW",
            "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-08-01", "transaction_type": "withdrawal", "account_type": "comprehensive",
            "settlement_amount": 500, "settlement_amount_krw": 500, "amount_krw": 500, "currency": "KRW",
            "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-08-15", "transaction_type": "exchange", "account_type": "comprehensive",
            "settlement_amount": 300, "settlement_amount_krw": 300, "amount_krw": 300, "currency": "KRW",
            "cashflow_role": "internal_fx_exchange", "affects_principal": False, "amount_review_status": "ok",
        },
    ])

    content = dashboard_content("Cashflows.md", processed)
    monthly = content.split("## Monthly activity", 1)[1].split("## Type summary", 1)[0]
    recent = content.split("## Recent Cashflows", 1)[1].split("## Details", 1)[0]

    assert "Net Principal" in content
    assert "preliminary KRW-normalized deposits - withdrawals" in content
    assert "Preliminary profit and reconciliation" in content
    assert "Portfolio/Cashflows differences are not official reconciliation yet." in content
    assert "Raw numeric values may mix KRW and USD." in content
    assert "quantity, unit price, total amount, fee, tax, FX rate, dividend, interest, and internal FX transfer" in content
    assert "reconciliation_status=currency_normalization_pending" in content
    assert "principal_amount_krw" in recent
    assert "| net_principal | 2,500 |" in content
    assert "weight_pct" not in monthly
    assert "exchange" not in monthly
    assert "999" not in content
    assert monthly.find("| 2025-09 ") < monthly.find("| 2025-08 ") < monthly.find("| 2025-07 ")
    assert "| 2025-09 | 1 | 2,000 | 0 | 2,000 | 2,500 |" in monthly
    assert "| 2025-08 | 1 | 0 | 500 | -500 | 500 |" in monthly

def test_cashflow_dashboard_adds_monthly_trend_graph_and_fallback_table(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "settlement_amount_krw": 1000,
            "amount_krw": 1000,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
        {
            "trade_date": "2025-08-01",
            "transaction_type": "withdrawal",
            "account_type": "comprehensive",
            "settlement_amount_krw": 500,
            "amount_krw": 500,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
    ])

    content = dashboard_content("Cashflows.md", processed)

    assert "## 월별 입출금 추이" in content
    assert "<svg" in content
    assert "Monthly Principal Cashflow Trend" in content
    assert "### Fallback table" in content
    assert "external_deposit_krw" in content
    assert "| 2025-07 | 1,000 | 0 | 1,000 | 1,000 |" in content
    assert "| 2025-08 | 0 | 500 | -500 | 500 |" in content

def test_portfolio_dashboard_snapshot_shows_value_cost_and_return(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "2"},
        {"metric": "total_cost", "value": "1500"},
        {"metric": "total_portfolio_value", "value": "1800"},
        {"metric": "total_unrealized_pnl", "value": "300"},
        {"metric": "pnl_pct", "value": "20"},
        {"metric": "loss_review_required_count", "value": "0"},
        {"metric": "leveraged_etf_count", "value": "0"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame([
        {"ticker": "AAA", "security_name": "AAA", "account_type": "ISA", "asset_type": "stock", "currency": "KRW", "evaluation_amount": 1000, "unrealized_pnl": 100, "pnl_pct": 11.11, "weight_pct": 55.56},
        {"ticker": "BBB", "security_name": "BBB", "account_type": "ISA", "asset_type": "stock", "currency": "KRW", "evaluation_amount": 800, "unrealized_pnl": 200, "pnl_pct": 33.33, "weight_pct": 44.44},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="1800",
        current_cash_krw="0",
        current_holding_assets_krw="1800",
        net_external_principal_krw="1500",
        total_return_krw="300",
        total_return_pct="20",
        unrealized_pnl_krw="300",
        realized_pnl_krw="0",
        dividend_income_krw="100",
        interest_income_krw="20",
        distribution_income_krw="30",
        fee_expense_krw="10",
        tax_expense_krw="5",
        residual_krw="0",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame(valid_performance_summary_rows(
        net_external_principal_krw="1500",
        external_deposit_krw="1500",
        external_withdrawal_krw="0",
        current_total_assets_krw="1810",
        current_cash_krw="10",
        current_holding_assets_krw="1800",
        cumulative_return_krw="310",
        cumulative_return_pct="20.666667",
        realized_trade_pnl_gross_krw="0",
        realized_trade_pnl_net_krw="0",
        unrealized_pnl_krw="300",
        dividend_income_krw="100",
        interest_income_krw="20",
        distribution_income_krw="30",
        income_total_krw="150",
        fee_expense_krw="10",
        tax_expense_krw="5",
        explained_profit_krw="445",
        reconciliation_residual_krw="-135",
    )).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame([
        {
            "income_type": "dividend",
            "currency_native": "KRW",
            "amount_native_sum": "150",
            "amount_krw_sum": "150",
            "tax_native_sum": "0",
            "tax_krw_sum": "0",
            "net_income_native": "150",
            "net_income_krw": "150",
            "row_count": "3",
            "fx_missing_row_count": "0",
            "amount_review_needed_row_count": "0",
            "income_status": "available",
        },
        {
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native_sum": "175",
            "amount_krw_sum": "",
            "tax_native_sum": "0",
            "tax_krw_sum": "",
            "net_income_native": "175",
            "net_income_krw": "",
            "row_count": "19",
            "fx_missing_row_count": "19",
            "amount_review_needed_row_count": "19",
            "income_status": "fx_missing",
        },
    ], columns=INCOME_SUMMARY_OUTPUT_COLUMNS).to_csv(processed / "income_summary.csv", index=False)
    pd.DataFrame([
        {
            "event_date": "2026-01-02",
            "currency": "USD",
            "use_case": "income_dividend",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "income",
            "status": "fx_missing",
        }
    ], columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)

    assert "FX review gate" in content
    assert "Remaining FX requirements: `1`" in content
    assert "official-FX-unavailable review-gated exceptions" in content
    assert "today-rate backfill" in content
    assert "## 전체 투자 성과" in content
    assert "## 현재 보유분" in content
    assert "## 원금/원가 브릿지" in content
    assert "현재 보유분 원가" in content
    assert "current holdings cost basis; not net external principal" in content
    assert "현재 보유분 평가금액" in content
    assert "현재 보유분 미실현손익" in content
    assert "현재 보유분 평가수익률" in content
    assert "단순 누적손익 (KRW)" in content
    assert "단순 누적수익률" in content
    assert "현재 총자산 (KRW)" in content
    assert "인식된 현금 (KRW)" in content
    assert "원금/보유원가 차이 (KRW)" in content
    assert "not cash and is not confirmed realized profit" in content
    assert "KRW 환산 가능 배당/이자/분배금" in content
    assert '<span class="stock-kpi-label">KRW 환산 가능 배당/이자/분배금</span><strong>150</strong>' in content
    assert '<span class="stock-kpi-label">USD 배당</span><strong>175 USD</strong>' in content
    assert '<span class="stock-kpi-label">FX 미해결 income row</span><strong>19</strong>' in content
    assert '<span class="stock-kpi-label">현금성 수익 상태</span><strong>available: 1 / fx_missing: 1</strong>' in content
    assert "수집된 배당/이자/분배금" not in content
    assert "수수료/세금" in content
    assert "Portfolio Cost Basis" not in content
    assert '<span class="stock-kpi-label">Return</span>' not in content
    assert "Total Return %" not in content
    assert "Preliminary profit and reconciliation" in content
    assert "Final total return should not be considered official until unit/currency-aware processing is complete." in content
    assert "profit_result_status=preliminary" in content
    assert "<strong>1,500</strong>" in content
    assert "<strong>1,810</strong>" in content
    assert '<span class="stock-kpi-label">단순 누적손익 (KRW)</span><strong>310</strong>' in content
    assert '<span class="stock-kpi-label">단순 누적수익률</span><strong>20.67%</strong>' in content
    assert '<span class="stock-kpi-label">현재 총자산 (KRW)</span><strong>1,810</strong>' in content
    assert '<span class="stock-kpi-label">인식된 현금 (KRW)</span><strong>10</strong>' in content
    assert '<span class="stock-kpi-label">원금/보유원가 차이 (KRW)</span><strong>0</strong>' in content
    assert '<span class="stock-kpi-label">설명되지 않은 차이 (KRW)</span><strong>-135</strong>' in content
    assert "<strong>-135</strong>" in content

def test_portfolio_dashboard_adds_account_principal_bridge_without_account_returns(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "4"},
        {"metric": "total_cost", "value": "3070"},
        {"metric": "total_portfolio_value", "value": "3150"},
        {"metric": "total_unrealized_pnl", "value": "-70"},
        {"metric": "pnl_pct", "value": "-2.23"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="3150",
        current_cash_krw="150",
        current_holding_assets_krw="3000",
        net_external_principal_krw="2800",
        total_return_krw="350",
        total_return_pct="12.5",
        unrealized_pnl_krw="-70",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame(valid_performance_summary_rows(
        net_external_principal_krw="2800",
        external_deposit_krw="3000",
        external_withdrawal_krw="200",
        current_total_assets_krw="3150",
        current_cash_krw="150",
        current_holding_assets_krw="3000",
        cumulative_return_krw="350",
        cumulative_return_pct="12.5",
        unrealized_pnl_krw="-70",
    )).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame([
        {"ticker": "ISA_STOCK", "security_name": "ISA Stock", "account_type": "ISA", "asset_type": "stock", "currency": "KRW", "evaluation_amount": 900, "evaluation_amount_krw": 900, "unrealized_pnl": 100, "unrealized_pnl_krw": 100},
        {"ticker": "ISA_CASH", "security_name": "ISA Cash", "account_type": "ISA", "asset_type": "cash", "currency": "KRW", "evaluation_amount": 50, "evaluation_amount_krw": 50, "unrealized_pnl": 0, "unrealized_pnl_krw": 0},
        {"ticker": "COMP_STOCK", "security_name": "Comprehensive Stock", "account_type": "comprehensive", "asset_type": "stock", "currency": "KRW", "evaluation_amount": 1800, "evaluation_amount_krw": 1800, "unrealized_pnl": -200, "unrealized_pnl_krw": -200},
        {"ticker": "COMP_CASH", "security_name": "Comprehensive Cash", "account_type": "comprehensive", "asset_type": "cash", "currency": "KRW", "evaluation_amount": 100, "evaluation_amount_krw": 100, "unrealized_pnl": 0, "unrealized_pnl_krw": 0},
        {"ticker": "OVERSEAS_STOCK", "security_name": "Overseas Stock", "account_type": "overseas", "asset_type": "stock", "currency": "USD", "evaluation_amount": 1, "evaluation_amount_krw": 300, "unrealized_pnl": 0.1, "unrealized_pnl_krw": 30},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame([
        {"trade_date": "2026-01-01", "transaction_type": "deposit", "account_type": "ISA", "ticker": "", "security_name": "", "quantity": 0, "price": 0, "settlement_amount_krw": 1000, "amount_krw": 1000, "currency": "KRW", "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok"},
        {"trade_date": "2026-01-02", "transaction_type": "withdrawal", "account_type": "ISA", "ticker": "", "security_name": "", "quantity": 0, "price": 0, "settlement_amount_krw": 200, "amount_krw": 200, "currency": "KRW", "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok"},
        {"trade_date": "2026-01-03", "transaction_type": "deposit", "account_type": "comprehensive", "ticker": "", "security_name": "", "quantity": 0, "price": 0, "settlement_amount_krw": 2000, "amount_krw": 2000, "currency": "KRW", "cashflow_role": "external_principal", "affects_principal": True, "amount_review_status": "ok"},
        {"trade_date": "2026-01-04", "transaction_type": "dividend", "account_type": "comprehensive", "ticker": "", "security_name": "", "quantity": 0, "price": 0, "settlement_amount_krw": 999, "amount_krw": 999, "currency": "KRW", "cashflow_role": "income_dividend", "affects_principal": False, "amount_review_status": "ok"},
        {"trade_date": "2026-01-05", "transaction_type": "exchange", "account_type": "comprehensive", "ticker": "", "security_name": "", "quantity": 0, "price": 0, "settlement_amount_krw": 888, "amount_krw": 888, "currency": "KRW", "cashflow_role": "internal_fx_exchange", "affects_principal": False, "amount_review_status": "ok"},
        {"trade_date": "2026-01-06", "transaction_type": "deposit", "account_type": "comprehensive", "ticker": "", "security_name": "", "quantity": 0, "price": 0, "settlement_amount_krw": 777, "amount_krw": 777, "currency": "KRW", "cashflow_role": "external_principal", "affects_principal": False, "amount_review_status": "ok"},
    ]).to_csv(processed / "processed_cashflows.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)
    section = content.split("## 계좌별 원금/평가 브릿지", 1)[1].split("## 검토/상태", 1)[0]

    assert "계좌별 공식 TWR/MWR 수익률이 아닙니다" in section
    assert "`종합+해외`는 종합 원금 흐름과 해외잔고 valuation snapshot을 함께 보여주는 display bucket" in section
    assert "| account | net_external_principal_krw | current_value_krw | recognized_cash_krw | holdings_cost_krw | unrealized_pnl_krw | principal_to_cost_gap_krw |" in section
    assert "| ISA | 800 | 950 | 50 | 800 | 100 | -50 |" in section
    assert "| 종합+해외 | 2,000 | 2,200 | 100 | 2,270 | -170 | -370 |" in section
    assert "| TOTAL | 2,800 | 3,150 | 150 | 3,070 | -70 | -420 |" in section
    assert "| 종합 |" not in section
    assert "| 해외/해외잔고 |" not in section
    assert "999" not in section
    assert "888" not in section
    assert "777" not in section
    assert "account-level return" not in content.lower()
    assert "official TWR/MWR" not in content

def test_portfolio_dashboard_formats_numbers_without_changing_processed_csv(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "0"},
        {"metric": "total_cost", "value": "37586238.0"},
        {"metric": "total_portfolio_value", "value": "52409827.0"},
        {"metric": "total_unrealized_pnl", "value": "14823589.0"},
        {"metric": "pnl_pct", "value": "39.44"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame(columns=["ticker", "security_name", "account_type", "asset_type", "currency"]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="52409827.0",
        current_cash_krw="0",
        current_holding_assets_krw="52409827.0",
        net_external_principal_krw="52377996.0",
        total_return_krw="31831.0",
        total_return_pct="0.060778",
        residual_krw="0",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame(valid_performance_summary_rows(
        net_external_principal_krw="52377996.0",
        external_deposit_krw="52377996.0",
        external_withdrawal_krw="0",
        current_total_assets_krw="52409827.0",
        current_cash_krw="0",
        current_holding_assets_krw="52409827.0",
        cumulative_return_krw="31831.0",
        cumulative_return_pct="0.060778",
        fee_expense_krw="31000.0",
        tax_expense_krw="709.0",
        reconciliation_residual_krw="0",
    )).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame([
        {
            "income_type": "dividend",
            "currency_native": "USD",
            "amount_native_sum": "175",
            "amount_krw_sum": "",
            "tax_native_sum": "0",
            "tax_krw_sum": "",
            "net_income_native": "175",
            "net_income_krw": "",
            "row_count": "1",
            "fx_missing_row_count": "1",
            "amount_review_needed_row_count": "1",
            "income_status": "fx_missing",
        },
    ], columns=INCOME_SUMMARY_OUTPUT_COLUMNS).to_csv(processed / "income_summary.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)
    raw_summary = pd.read_csv(processed / "portfolio_summary.csv", dtype=str)
    raw_performance = pd.read_csv(processed / "performance_summary.csv", dtype=str)
    raw_summary_values = dict(zip(raw_summary["metric"], raw_summary["value"].fillna("")))
    raw_values = dict(zip(raw_performance["metric"], raw_performance["value"].fillna("")))

    assert "52,409,827" in content
    assert "37,586,238" in content
    assert "14,823,589" in content
    assert "31,709" in content
    assert "31,831" in content
    assert "0.06%" in content
    assert '<span class="stock-kpi-label">USD 배당</span><strong>175 USD</strong>' in content
    assert "37586238.0" not in content
    assert "52409827.0" not in content
    assert "14823589.0" not in content
    assert "31709.0" not in content
    assert raw_summary_values["total_cost"] == "37586238.0"
    assert raw_summary_values["total_portfolio_value"] == "52409827.0"
    assert raw_summary_values["total_unrealized_pnl"] == "14823589.0"
    assert raw_values["current_total_assets_krw"] == "52409827.0"
    assert raw_values["cumulative_return_krw"] == "31831.0"
    assert raw_values["fee_expense_krw"] == "31000.0"
    assert raw_values["tax_expense_krw"] == "709.0"
    assert "추후 import 누적 후 표시" in content

def test_dashboard_percent_formatting_preserves_integer_trailing_zeroes(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    write_cashflow_dashboard_inputs(processed, [
        {
            "trade_date": "2025-07-10",
            "transaction_type": "deposit",
            "account_type": "comprehensive",
            "settlement_amount_krw": 1000,
            "amount_krw": 1000,
            "currency": "KRW",
            "cashflow_role": "external_principal",
            "affects_principal": True,
            "amount_review_status": "ok",
        },
    ])

    content = dashboard_content("Cashflows.md", processed)

    assert "| deposit | 1 | 100% |" in content
    assert "| deposit | 1 | 1% |" not in content

def test_portfolio_dashboard_performance_history_two_points_renders_graph_and_fallback(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "0"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame(columns=["ticker", "security_name", "account_type", "asset_type", "currency"]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows()).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame(valid_performance_summary_rows()).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame([
        {
            "snapshot_month": "2026-04",
            "snapshot_date": "2026-04-30",
            "cumulative_principal_krw": "100000",
            "current_total_assets_krw": "110000",
            "cumulative_return_krw": "10000",
            "cumulative_return_pct": "10",
            "performance_status": "available",
        },
        {
            "snapshot_month": "2026-05",
            "snapshot_date": "2026-05-24",
            "cumulative_principal_krw": "120000",
            "current_total_assets_krw": "125000",
            "cumulative_return_krw": "5000",
            "cumulative_return_pct": "4.166667",
            "performance_status": "available",
        },
    ], columns=PERFORMANCE_HISTORY_COLUMNS).to_csv(processed / "performance_history.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)
    section = content.split("## 월별 원금/누적수익 추이", 1)[1].split("## 현재 보유분", 1)[0]

    assert "<svg" in section
    assert "Monthly Principal and Cumulative Return Trend" in section
    assert "historical total assets는 raw transactions로 추정하지 않습니다" in section
    assert "### 대체 표시 표" in section
    assert not re.search(r'<text class="label" x="8" y="[^"]+">-?[\d,]+\.\d+</text>', section)
    assert "| 2026-05 | 2026-05-24 | 120,000 | 125,000 | 5,000 | 4.17% | available |" in section

def test_portfolio_dashboard_surfaces_reconciliation_status_and_currency_exposure(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "2"},
        {"metric": "total_cost", "value": "1500"},
        {"metric": "total_portfolio_value", "value": "1800"},
        {"metric": "total_unrealized_pnl", "value": "300"},
        {"metric": "pnl_pct", "value": "20"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="",
        total_assets_status="fx_missing",
        current_cash_krw="0",
        net_external_principal_krw="1500",
        total_return_krw="",
        total_return_status="fx_missing",
        unrealized_pnl_krw="",
        realized_pnl_krw="",
        realized_pnl_status="unit_ambiguous",
        residual_krw="",
        residual_status="unavailable",
        fx_missing_row_count="1",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame([
        {"ticker": "AAA", "security_name": "AAA", "account_type": "ISA", "asset_type": "stock", "currency": "KRW", "currency_native": "KRW", "evaluation_amount": 1000, "evaluation_amount_krw": 1000, "unrealized_pnl": 100, "pnl_pct": 11.11, "weight_pct": 55.56},
        {"ticker": "AAPL", "security_name": "Apple", "account_type": "overseas", "asset_type": "stock", "currency": "USD", "currency_native": "USD", "evaluation_amount": 100, "evaluation_amount_krw": "", "amount_review_status": "fx_missing", "weight_pct": 44.44},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame([
        {"source_file": "PRIVATE_RAW_EXPORT.xlsx", "source_file_type": "holdings_or_balance_source", "account_type": "ISA"},
        {"source_file": "PRIVATE_TX_HISTORY.xlsx", "source_file_type": "transaction_history_source", "account_type": "comprehensive"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame([
        {"trade_date": "2026-01-01", "transaction_type": "buy", "source_file_type": "transaction_history"},
        {"trade_date": "2026-01-02", "transaction_type": "sell", "source_file_type": "transaction_history"},
    ]).to_csv(processed / "processed_transactions.csv", index=False)
    pd.DataFrame([
        {"realized_trade_pnl_gross_krw": "50", "realized_trade_pnl_net_krw": "45", "amount_review_status": "ok"},
        {"realized_trade_pnl_gross_krw": "", "realized_trade_pnl_net_krw": "", "amount_review_status": "fx_missing"},
    ], columns=REALIZED_PNL_OUTPUT_COLUMNS).to_csv(processed / "processed_realized_pnl.csv", index=False)
    pd.DataFrame([
        {"income_type": "dividend", "currency_native": "KRW", "amount_review_status": "ok"},
    ]).to_csv(processed / "processed_income.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)

    assert "현재 총자산 상태" in content
    assert "fx_missing" in content
    assert "성과 상태" in content
    assert "not official" in content
    assert "Portfolio cards show display subtotals" in content
    assert "현재 평가금액 (보유분 기준)" in content
    assert "current holdings valuation fallback; recognized cash shown separately" in content
    assert "not TWR/MWR" in content
    assert "단순 누적손익 (KRW)" in content
    assert '<span class="stock-kpi-label">현재 평가금액 (보유분 기준)</span><strong>1,800</strong>' in content
    assert '<span class="stock-kpi-label">단순 누적손익 (KRW)</span><strong>300</strong>' in content
    assert '<span class="stock-kpi-label">단순 누적수익률</span><strong>20%</strong>' in content
    assert "원금/원가 브릿지" in content
    assert "원금/보유원가 차이 (KRW)" in content
    assert '<span class="stock-kpi-label">인식된 현금 (KRW)</span><strong>0</strong>' in content
    assert "실현손익 상태" in content
    assert "unit_ambiguous" in content
    assert "KRW available subtotal; gated rows excluded" not in content
    assert '<span class="stock-kpi-label">실현손익 (KRW)</span>' not in content
    assert "설명되지 않은 차이" not in content
    assert "<strong>1,800</strong>" in content
    assert "<strong>1,500</strong>" in content
    assert "<strong>300</strong>" in content
    assert "<strong>20%</strong>" in content
    assert "## 정규화 통화 노출" in content
    assert "| USD | 1 |  | 1 | 44.44% |" in content
    assert "## 이번 업데이트 반영 상태" in content
    assert "이번 업데이트 반영 설명" in content
    assert '<span class="stock-kpi-label">거래 ledger row</span><strong>2</strong>' in content
    assert '<span class="stock-kpi-label">실현손익 ledger row</span><strong>2</strong>' in content
    assert '<span class="stock-kpi-label">수익 ledger row</span><strong>1</strong>' in content
    assert "실행별 delta가 아니라" in content
    assert "current holdings로 승격하지 않습니다" in content
    assert "### 보유 snapshot 최신성" in content
    assert "현재 보유 source 최신성" in content
    assert '<span class="stock-kpi-label">보유/잔고 source</span><strong>있음</strong>' in content
    assert '<span class="stock-kpi-label">snapshot 날짜</span><strong>날짜 없음</strong>' in content
    assert "날짜 없음" in content
    assert "거래내역 추정이 아니라" in content
    assert "현재 보유로 승격하지 않음" in content
    assert "PRIVATE_RAW_EXPORT.xlsx" not in content
    assert "PRIVATE_TX_HISTORY.xlsx" not in content

def test_portfolio_dashboard_uses_explicit_holdings_snapshot_date(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "1"},
        {"metric": "total_cost", "value": "1000"},
        {"metric": "total_portfolio_value", "value": "1200"},
        {"metric": "total_unrealized_pnl", "value": "200"},
        {"metric": "pnl_pct", "value": "20"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="1200",
        total_assets_status="available",
        current_cash_krw="0",
        net_external_principal_krw="1000",
        total_return_krw="200",
        total_return_status="available",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame([
        {
            "ticker": "AAA",
            "security_name": "AAA",
            "account_type": "ISA",
            "asset_type": "stock",
            "currency": "KRW",
            "snapshot_date": "2026-06-28",
            "evaluation_amount": 1200,
            "evaluation_amount_krw": 1200,
            "unrealized_pnl": 200,
            "pnl_pct": 20,
            "weight_pct": 100,
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame([
        {"source_file": "source_holdings.xlsx", "source_file_type": "holdings", "account_type": "ISA", "snapshot_date": "2026-06-28"},
    ]).to_csv(processed / "source_file_index.csv", index=False)
    pd.DataFrame(columns=["trade_date", "transaction_type", "source_file_type"]).to_csv(processed / "processed_transactions.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)
    snapshot_section = content.split("### 보유 snapshot 최신성", 1)[1].split("### 현재 보유 source 최신성", 1)[0]

    assert '<span class="stock-kpi-label">snapshot 날짜</span><strong>2026-06-28</strong>' in snapshot_section
    assert "날짜 없음" not in snapshot_section

def test_portfolio_dashboard_labels_user_confirmed_snapshot_date(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "1"},
        {"metric": "total_cost", "value": "1000"},
        {"metric": "total_portfolio_value", "value": "1200"},
        {"metric": "total_unrealized_pnl", "value": "200"},
        {"metric": "pnl_pct", "value": "20"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="1200",
        total_assets_status="available",
        current_cash_krw="0",
        net_external_principal_krw="1000",
        total_return_krw="200",
        total_return_status="available",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame([
        {
            "ticker": "SYNTH",
            "security_name": "Synthetic Holding",
            "account_type": "ISA",
            "asset_type": "stock",
            "currency": "KRW",
            "snapshot_date": "2026-07-02",
            "snapshot_date_source": "user_confirmed_asof_register",
            "snapshot_date_status": "user_confirmed",
            "evaluation_amount": 1200,
            "evaluation_amount_krw": 1200,
            "unrealized_pnl": 200,
            "pnl_pct": 20,
            "weight_pct": 100,
        },
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(columns=["trade_date", "transaction_type", "source_file_type"]).to_csv(processed / "processed_transactions.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)

    assert "2026-07-02" in content
    assert "사용자 확인 기준일" in content
    assert "broker export 날짜 아님" in content

def test_portfolio_dashboard_summarizes_reviewed_fx_unavailable_exceptions(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    cache = tmp_path / "70_Imports" / "cache"
    processed.mkdir(parents=True)
    cache.mkdir(parents=True)
    pd.DataFrame([
        {"metric": "holding_count", "value": "1"},
        {"metric": "total_cost", "value": "1000"},
        {"metric": "total_portfolio_value", "value": "1200"},
        {"metric": "total_unrealized_pnl", "value": "200"},
        {"metric": "pnl_pct", "value": "20"},
        {"metric": "total_portfolio_value_status", "value": "available"},
        {"metric": "balance_data_available", "value": "True"},
    ]).to_csv(processed / "portfolio_summary.csv", index=False)
    pd.DataFrame([
        {"ticker": "AAA", "security_name": "AAA", "account_type": "ISA", "asset_type": "stock", "currency": "KRW", "evaluation_amount": 1200, "evaluation_amount_krw": 1200, "weight_pct": 100},
    ]).to_csv(processed / "processed_holdings.csv", index=False)
    pd.DataFrame(valid_reconciliation_summary_rows(
        total_assets_krw="",
        total_assets_status="fx_missing",
        current_cash_krw="0",
        net_external_principal_krw="1000",
        total_return_krw="",
        total_return_status="fx_missing",
        residual_status="unavailable",
        fx_missing_row_count="2",
    )).to_csv(processed / "reconciliation_summary.csv", index=False)
    pd.DataFrame(valid_performance_summary_rows(
        current_total_assets_krw="",
        current_cash_krw="",
        net_external_principal_krw="1000",
        cumulative_return_krw="",
        cumulative_return_pct="",
        performance_status="fx_missing",
    )).to_csv(processed / "performance_summary.csv", index=False)
    pd.DataFrame([
        {
            "event_date": "2026-01-02",
            "currency": "USD",
            "use_case": "income_dividend",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "income",
            "status": "fx_missing",
        },
        {
            "event_date": "2026-01-05",
            "currency": "USD",
            "use_case": "realized_pnl_trade_settlement",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "transaction_history",
            "status": "fx_missing",
        },
    ], columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)
    pd.DataFrame([
        {
            "requirement_key": "2026-01-02|USD|income_dividend",
            "decision": "still_review_gated",
            "reason_code": "official_fx_unavailable_same_date",
            "operator_review_label": "official_fx_unavailable_non_business_day",
            "provider": "eximbank",
        },
    ]).to_csv(cache / "fx_unavailable_exceptions.csv", index=False)

    content = dashboard_content("Portfolio.md", processed)
    reconciliation_content_text = dashboard_content("Reconciliation.md", processed)

    assert "Remaining FX requirements: `2`" in content
    assert "reviewed official-FX-unavailable keys `1`; unreviewed keys `1`" in content
    assert "The private exception register is review context only" in content
    assert "not FX rate provenance, archive promotion, or REC closure" in content
    assert '<span class="stock-kpi-label">FX reviewed unavailable</span><strong>1</strong>' in content
    assert '<span class="stock-kpi-label">FX unreviewed requirements</span><strong>1</strong>' in content
    assert "reviewed official-FX-unavailable keys `1`; unreviewed keys `1`" in reconciliation_content_text

def test_qa_and_review_dashboards_summarize_reviewed_fx_unavailable_exceptions(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    cache = tmp_path / "70_Imports" / "cache"
    processed.mkdir(parents=True)
    cache.mkdir(parents=True)
    pd.DataFrame([
        {
            "event_date": "2026-01-02",
            "currency": "USD",
            "use_case": "income_dividend",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "income",
            "status": "fx_missing",
        },
    ], columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)
    pd.DataFrame([
        {
            "requirement_key": "2026-01-02|USD|income_dividend",
            "decision": "still_review_gated",
            "reason_code": "official_fx_unavailable_same_date",
            "operator_review_label": "official_fx_unavailable_non_business_day",
            "provider": "eximbank",
        },
    ]).to_csv(cache / "fx_unavailable_exceptions.csv", index=False)
    qa = synthetic_rec_ex_01_rollup_rows()
    qa.to_csv(processed / "qa_exceptions.csv", index=False)
    build_qa_exception_rollup(qa).to_csv(processed / "qa_exception_rollup.csv", index=False)
    pd.DataFrame([
        {
            "severity": "blocking",
            "reason": "FX provenance review gate",
            "suggested_action": "Review same-date FX provenance.",
        },
    ]).to_csv(processed / "review_queue.csv", index=False)

    qa_content = dashboard_content("QA_Exceptions.md", processed)
    review_content = dashboard_content("Review_Queue.md", processed)

    for content in [qa_content, review_content]:
        assert "Remaining FX requirements: `1`" in content
        assert "reviewed official-FX-unavailable keys `1`; unreviewed keys `0`" in content
        assert "not FX rate provenance, archive promotion, or REC closure" in content
    assert "REC-EX-01 row-level findings remain blocking by policy" in qa_content
    assert "unreviewed FX requirement keys are `0`, not that row-level REC findings are closed" in qa_content
    assert qa_content.index("REC-EX-01 row-level context") < qa_content.index("## Exception Summary")
    assert "REC-EX-01 row-level context" not in review_content
    assert "## Rollup Summary" in qa_content
    assert "## Reason summary" in review_content

def test_qa_and_review_dashboards_surface_realized_pnl_review_buckets(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    cache = tmp_path / "70_Imports" / "cache"
    processed.mkdir(parents=True)
    cache.mkdir(parents=True)
    pd.DataFrame([
        {
            "event_date": "2026-01-02",
            "currency": "USD",
            "use_case": "realized_pnl_trade_settlement",
            "row_count": "1",
            "amount_native_sum": "",
            "missing_reason": "same-date FX/KRW provenance required",
            "source_file_type": "transaction_history",
            "status": "fx_missing",
        },
    ], columns=FX_RATE_REQUIREMENT_COLUMNS).to_csv(processed / "fx_rate_requirements.csv", index=False)
    pd.DataFrame([
        {
            "requirement_key": "2026-01-02|USD|realized_pnl_trade_settlement",
            "decision": "still_review_gated",
            "reason_code": "official_fx_unavailable_same_date",
            "operator_review_label": "official_fx_unavailable_non_business_day",
        },
    ]).to_csv(cache / "fx_unavailable_exceptions.csv", index=False)
    realized_rows = [
        {
            "position_status": "closed",
            "cost_basis_method": "fifo",
            "amount_review_status": "fx_missing",
            "fx_status": "fx_missing",
            "amount_review_reason": "same-date FX provenance required",
        },
        {
            "position_status": "closed",
            "cost_basis_method": "fifo",
            "amount_review_status": "lot_missing",
            "fx_status": "not_required",
            "amount_review_reason": "sell quantity exceeds matched buy lots",
        },
        {
            "position_status": "closed",
            "cost_basis_method": "fifo",
            "amount_review_status": "unit_ambiguous",
            "fx_status": "not_required",
            "amount_review_reason": "quantity/unit price interpretation requires review",
        },
        {
            "position_status": "closed",
            "cost_basis_method": "fifo",
            "amount_review_status": "fx_missing",
            "fx_status": "fx_missing",
            "amount_review_reason": "sell quantity exceeds matched buy lots; same-date FX provenance required",
        },
        {
            "position_status": "closed",
            "cost_basis_method": "fifo",
            "amount_review_status": "unit_ambiguous",
            "fx_status": "not_required",
            "amount_review_reason": "sell quantity missing; sell quantity exceeds matched buy lots",
        },
    ]
    pd.DataFrame(realized_rows, columns=REALIZED_PNL_OUTPUT_COLUMNS).to_csv(processed / "processed_realized_pnl.csv", index=False)
    qa = pd.DataFrame([
        {
            "exception_id": "REC-EX-12",
            "severity": "advisory",
            "file": "70_Imports/processed/processed_realized_pnl.csv",
            "issue": "Realized PnL ledger row requires review before official profit decomposition.",
            "suggested_fix": "Review realized ledger status.",
        },
        {
            "exception_id": "REC-EX-13",
            "severity": "advisory",
            "file": "70_Imports/processed/processed_realized_pnl.csv",
            "issue": "Sell quantity exceeds matched FIFO buy lots.",
            "suggested_fix": "Review lot coverage.",
        },
        {
            "exception_id": "REC-EX-10",
            "severity": "advisory",
            "file": "70_Imports/processed/reconciliation_summary.csv",
            "issue": "Realized PnL ledger is incomplete or unavailable.",
            "suggested_fix": "Review realized ledger.",
        },
        {
            "exception_id": "REC-EX-16",
            "severity": "advisory",
            "file": "70_Imports/processed/performance_summary.csv",
            "issue": "Whole-investment performance summary is not fully available.",
            "suggested_fix": "Review realized ledger.",
        },
    ])
    qa.to_csv(processed / "qa_exceptions.csv", index=False)
    build_qa_exception_rollup(qa).to_csv(processed / "qa_exception_rollup.csv", index=False)
    pd.DataFrame([
        {
            "reason": "realized PnL review required",
            "severity": "advisory",
            "suggested_action": "Review realized ledger buckets.",
        },
    ]).to_csv(processed / "review_queue.csv", index=False)

    qa_content = dashboard_content("QA_Exceptions.md", processed)
    review_content = dashboard_content("Review_Queue.md", processed)

    for content in [qa_content, review_content]:
        assert "REC-EX-12 realized PnL review buckets" in content
        assert "reviewed official-FX-unavailable carry-through" in content
        assert "FIFO lot coverage gap" in content
        assert "unit/amount ambiguous" in content
        assert "Bucket counts can overlap" in content
        assert "not REC closure or official performance approval" in content
        assert "REC-EX-10/REC-EX-16 are downstream rollup statuses" in content
        assert "unreviewed FX requirement keys `0`" in content
        assert "| bucket | count | meaning |" not in content
        assert "> - reviewed official-FX-unavailable carry-through: `2`" in content
        assert "> - FIFO lot coverage gap: `3`" in content
        assert "> - unit/amount ambiguous: `2`" in content
    assert qa_content.index("REC-EX-12 realized PnL review buckets") < qa_content.index("## Exception Summary")
    assert review_content.index("REC-EX-12 realized PnL review buckets") < review_content.index("## Snapshot")

def test_qa_and_review_dashboards_surface_inv_ex_08_user_decision_gate(tmp_path: Path):
    processed = tmp_path / "70_Imports" / "processed"
    processed.mkdir(parents=True)
    qa = pd.DataFrame([
        {
            "exception_id": "INV-EX-08",
            "severity": "blocking",
            "file": "20_Companies/SYNTH/Company.md",
            "issue": "sell criteria missing",
            "suggested_fix": "User decision required.",
        },
        {
            "exception_id": "INV-EX-08",
            "severity": "blocking",
            "file": "20_Companies/SYNTH2/Company.md",
            "issue": "sell criteria missing",
            "suggested_fix": "User decision required.",
        },
    ])
    qa.to_csv(processed / "qa_exceptions.csv", index=False)
    build_qa_exception_rollup(qa).to_csv(processed / "qa_exception_rollup.csv", index=False)
    pd.DataFrame([
        {
            "ticker": "SYNTH",
            "security_name": "Synthetic",
            "reason": "sell criteria missing",
            "severity": "blocking",
            "suggested_action": "User-defined sell/reduce criteria required.",
        },
    ]).to_csv(processed / "review_queue.csv", index=False)

    qa_content = dashboard_content("QA_Exceptions.md", processed)
    review_content = dashboard_content("Review_Queue.md", processed)

    assert "INV-EX-08 sell criteria review" in qa_content
    assert "QA findings `2`" in qa_content
    assert "Review Queue rows" not in qa_content
    assert "INV-EX-08 sell criteria review" in review_content
    assert "Review Queue rows `1`" in review_content
    assert "QA findings" not in review_content
    for content in [qa_content, review_content]:
        assert "INV-EX-08 sell criteria review" in content
        assert "user-written operating criteria" in content
        assert "not automated thesis, sell criteria, or buy/sell recommendations" in content
        assert "thesis-break conditions" in content
        assert "keep INV-EX-08 review-gated" in content
    assert qa_content.index("INV-EX-08 sell criteria review") < qa_content.index("## Exception Summary")
    assert review_content.index("INV-EX-08 sell criteria review") < review_content.index("## Snapshot")

def test_preserve_user_written_markdown_sections(tmp_path: Path):
    note = tmp_path / "Company.md"
    note.write_text("# A\n\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\n\n## 사용자 판단 영역\nkeep me\n", encoding="utf-8")
    replace_autogenerated_block(note, "new")
    text = note.read_text(encoding="utf-8")
    assert "new" in text
    assert "keep me" in text

def test_update_only_autogenerated_block(tmp_path: Path):
    note = tmp_path / "Dashboard.md"
    note.write_text("before\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\nafter\n", encoding="utf-8")
    ok, _ = replace_autogenerated_block(note, "new")
    assert ok
    assert note.read_text(encoding="utf-8") == "before\n<!-- AUTO-GENERATED:START -->\nnew\n<!-- AUTO-GENERATED:END -->\nafter\n"

def test_update_only_autogenerated_block_preserves_bom_and_outside_text(tmp_path: Path):
    note = tmp_path / "Company.md"
    before = "outside before\n<!-- AUTO-GENERATED:START -->\nold\n<!-- AUTO-GENERATED:END -->\noutside after"
    note.write_bytes(b"\xef\xbb\xbf" + before.encode("utf-8"))
    ok, _ = replace_autogenerated_block(note, "new")
    assert ok
    after = note.read_bytes()
    assert after.startswith(b"\xef\xbb\xbf")
    assert after.decode("utf-8-sig") == "outside before\n<!-- AUTO-GENERATED:START -->\nnew\n<!-- AUTO-GENERATED:END -->\noutside after"

def test_bootstrap_autogenerated_block_adds_markers_and_preserves_user_content(tmp_path: Path):
    note = tmp_path / "20_Companies" / "005930" / "Company.md"
    note.parent.mkdir(parents=True)
    note.write_text("---\nticker: \"005930\"\n---\n\n# 005930 - Samsung Electronics\n\n## User thesis\nkeep this section\n", encoding="utf-8")
    ok, warning = bootstrap_autogenerated_block(note, heading="Auto-generated update area")
    assert ok, warning
    text = note.read_text(encoding="utf-8")
    assert AUTO_START in text
    assert AUTO_END in text
    assert "## Auto-generated update area" in text
    assert "## User thesis\nkeep this section" in text
    assert text.index(AUTO_START) < text.index("## User thesis")

def test_bootstrap_autogenerated_block_does_not_duplicate_existing_markers(tmp_path: Path):
    note = tmp_path / "20_Companies" / "005930" / "Company.md"
    note.parent.mkdir(parents=True)
    before = f"# A\n\n{AUTO_START}\nold\n{AUTO_END}\n\nmanual"
    note.write_text(before, encoding="utf-8")
    ok, warning = bootstrap_autogenerated_block(note)
    assert ok, warning
    assert note.read_text(encoding="utf-8") == before
    assert note.read_text(encoding="utf-8").count(AUTO_START) == 1

def test_bootstrap_autogenerated_block_preserves_bom(tmp_path: Path):
    note = tmp_path / "20_Companies" / "005930" / "Company.md"
    note.parent.mkdir(parents=True)
    note.write_bytes(b"\xef\xbb\xbf" + "# A\n\nmanual".encode("utf-8"))
    ok, warning = bootstrap_autogenerated_block(note)
    assert ok, warning
    assert note.read_bytes().startswith(b"\xef\xbb\xbf")
    assert "manual" in note.read_text(encoding="utf-8-sig")

def test_bootstrap_autogenerated_block_does_not_create_sensitive_generated_content(tmp_path: Path):
    note = tmp_path / "20_Companies" / "005930" / "Company.md"
    note.parent.mkdir(parents=True)
    note.write_text("# 005930 - Samsung Electronics\n\nmanual", encoding="utf-8")
    ok, warning = bootstrap_autogenerated_block(note)
    assert ok, warning
    assert scan_generated_markdown_sensitive(tmp_path) == []
