from __future__ import annotations

import argparse
import csv
import hashlib
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


AUTO_START = "<!-- AUTO-GENERATED:START -->"
AUTO_END = "<!-- AUTO-GENERATED:END -->"
BALANCE_SOURCE_TYPES = {"holdings", "overseas_balance"}
TRANSACTION_SOURCE_TYPES = {"transaction_history", "transactions", "cashflow"}
BLANK_VALUES = {"", "nan", "none", "na", "n/a", "<na>"}

SENSITIVE_PATTERNS = [
    re.compile(r"\b(?!20\d{2}-\d{2}-\d{2}\b)\d{2,6}-\d{2,8}-\d{2,8}\b"),
    re.compile(r"\b\d{6}-[1-4]\d{6}\b"),
    re.compile(r"\b01[016789]-?\d{3,4}-?\d{4}\b"),
    re.compile(r"(?i)(api[_-]?key|api[_-]?secret|access[_-]?token|password|order[_-]?password|account[_-]?number|certificate)\s*[:=]\s*\S+"),
]


@dataclass
class GateResult:
    name: str
    status: str
    detail: str


def repo_root_from_script() -> Path:
    return Path(__file__).resolve().parents[1]


def is_blank(value: object) -> bool:
    return str(value or "").strip().lower() in BLANK_VALUES


def read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def write_result(results: list[GateResult], name: str, status: str, detail: str) -> None:
    results.append(GateResult(name=name, status=status, detail=detail))
    print(f"[{status}] {name}: {detail}")


def worst_status(results: Iterable[GateResult]) -> str:
    statuses = [r.status for r in results]
    if "FAIL" in statuses:
        return "FAIL"
    if "WARN" in statuses:
        return "WARN"
    return "PASS"


def snapshot_raw_files(raw_dir: Path) -> dict[str, tuple[int, int]]:
    if not raw_dir.exists():
        return {}
    snapshot: dict[str, tuple[int, int]] = {}
    for path in sorted(raw_dir.rglob("*")):
        if path.is_file():
            stat = path.stat()
            snapshot[str(path.relative_to(raw_dir))] = (stat.st_mtime_ns, stat.st_size)
    return snapshot


def strip_auto_generated_blocks(text: str) -> str:
    pattern = re.compile(re.escape(AUTO_START) + r".*?" + re.escape(AUTO_END), re.S)
    return pattern.sub(f"{AUTO_START}\n<AUTO-GENERATED>\n{AUTO_END}", text)


def snapshot_markdown_outside_auto(vault_root: Path) -> dict[str, str]:
    snapshot: dict[str, str] = {}
    for path in sorted(vault_root.rglob("*.md")):
        if any(part in {".git", ".obsidian"} for part in path.parts):
            continue
        text = path.read_text(encoding="utf-8-sig", errors="ignore")
        normalized = strip_auto_generated_blocks(text)
        digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()
        snapshot[str(path.relative_to(vault_root))] = digest
    return snapshot


def changed_entries(before: dict[str, object], after: dict[str, object]) -> list[str]:
    changed = []
    for key, old_value in before.items():
        if key not in after:
            changed.append(f"{key} removed")
        elif after[key] != old_value:
            changed.append(key)
    return changed


def run_command(args: list[str], cwd: Path) -> tuple[int, str]:
    proc = subprocess.run(args, cwd=cwd, text=True, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    return proc.returncode, proc.stdout


def scan_generated_markdown_sensitive(vault_root: Path) -> list[str]:
    findings: list[str] = []
    block_pattern = re.compile(re.escape(AUTO_START) + r"(.*?)" + re.escape(AUTO_END), re.S)
    for path in sorted(vault_root.rglob("*.md")):
        text = path.read_text(encoding="utf-8-sig", errors="ignore")
        for match in block_pattern.finditer(text):
            block = match.group(1)
            for pattern in SENSITIVE_PATTERNS:
                if pattern.search(block):
                    findings.append(str(path.relative_to(vault_root)))
                    break
    return findings


def summary_map(processed_dir: Path) -> dict[str, str]:
    return {row.get("metric", ""): row.get("value", "") for row in read_csv_rows(processed_dir / "portfolio_summary.csv")}


def check_processed_integrity(vault_root: Path, results: list[GateResult]) -> None:
    processed_dir = vault_root / "70_Imports" / "processed"
    source_index = read_csv_rows(processed_dir / "source_file_index.csv")
    transactions = read_csv_rows(processed_dir / "processed_transactions.csv")
    holdings = read_csv_rows(processed_dir / "processed_holdings.csv")
    summary = summary_map(processed_dir)

    if not source_index:
        write_result(results, "processed/source_file_index.csv", "FAIL", "source_file_index.csv is missing or empty.")
        return

    source_types = [row.get("source_file_type", "") for row in source_index]
    transaction_file_count = sum(1 for value in source_types if value in TRANSACTION_SOURCE_TYPES)
    holdings_file_count = sum(1 for value in source_types if value in BALANCE_SOURCE_TYPES)
    write_result(results, "source type split", "PASS", f"transaction_history={transaction_file_count}, holdings={holdings_file_count}")

    bad_transaction_values = []
    for idx, row in enumerate(transactions, start=2):
        if row.get("source_file_type") in {"transaction_history", "transactions"}:
            for field in ["balance_quantity", "evaluation_amount", "unrealized_pnl", "pnl_pct"]:
                if not is_blank(row.get(field, "")):
                    bad_transaction_values.append(f"row {idx} {field}={row.get(field)}")
                    break
    if bad_transaction_values:
        write_result(results, "transaction rows do not carry balance metrics", "FAIL", "; ".join(bad_transaction_values[:5]))
    else:
        write_result(results, "transaction rows do not carry balance metrics", "PASS", "transaction_history rows keep balance/evaluation/pnl fields blank.")

    bad_holding_rows = []
    for idx, row in enumerate(holdings, start=2):
        if row.get("source_file_type") not in BALANCE_SOURCE_TYPES:
            bad_holding_rows.append(f"row {idx} source_file_type={row.get('source_file_type')}")
            continue
        balance = float(row.get("balance_quantity") or 0)
        evaluation = float(row.get("evaluation_amount") or 0)
        if abs(balance) <= 1e-9 and abs(evaluation) <= 1e-9:
            bad_holding_rows.append(f"row {idx} has no current position signal")
    if bad_holding_rows:
        write_result(results, "processed_holdings current-only contract", "FAIL", "; ".join(bad_holding_rows[:5]))
    else:
        write_result(results, "processed_holdings current-only contract", "PASS", f"{len(holdings)} current holding rows.")

    if holdings_file_count == 0:
        checks = {
            "processed_holdings empty": len(holdings) == 0,
            "balance_data_available false": summary.get("balance_data_available", "").lower() == "false",
            "total_portfolio_value_status unknown": summary.get("total_portfolio_value_status", "") == "unknown",
            "total_portfolio_value blank": is_blank(summary.get("total_portfolio_value", "")),
        }
        failed = [name for name, ok in checks.items() if not ok]
        if failed:
            write_result(results, "no balance file contract", "FAIL", ", ".join(failed))
        else:
            write_result(results, "no balance file contract", "PASS", "holdings unavailable and portfolio value status is unknown.")
    elif summary.get("total_portfolio_value_status") == "available":
        write_result(results, "balance file contract", "PASS", "balance files present and portfolio summary is available.")
    else:
        write_result(results, "balance file contract", "FAIL", f"unexpected status={summary.get('total_portfolio_value_status')}")


def quality_gate(vault_root: Path) -> int:
    scripts_dir = vault_root / "70_Imports" / "scripts"
    raw_dir = vault_root / "70_Imports" / "raw"
    results: list[GateResult] = []

    raw_before = snapshot_raw_files(raw_dir)
    md_before = snapshot_markdown_outside_auto(vault_root)

    command = [sys.executable, "main.py", "all", "--vault-root", "../..", "--raw-dir", "../raw"]
    code, output = run_command(command, scripts_dir)
    if code == 0:
        detail = output.strip().splitlines()[-1] if output.strip() else "completed"
        write_result(results, "python main.py all --vault-root ../.. --raw-dir ../raw", "PASS", detail)
    else:
        write_result(results, "python main.py all --vault-root ../.. --raw-dir ../raw", "FAIL", output.strip())

    pytest_command = [sys.executable, "-m", "pytest"]
    code, output = run_command(pytest_command, scripts_dir)
    if code == 0:
        detail = output.strip().splitlines()[-1] if output.strip() else "pytest completed"
        write_result(results, "pytest", "PASS", detail)
    else:
        write_result(results, "pytest", "FAIL", output.strip())

    raw_changes = changed_entries(raw_before, snapshot_raw_files(raw_dir))
    if raw_changes:
        write_result(results, "raw immutable mtime/size", "FAIL", "; ".join(raw_changes[:10]))
    else:
        write_result(results, "raw immutable mtime/size", "PASS", f"{len(raw_before)} raw files unchanged.")

    md_changes = changed_entries(md_before, snapshot_markdown_outside_auto(vault_root))
    if md_changes:
        write_result(results, "AUTO-GENERATED outside-block guard", "FAIL", "; ".join(md_changes[:10]))
    else:
        write_result(results, "AUTO-GENERATED outside-block guard", "PASS", "pre-existing Markdown outside AUTO-GENERATED blocks unchanged.")

    check_processed_integrity(vault_root, results)

    sensitive_findings = scan_generated_markdown_sensitive(vault_root)
    if sensitive_findings:
        write_result(results, "generated Markdown sensitive scan", "FAIL", "; ".join(sensitive_findings[:10]))
    else:
        write_result(results, "generated Markdown sensitive scan", "PASS", "no sensitive-data candidates in AUTO-GENERATED blocks.")

    final_status = worst_status(results)
    print(f"[{final_status}] quality_gate: {len(results)} checks completed.")
    return 1 if final_status == "FAIL" else 0


def main() -> int:
    parser = argparse.ArgumentParser(description="06_Stock development quality gate")
    parser.add_argument("--vault-root", default=str(repo_root_from_script()), help="06_Stock vault root")
    args = parser.parse_args()
    return quality_gate(Path(args.vault_root).resolve())


if __name__ == "__main__":
    raise SystemExit(main())
